// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shopee.sql

package shopeedb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const apagarCredencial = `-- name: ApagarCredencial :exec
DELETE FROM credenciais_shopee WHERE usuario_id = $1
`

func (q *Queries) ApagarCredencial(ctx context.Context, usuarioID uuid.UUID) error {
	_, err := q.db.Exec(ctx, apagarCredencial, usuarioID)
	return err
}

const credencialDoUsuario = `-- name: CredencialDoUsuario :one
SELECT usuario_id, app_id, secret_cifrado, dek_cifrada, kek_id, status, verificado_em, criado_em, atualizado_em FROM credenciais_shopee WHERE usuario_id = $1
`

func (q *Queries) CredencialDoUsuario(ctx context.Context, usuarioID uuid.UUID) (CredenciaisShopee, error) {
	row := q.db.QueryRow(ctx, credencialDoUsuario, usuarioID)
	var i CredenciaisShopee
	err := row.Scan(
		&i.UsuarioID,
		&i.AppID,
		&i.SecretCifrado,
		&i.DekCifrada,
		&i.KekID,
		&i.Status,
		&i.VerificadoEm,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const marcarStatusCredencial = `-- name: MarcarStatusCredencial :execrows
UPDATE credenciais_shopee
SET status = $2, verificado_em = now(), atualizado_em = now()
WHERE usuario_id = $1
`

type MarcarStatusCredencialParams struct {
	UsuarioID uuid.UUID
	Status    CredencialStatus
}

func (q *Queries) MarcarStatusCredencial(ctx context.Context, arg MarcarStatusCredencialParams) (int64, error) {
	result, err := q.db.Exec(ctx, marcarStatusCredencial, arg.UsuarioID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const salvarCredencial = `-- name: SalvarCredencial :one
INSERT INTO credenciais_shopee (usuario_id, app_id, secret_cifrado, dek_cifrada, kek_id, status, verificado_em)
VALUES ($1, $2, $3, $4, $5, 'conectado', $6)
ON CONFLICT (usuario_id) DO UPDATE SET
    app_id = excluded.app_id,
    secret_cifrado = excluded.secret_cifrado,
    dek_cifrada = excluded.dek_cifrada,
    kek_id = excluded.kek_id,
    status = 'conectado',
    verificado_em = excluded.verificado_em,
    atualizado_em = now()
RETURNING usuario_id, app_id, secret_cifrado, dek_cifrada, kek_id, status, verificado_em, criado_em, atualizado_em
`

type SalvarCredencialParams struct {
	UsuarioID     uuid.UUID
	AppID         string
	SecretCifrado []byte
	DekCifrada    []byte
	KekID         string
	VerificadoEm  time.Time
}

func (q *Queries) SalvarCredencial(ctx context.Context, arg SalvarCredencialParams) (CredenciaisShopee, error) {
	row := q.db.QueryRow(ctx, salvarCredencial,
		arg.UsuarioID,
		arg.AppID,
		arg.SecretCifrado,
		arg.DekCifrada,
		arg.KekID,
		arg.VerificadoEm,
	)
	var i CredenciaisShopee
	err := row.Scan(
		&i.UsuarioID,
		&i.AppID,
		&i.SecretCifrado,
		&i.DekCifrada,
		&i.KekID,
		&i.Status,
		&i.VerificadoEm,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}
