// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package produtosdb

import (
	"context"
	"errors"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const inserirSnapshot = `-- name: InserirSnapshot :batchexec
INSERT INTO produto_snapshots (produto_id, coletado_em, preco_min_centavos, preco_max_centavos, comissao_bp, vendas, nota)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (produto_id, coletado_em) DO NOTHING
`

type InserirSnapshotBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InserirSnapshotParams struct {
	ProdutoID        uuid.UUID
	ColetadoEm       time.Time
	PrecoMinCentavos int64
	PrecoMaxCentavos int64
	ComissaoBp       int32
	Vendas           int64
	Nota             *float64
}

func (q *Queries) InserirSnapshot(ctx context.Context, arg []InserirSnapshotParams) *InserirSnapshotBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ProdutoID,
			a.ColetadoEm,
			a.PrecoMinCentavos,
			a.PrecoMaxCentavos,
			a.ComissaoBp,
			a.Vendas,
			a.Nota,
		}
		batch.Queue(inserirSnapshot, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InserirSnapshotBatchResults{br, len(arg), false}
}

func (b *InserirSnapshotBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InserirSnapshotBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertProduto = `-- name: UpsertProduto :batchone
INSERT INTO produtos (
    fonte, item_id, loja_id, loja_nome, nome, imagem_url, categoria_id, categorias, url,
    preco_min_centavos, preco_max_centavos, comissao_bp, vendas, nota, coletado_em
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15
)
ON CONFLICT (fonte, item_id) DO UPDATE SET
    loja_id = excluded.loja_id,
    loja_nome = excluded.loja_nome,
    nome = excluded.nome,
    imagem_url = excluded.imagem_url,
    categoria_id = excluded.categoria_id,
    categorias = excluded.categorias,
    url = excluded.url,
    preco_min_centavos = excluded.preco_min_centavos,
    preco_max_centavos = excluded.preco_max_centavos,
    comissao_bp = excluded.comissao_bp,
    vendas = excluded.vendas,
    nota = excluded.nota,
    coletado_em = excluded.coletado_em
WHERE produtos.coletado_em <= excluded.coletado_em
RETURNING id
`

type UpsertProdutoBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertProdutoParams struct {
	Fonte            Fonte
	ItemID           int64
	LojaID           int64
	LojaNome         string
	Nome             string
	ImagemUrl        *string
	CategoriaID      *int64
	Categorias       []int64
	Url              string
	PrecoMinCentavos int64
	PrecoMaxCentavos int64
	ComissaoBp       int32
	Vendas           int64
	Nota             *float64
	ColetadoEm       time.Time
}

func (q *Queries) UpsertProduto(ctx context.Context, arg []UpsertProdutoParams) *UpsertProdutoBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Fonte,
			a.ItemID,
			a.LojaID,
			a.LojaNome,
			a.Nome,
			a.ImagemUrl,
			a.CategoriaID,
			a.Categorias,
			a.Url,
			a.PrecoMinCentavos,
			a.PrecoMaxCentavos,
			a.ComissaoBp,
			a.Vendas,
			a.Nota,
			a.ColetadoEm,
		}
		batch.Queue(upsertProduto, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertProdutoBatchResults{br, len(arg), false}
}

func (b *UpsertProdutoBatchResults) QueryRow(f func(int, uuid.UUID, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var id uuid.UUID
		if b.closed {
			if f != nil {
				f(t, id, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(&id)
		if f != nil {
			f(t, id, err)
		}
	}
}

func (b *UpsertProdutoBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
