// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: produtos.sql

package produtosdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const categoriasMonitoradas = `-- name: CategoriasMonitoradas :many
SELECT id FROM categorias WHERE fonte = $1 AND monitorar ORDER BY id
`

func (q *Queries) CategoriasMonitoradas(ctx context.Context, fonte Fonte) ([]int64, error) {
	rows, err := q.db.Query(ctx, categoriasMonitoradas, fonte)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const garantirParticaoSnapshots = `-- name: GarantirParticaoSnapshots :exec
SELECT garantir_particao_snapshots(($1::timestamptz)::date)
`

func (q *Queries) GarantirParticaoSnapshots(ctx context.Context, mes time.Time) error {
	_, err := q.db.Exec(ctx, garantirParticaoSnapshots, mes)
	return err
}

const historico = `-- name: Historico :many
SELECT coletado_em, preco_min_centavos, preco_max_centavos, comissao_bp, vendas, nota
FROM produto_snapshots
WHERE produto_id = $1 AND coletado_em >= $2
ORDER BY coletado_em
`

type HistoricoParams struct {
	ProdutoID uuid.UUID
	Desde     time.Time
}

type HistoricoRow struct {
	ColetadoEm       time.Time
	PrecoMinCentavos int64
	PrecoMaxCentavos int64
	ComissaoBp       int32
	Vendas           int64
	Nota             *float64
}

func (q *Queries) Historico(ctx context.Context, arg HistoricoParams) ([]HistoricoRow, error) {
	rows, err := q.db.Query(ctx, historico, arg.ProdutoID, arg.Desde)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HistoricoRow
	for rows.Next() {
		var i HistoricoRow
		if err := rows.Scan(
			&i.ColetadoEm,
			&i.PrecoMinCentavos,
			&i.PrecoMaxCentavos,
			&i.ComissaoBp,
			&i.Vendas,
			&i.Nota,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nomesCategorias = `-- name: NomesCategorias :many
SELECT id, nome FROM categorias WHERE fonte = $1 AND id = ANY ($2::bigint[])
`

type NomesCategoriasParams struct {
	Fonte Fonte
	Ids   []int64
}

type NomesCategoriasRow struct {
	ID   int64
	Nome string
}

func (q *Queries) NomesCategorias(ctx context.Context, arg NomesCategoriasParams) ([]NomesCategoriasRow, error) {
	rows, err := q.db.Query(ctx, nomesCategorias, arg.Fonte, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NomesCategoriasRow
	for rows.Next() {
		var i NomesCategoriasRow
		if err := rows.Scan(&i.ID, &i.Nome); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const paraTendencias = `-- name: ParaTendencias :many
SELECT
    p.id, p.nome, p.loja_nome, p.imagem_url, p.categoria_id, p.categorias, p.url,
    p.preco_min_centavos, p.preco_max_centavos, p.comissao_bp, p.vendas, p.nota, p.coletado_em,
    COALESCE(antes.vendas, depois.vendas)::bigint AS base_vendas,
    COALESCE(antes.coletado_em, depois.coletado_em)::timestamptz AS base_coletado_em
FROM produtos p
LEFT JOIN LATERAL (
    SELECT s.vendas, s.coletado_em FROM produto_snapshots s
    WHERE s.produto_id = p.id
      AND s.coletado_em BETWEEN p.coletado_em - interval '14 days' AND p.coletado_em - interval '7 days'
    ORDER BY s.coletado_em DESC
    LIMIT 1
) antes ON true
LEFT JOIN LATERAL (
    SELECT s.vendas, s.coletado_em FROM produto_snapshots s
    WHERE s.produto_id = p.id AND s.coletado_em > p.coletado_em - interval '7 days'
    ORDER BY s.coletado_em
    LIMIT 1
) depois ON true
WHERE p.coletado_em >= $1
`

type ParaTendenciasRow struct {
	ID               uuid.UUID
	Nome             string
	LojaNome         string
	ImagemUrl        *string
	CategoriaID      *int64
	Categorias       []int64
	Url              string
	PrecoMinCentavos int64
	PrecoMaxCentavos int64
	ComissaoBp       int32
	Vendas           int64
	Nota             *float64
	ColetadoEm       time.Time
	BaseVendas       int64
	BaseColetadoEm   time.Time
}

// Dados atuais de cada produto coletado desde @desde e a base para medir o
// crescimento: o snapshot mais recente com 7 a 14 dias, ou, se ainda não
// houver, o mais antigo dos últimos 7 dias.
func (q *Queries) ParaTendencias(ctx context.Context, desde time.Time) ([]ParaTendenciasRow, error) {
	rows, err := q.db.Query(ctx, paraTendencias, desde)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ParaTendenciasRow
	for rows.Next() {
		var i ParaTendenciasRow
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.LojaNome,
			&i.ImagemUrl,
			&i.CategoriaID,
			&i.Categorias,
			&i.Url,
			&i.PrecoMinCentavos,
			&i.PrecoMaxCentavos,
			&i.ComissaoBp,
			&i.Vendas,
			&i.Nota,
			&i.ColetadoEm,
			&i.BaseVendas,
			&i.BaseColetadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const produto = `-- name: Produto :one
SELECT id, fonte, item_id, loja_id, loja_nome, nome, imagem_url, categoria_id, categorias, url, preco_min_centavos, preco_max_centavos, comissao_bp, vendas, nota, coletado_em, criado_em FROM produtos WHERE id = $1
`

func (q *Queries) Produto(ctx context.Context, id uuid.UUID) (Produto, error) {
	row := q.db.QueryRow(ctx, produto, id)
	var i Produto
	err := row.Scan(
		&i.ID,
		&i.Fonte,
		&i.ItemID,
		&i.LojaID,
		&i.LojaNome,
		&i.Nome,
		&i.ImagemUrl,
		&i.CategoriaID,
		&i.Categorias,
		&i.Url,
		&i.PrecoMinCentavos,
		&i.PrecoMaxCentavos,
		&i.ComissaoBp,
		&i.Vendas,
		&i.Nota,
		&i.ColetadoEm,
		&i.CriadoEm,
	)
	return i, err
}

const produtoPorItem = `-- name: ProdutoPorItem :one
SELECT id FROM produtos WHERE fonte = $1 AND item_id = $2
`

type ProdutoPorItemParams struct {
	Fonte  Fonte
	ItemID int64
}

func (q *Queries) ProdutoPorItem(ctx context.Context, arg ProdutoPorItemParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, produtoPorItem, arg.Fonte, arg.ItemID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertCategoria = `-- name: UpsertCategoria :exec
INSERT INTO categorias (fonte, id, nome, monitorar) VALUES ($1, $2, $3, $4)
ON CONFLICT (fonte, id) DO UPDATE SET nome = excluded.nome, monitorar = excluded.monitorar
`

type UpsertCategoriaParams struct {
	Fonte     Fonte
	ID        int64
	Nome      string
	Monitorar bool
}

func (q *Queries) UpsertCategoria(ctx context.Context, arg UpsertCategoriaParams) error {
	_, err := q.db.Exec(ctx, upsertCategoria,
		arg.Fonte,
		arg.ID,
		arg.Nome,
		arg.Monitorar,
	)
	return err
}
