// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: curadoria.sql

package curadoriadb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const adicionarItemLista = `-- name: AdicionarItemLista :execrows
INSERT INTO lista_itens (lista_id, workspace_id, produto_id, comentario, ordem)
SELECT $1, $2, $3, $4, coalesce(max(ordem), 0) + 1
FROM lista_itens WHERE lista_id = $1 AND workspace_id = $2
ON CONFLICT (lista_id, produto_id) DO NOTHING
`

type AdicionarItemListaParams struct {
	ListaID     uuid.UUID
	WorkspaceID uuid.UUID
	ProdutoID   uuid.UUID
	Comentario  string
}

func (q *Queries) AdicionarItemLista(ctx context.Context, arg AdicionarItemListaParams) (int64, error) {
	result, err := q.db.Exec(ctx, adicionarItemLista,
		arg.ListaID,
		arg.WorkspaceID,
		arg.ProdutoID,
		arg.Comentario,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const apagarLista = `-- name: ApagarLista :execrows
DELETE FROM listas_curadoria WHERE id = $1 AND workspace_id = $2
`

type ApagarListaParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) ApagarLista(ctx context.Context, arg ApagarListaParams) (int64, error) {
	result, err := q.db.Exec(ctx, apagarLista, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const atualizarLista = `-- name: AtualizarLista :execrows
UPDATE listas_curadoria SET
    titulo = coalesce($1, titulo),
    descricao = coalesce($2, descricao),
    atualizado_em = now()
WHERE id = $3 AND workspace_id = $4
`

type AtualizarListaParams struct {
	Titulo      *string
	Descricao   *string
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) AtualizarLista(ctx context.Context, arg AtualizarListaParams) (int64, error) {
	result, err := q.db.Exec(ctx, atualizarLista,
		arg.Titulo,
		arg.Descricao,
		arg.ID,
		arg.WorkspaceID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const comentarItemLista = `-- name: ComentarItemLista :execrows
UPDATE lista_itens SET comentario = $1
WHERE lista_id = $2 AND workspace_id = $3 AND produto_id = $4
`

type ComentarItemListaParams struct {
	Comentario  string
	ListaID     uuid.UUID
	WorkspaceID uuid.UUID
	ProdutoID   uuid.UUID
}

func (q *Queries) ComentarItemLista(ctx context.Context, arg ComentarItemListaParams) (int64, error) {
	result, err := q.db.Exec(ctx, comentarItemLista,
		arg.Comentario,
		arg.ListaID,
		arg.WorkspaceID,
		arg.ProdutoID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const contarListas = `-- name: ContarListas :one

SELECT count(*) FROM listas_curadoria WHERE workspace_id = $1
`

// Queries do módulo curadoria. Toda query filtra por workspace_id, além da RLS
// (que esconde os rascunhos de quem não é dono nem mentor).
func (q *Queries) ContarListas(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, contarListas, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const criarLista = `-- name: CriarLista :one
INSERT INTO listas_curadoria (workspace_id, autor_id, titulo, descricao)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CriarListaParams struct {
	WorkspaceID uuid.UUID
	AutorID     uuid.UUID
	Titulo      string
	Descricao   string
}

func (q *Queries) CriarLista(ctx context.Context, arg CriarListaParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, criarLista,
		arg.WorkspaceID,
		arg.AutorID,
		arg.Titulo,
		arg.Descricao,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const importacoesPorProduto = `-- name: ImportacoesPorProduto :many
SELECT produto_id, count(*) AS importadores FROM importacoes
WHERE lista_id = $1 AND workspace_id = $2
GROUP BY produto_id
`

type ImportacoesPorProdutoParams struct {
	ListaID     uuid.UUID
	WorkspaceID uuid.UUID
}

type ImportacoesPorProdutoRow struct {
	ProdutoID    uuid.UUID
	Importadores int64
}

func (q *Queries) ImportacoesPorProduto(ctx context.Context, arg ImportacoesPorProdutoParams) ([]ImportacoesPorProdutoRow, error) {
	rows, err := q.db.Query(ctx, importacoesPorProduto, arg.ListaID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportacoesPorProdutoRow
	for rows.Next() {
		var i ImportacoesPorProdutoRow
		if err := rows.Scan(&i.ProdutoID, &i.Importadores); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const importadores = `-- name: Importadores :many
SELECT usuario_id, count(*) AS produtos, max(importado_em)::timestamptz AS ultima_em FROM importacoes
WHERE lista_id = $1 AND workspace_id = $2
GROUP BY usuario_id
ORDER BY ultima_em DESC
`

type ImportadoresParams struct {
	ListaID     uuid.UUID
	WorkspaceID uuid.UUID
}

type ImportadoresRow struct {
	UsuarioID uuid.UUID
	Produtos  int64
	UltimaEm  time.Time
}

func (q *Queries) Importadores(ctx context.Context, arg ImportadoresParams) ([]ImportadoresRow, error) {
	rows, err := q.db.Query(ctx, importadores, arg.ListaID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ImportadoresRow
	for rows.Next() {
		var i ImportadoresRow
		if err := rows.Scan(&i.UsuarioID, &i.Produtos, &i.UltimaEm); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const itensDaLista = `-- name: ItensDaLista :many
SELECT produto_id, comentario, ordem FROM lista_itens
WHERE lista_id = $1 AND workspace_id = $2
ORDER BY ordem, produto_id
`

type ItensDaListaParams struct {
	ListaID     uuid.UUID
	WorkspaceID uuid.UUID
}

type ItensDaListaRow struct {
	ProdutoID  uuid.UUID
	Comentario string
	Ordem      int32
}

func (q *Queries) ItensDaLista(ctx context.Context, arg ItensDaListaParams) ([]ItensDaListaRow, error) {
	rows, err := q.db.Query(ctx, itensDaLista, arg.ListaID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItensDaListaRow
	for rows.Next() {
		var i ItensDaListaRow
		if err := rows.Scan(&i.ProdutoID, &i.Comentario, &i.Ordem); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lista = `-- name: Lista :one
SELECT l.id, l.titulo, l.descricao, l.publicada_em, l.criado_em, l.atualizado_em,
    (SELECT count(*) FROM lista_itens li
     WHERE li.lista_id = l.id AND li.workspace_id = $1) AS produtos,
    (SELECT count(DISTINCT i.usuario_id) FROM importacoes i
     WHERE i.lista_id = l.id AND i.workspace_id = $1) AS importadores,
    EXISTS (SELECT 1 FROM importacoes i
            WHERE i.lista_id = l.id AND i.workspace_id = $1 AND i.usuario_id = $2) AS importei
FROM listas_curadoria l
WHERE l.id = $3 AND l.workspace_id = $1
  AND ($4::boolean OR l.publicada_em IS NOT NULL)
`

type ListaParams struct {
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
	ID          uuid.UUID
	Rascunhos   bool
}

type ListaRow struct {
	ID           uuid.UUID
	Titulo       string
	Descricao    string
	PublicadaEm  *time.Time
	CriadoEm     time.Time
	AtualizadoEm time.Time
	Produtos     int64
	Importadores int64
	Importei     bool
}

func (q *Queries) Lista(ctx context.Context, arg ListaParams) (ListaRow, error) {
	row := q.db.QueryRow(ctx, lista,
		arg.WorkspaceID,
		arg.UsuarioID,
		arg.ID,
		arg.Rascunhos,
	)
	var i ListaRow
	err := row.Scan(
		&i.ID,
		&i.Titulo,
		&i.Descricao,
		&i.PublicadaEm,
		&i.CriadoEm,
		&i.AtualizadoEm,
		&i.Produtos,
		&i.Importadores,
		&i.Importei,
	)
	return i, err
}

const listas = `-- name: Listas :many
SELECT l.id, l.titulo, l.descricao, l.publicada_em, l.criado_em, l.atualizado_em,
    (SELECT count(*) FROM lista_itens li
     WHERE li.lista_id = l.id AND li.workspace_id = $1) AS produtos,
    (SELECT count(DISTINCT i.usuario_id) FROM importacoes i
     WHERE i.lista_id = l.id AND i.workspace_id = $1) AS importadores,
    EXISTS (SELECT 1 FROM importacoes i
            WHERE i.lista_id = l.id AND i.workspace_id = $1 AND i.usuario_id = $2) AS importei
FROM listas_curadoria l
WHERE l.workspace_id = $1
  AND ($3::boolean OR l.publicada_em IS NOT NULL)
ORDER BY l.publicada_em IS NOT NULL, coalesce(l.publicada_em, l.criado_em) DESC, l.id
`

type ListasParams struct {
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
	Rascunhos   bool
}

type ListasRow struct {
	ID           uuid.UUID
	Titulo       string
	Descricao    string
	PublicadaEm  *time.Time
	CriadoEm     time.Time
	AtualizadoEm time.Time
	Produtos     int64
	Importadores int64
	Importei     bool
}

// Os rascunhos só voltam com rascunhos = true (e a RLS só os mostra a
// dono e mentor). importadores conta a turma; importei, o próprio usuário.
func (q *Queries) Listas(ctx context.Context, arg ListasParams) ([]ListasRow, error) {
	rows, err := q.db.Query(ctx, listas, arg.WorkspaceID, arg.UsuarioID, arg.Rascunhos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListasRow
	for rows.Next() {
		var i ListasRow
		if err := rows.Scan(
			&i.ID,
			&i.Titulo,
			&i.Descricao,
			&i.PublicadaEm,
			&i.CriadoEm,
			&i.AtualizadoEm,
			&i.Produtos,
			&i.Importadores,
			&i.Importei,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const minhasImportacoes = `-- name: MinhasImportacoes :many
SELECT produto_id FROM importacoes
WHERE lista_id = $1 AND workspace_id = $2 AND usuario_id = $3
`

type MinhasImportacoesParams struct {
	ListaID     uuid.UUID
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
}

func (q *Queries) MinhasImportacoes(ctx context.Context, arg MinhasImportacoesParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, minhasImportacoes, arg.ListaID, arg.WorkspaceID, arg.UsuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var produto_id uuid.UUID
		if err := rows.Scan(&produto_id); err != nil {
			return nil, err
		}
		items = append(items, produto_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ordenarItensLista = `-- name: OrdenarItensLista :execrows
UPDATE lista_itens li SET ordem = o.ordem
FROM unnest($3::uuid[]) WITH ORDINALITY AS o(produto_id, ordem)
WHERE li.lista_id = $1 AND li.workspace_id = $2 AND li.produto_id = o.produto_id
`

type OrdenarItensListaParams struct {
	ListaID     uuid.UUID
	WorkspaceID uuid.UUID
	ProdutoIds  []uuid.UUID
}

func (q *Queries) OrdenarItensLista(ctx context.Context, arg OrdenarItensListaParams) (int64, error) {
	result, err := q.db.Exec(ctx, ordenarItensLista, arg.ListaID, arg.WorkspaceID, arg.ProdutoIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const publicarLista = `-- name: PublicarLista :execrows
UPDATE listas_curadoria SET publicada_em = now(), atualizado_em = now()
WHERE id = $1 AND workspace_id = $2 AND publicada_em IS NULL
`

type PublicarListaParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

// Só a primeira publicação conta: publicar de novo não muda nada.
func (q *Queries) PublicarLista(ctx context.Context, arg PublicarListaParams) (int64, error) {
	result, err := q.db.Exec(ctx, publicarLista, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const registrarImportacao = `-- name: RegistrarImportacao :exec
INSERT INTO importacoes (lista_id, workspace_id, usuario_id, produto_id)
SELECT $1, $2, $3, unnest($4::uuid[])
ON CONFLICT DO NOTHING
`

type RegistrarImportacaoParams struct {
	ListaID     uuid.UUID
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
	ProdutoIds  []uuid.UUID
}

func (q *Queries) RegistrarImportacao(ctx context.Context, arg RegistrarImportacaoParams) error {
	_, err := q.db.Exec(ctx, registrarImportacao,
		arg.ListaID,
		arg.WorkspaceID,
		arg.UsuarioID,
		arg.ProdutoIds,
	)
	return err
}

const removerItemLista = `-- name: RemoverItemLista :execrows
DELETE FROM lista_itens
WHERE lista_id = $1 AND workspace_id = $2 AND produto_id = $3
`

type RemoverItemListaParams struct {
	ListaID     uuid.UUID
	WorkspaceID uuid.UUID
	ProdutoID   uuid.UUID
}

func (q *Queries) RemoverItemLista(ctx context.Context, arg RemoverItemListaParams) (int64, error) {
	result, err := q.db.Exec(ctx, removerItemLista, arg.ListaID, arg.WorkspaceID, arg.ProdutoID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const tocarLista = `-- name: TocarLista :exec
UPDATE listas_curadoria SET atualizado_em = now() WHERE id = $1 AND workspace_id = $2
`

type TocarListaParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) TocarLista(ctx context.Context, arg TocarListaParams) error {
	_, err := q.db.Exec(ctx, tocarLista, arg.ID, arg.WorkspaceID)
	return err
}

const travarLista = `-- name: TravarLista :one
SELECT id, publicada_em FROM listas_curadoria
WHERE id = $1 AND workspace_id = $2
FOR UPDATE
`

type TravarListaParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

type TravarListaRow struct {
	ID          uuid.UUID
	PublicadaEm *time.Time
}

func (q *Queries) TravarLista(ctx context.Context, arg TravarListaParams) (TravarListaRow, error) {
	row := q.db.QueryRow(ctx, travarLista, arg.ID, arg.WorkspaceID)
	var i TravarListaRow
	err := row.Scan(&i.ID, &i.PublicadaEm)
	return i, err
}
