// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package curadoriadb

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type Canal string

const (
	CanalInstagram Canal = "instagram"
	CanalTiktok    Canal = "tiktok"
	CanalWhatsapp  Canal = "whatsapp"
	CanalOutro     Canal = "outro"
)

func (e *Canal) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Canal(s)
	case string:
		*e = Canal(s)
	default:
		return fmt.Errorf("unsupported scan type for Canal: %T", src)
	}
	return nil
}

type NullCanal struct {
	Canal Canal
	Valid bool // Valid is true if Canal is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCanal) Scan(value interface{}) error {
	if value == nil {
		ns.Canal, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Canal.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCanal) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Canal), nil
}

type CredencialStatus string

const (
	CredencialStatusConectado CredencialStatus = "conectado"
	CredencialStatusInvalido  CredencialStatus = "invalido"
	CredencialStatusExpirado  CredencialStatus = "expirado"
)

func (e *CredencialStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CredencialStatus(s)
	case string:
		*e = CredencialStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CredencialStatus: %T", src)
	}
	return nil
}

type NullCredencialStatus struct {
	CredencialStatus CredencialStatus
	Valid            bool // Valid is true if CredencialStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCredencialStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CredencialStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CredencialStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCredencialStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CredencialStatus), nil
}

type Fonte string

const (
	FonteShopee Fonte = "shopee"
)

func (e *Fonte) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Fonte(s)
	case string:
		*e = Fonte(s)
	default:
		return fmt.Errorf("unsupported scan type for Fonte: %T", src)
	}
	return nil
}

type NullFonte struct {
	Fonte Fonte
	Valid bool // Valid is true if Fonte is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFonte) Scan(value interface{}) error {
	if value == nil {
		ns.Fonte, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Fonte.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFonte) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Fonte), nil
}

type ItemStatus string

const (
	ItemStatusTestando   ItemStatus = "testando"
	ItemStatusCampeao    ItemStatus = "campeao"
	ItemStatusDescartado ItemStatus = "descartado"
)

func (e *ItemStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ItemStatus(s)
	case string:
		*e = ItemStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ItemStatus: %T", src)
	}
	return nil
}

type NullItemStatus struct {
	ItemStatus ItemStatus
	Valid      bool // Valid is true if ItemStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullItemStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ItemStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ItemStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullItemStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ItemStatus), nil
}

type LinkOrigem string

const (
	LinkOrigemAuto   LinkOrigem = "auto"
	LinkOrigemManual LinkOrigem = "manual"
)

func (e *LinkOrigem) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LinkOrigem(s)
	case string:
		*e = LinkOrigem(s)
	default:
		return fmt.Errorf("unsupported scan type for LinkOrigem: %T", src)
	}
	return nil
}

type NullLinkOrigem struct {
	LinkOrigem LinkOrigem
	Valid      bool // Valid is true if LinkOrigem is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLinkOrigem) Scan(value interface{}) error {
	if value == nil {
		ns.LinkOrigem, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LinkOrigem.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLinkOrigem) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LinkOrigem), nil
}

type LinkStatus string

const (
	LinkStatusPendente LinkStatus = "pendente"
	LinkStatusGerando  LinkStatus = "gerando"
	LinkStatusPronto   LinkStatus = "pronto"
	LinkStatusFalhou   LinkStatus = "falhou"
)

func (e *LinkStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LinkStatus(s)
	case string:
		*e = LinkStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LinkStatus: %T", src)
	}
	return nil
}

type NullLinkStatus struct {
	LinkStatus LinkStatus
	Valid      bool // Valid is true if LinkStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLinkStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LinkStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LinkStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLinkStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LinkStatus), nil
}

type MembroPapel string

const (
	MembroPapelDono     MembroPapel = "dono"
	MembroPapelMentor   MembroPapel = "mentor"
	MembroPapelAfiliado MembroPapel = "afiliado"
)

func (e *MembroPapel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MembroPapel(s)
	case string:
		*e = MembroPapel(s)
	default:
		return fmt.Errorf("unsupported scan type for MembroPapel: %T", src)
	}
	return nil
}

type NullMembroPapel struct {
	MembroPapel MembroPapel
	Valid       bool // Valid is true if MembroPapel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMembroPapel) Scan(value interface{}) error {
	if value == nil {
		ns.MembroPapel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MembroPapel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMembroPapel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MembroPapel), nil
}

type WorkspaceTipo string

const (
	WorkspaceTipoPessoal  WorkspaceTipo = "pessoal"
	WorkspaceTipoMentoria WorkspaceTipo = "mentoria"
)

func (e *WorkspaceTipo) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkspaceTipo(s)
	case string:
		*e = WorkspaceTipo(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkspaceTipo: %T", src)
	}
	return nil
}

type NullWorkspaceTipo struct {
	WorkspaceTipo WorkspaceTipo
	Valid         bool // Valid is true if WorkspaceTipo is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkspaceTipo) Scan(value interface{}) error {
	if value == nil {
		ns.WorkspaceTipo, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkspaceTipo.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkspaceTipo) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkspaceTipo), nil
}

type Categoria struct {
	Fonte     Fonte
	ID        int64
	Nome      string
	Monitorar bool
}

type ColecaoIten struct {
	ColecaoID    uuid.UUID
	ItemID       uuid.UUID
	WorkspaceID  uuid.UUID
	UsuarioID    uuid.UUID
	AdicionadoEm time.Time
}

type Coleco struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
	Nome        string
	CriadoEm    time.Time
}

type Convite struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Email       *string
	TokenHash   []byte
	ExpiraEm    time.Time
	UsadoPor    *uuid.UUID
	UsadoEm     *time.Time
	RevogadoEm  *time.Time
	CriadoPor   uuid.UUID
	CriadoEm    time.Time
}

type CredenciaisShopee struct {
	UsuarioID     uuid.UUID
	AppID         string
	SecretCifrado []byte
	DekCifrada    []byte
	KekID         string
	Status        CredencialStatus
	VerificadoEm  time.Time
	CriadoEm      time.Time
	AtualizadoEm  time.Time
}

type Importacao struct {
	ListaID     uuid.UUID
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
	ProdutoID   uuid.UUID
	ImportadoEm time.Time
}

type ItensColecao struct {
	ID           uuid.UUID
	WorkspaceID  uuid.UUID
	UsuarioID    uuid.UUID
	ProdutoID    uuid.UUID
	Titulo       string
	Descricao    string
	Notas        string
	Tags         []string
	Status       ItemStatus
	LinkAfiliado *string
	LinkOrigem   LinkOrigem
	LinkStatus   LinkStatus
	CriadoEm     time.Time
	AtualizadoEm time.Time
}

type Limite struct {
	Plano string
	Chave string
	Valor int64
}

type LinksCanal struct {
	ItemID      uuid.UUID
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
	Canal       Canal
	SubID       string
	Url         string
	GeradoEm    time.Time
}

type ListaCuradoria struct {
	ID           uuid.UUID
	WorkspaceID  uuid.UUID
	AutorID      uuid.UUID
	Titulo       string
	Descricao    string
	PublicadaEm  *time.Time
	CriadoEm     time.Time
	AtualizadoEm time.Time
}

type ListaItem struct {
	ListaID     uuid.UUID
	WorkspaceID uuid.UUID
	ProdutoID   uuid.UUID
	Comentario  string
	Ordem       int32
}

type Membro struct {
	WorkspaceID        uuid.UUID
	UsuarioID          uuid.UUID
	Papel              MembroPapel
	ConsenteResultados bool
	EntrouEm           time.Time
}

type Notificacao struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
	Tipo        string
	Chave       string
	Titulo      string
	Corpo       string
	Url         string
	CriadoEm    time.Time
	LidaEm      *time.Time
	EmailEm     *time.Time
	PushEm      *time.Time
}

type PreferenciaNotificacao struct {
	UsuarioID    uuid.UUID
	Email        bool
	AtualizadoEm time.Time
}

type Produto struct {
	ID               uuid.UUID
	Fonte            Fonte
	ItemID           int64
	LojaID           int64
	LojaNome         string
	Nome             string
	ImagemUrl        *string
	CategoriaID      *int64
	Categorias       []int64
	Url              string
	PrecoMinCentavos int64
	PrecoMaxCentavos int64
	ComissaoBp       int32
	Vendas           int64
	Nota             *float64
	ColetadoEm       time.Time
	CriadoEm         time.Time
}

type ProdutoSnapshot struct {
	ProdutoID        uuid.UUID
	ColetadoEm       time.Time
	PrecoMinCentavos int64
	PrecoMaxCentavos int64
	ComissaoBp       int32
	Vendas           int64
	Nota             *float64
}

type ProdutoSnapshotsPadrao struct {
	ProdutoID        uuid.UUID
	ColetadoEm       time.Time
	PrecoMinCentavos int64
	PrecoMaxCentavos int64
	ComissaoBp       int32
	Vendas           int64
	Nota             *float64
}

type PushInscricao struct {
	ID        uuid.UUID
	UsuarioID uuid.UUID
	Endpoint  string
	P256dh    string
	Auth      string
	CriadoEm  time.Time
}

type Tendencia struct {
	ProdutoID             uuid.UUID
	CalculadoEm           time.Time
	Score                 float64
	GanhoPorVendaCentavos int64
	VariacaoVendas7d      *int64
	Nome                  string
	LojaNome              string
	ImagemUrl             *string
	CategoriaID           *int64
	Categorias            []int64
	Url                   string
	PrecoMinCentavos      int64
	PrecoMaxCentavos      int64
	ComissaoBp            int32
	Vendas                int64
	Nota                  *float64
	AtualizadoEm          time.Time
	Busca                 interface{}
}

type Usuario struct {
	ID              uuid.UUID
	ZitadelSub      string
	Nome            string
	Email           string
	EmailVerificado bool
	CriadoEm        time.Time
}

type Workspace struct {
	ID       uuid.UUID
	Tipo     WorkspaceTipo
	Nome     string
	FotoUrl  *string
	DonoID   uuid.UUID
	Plano    string
	Status   string
	CriadoEm time.Time
}
