/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verificação de vida do processo */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verificação de prontidão (Postgres e Redis) */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/eu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Usuário autenticado
         * @description No primeiro acesso, cria o usuário a partir do perfil do Zitadel e o seu workspace pessoal.
         */
        get: operations["eu"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspaces de que o usuário participa (seletor do topo) */
        get: operations["listarWorkspaces"];
        put?: never;
        /**
         * Criar mentoria
         * @description Cria um workspace do tipo mentoria com o usuário como dono.
         */
        post: operations["criarMentoria"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        /** Detalhe do workspace */
        get: operations["verWorkspace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Alterar nome e foto (só o dono) */
        patch: operations["atualizarWorkspace"];
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/membros": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        /** Membros do workspace (dono e mentor) */
        get: operations["listarMembros"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/membros/{usuarioId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                usuarioId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Sair do workspace ou remover um membro
         * @description Com o próprio id, o usuário sai do workspace. Dono e mentor removem afiliados; só o dono remove mentores; o dono não sai nem é removido. Os dados pessoais do afiliado (coleção, credencial) continuam dele.
         */
        delete: operations["removerMembro"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/convites": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        /** Convites pendentes (dono e mentor) */
        get: operations["listarConvites"];
        put?: never;
        /**
         * Convidar afiliado
         * @description Gera um convite de uso único para um workspace de mentoria. Com e-mail, só a conta com aquele e-mail verificado pode aceitar. Convites pendentes ocupam assento do plano. O token só aparece nesta resposta.
         */
        post: operations["criarConvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/convites/{conviteId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                conviteId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancelar convite pendente */
        delete: operations["revogarConvite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/convites/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["TokenConvite"];
            };
            cookie?: never;
        };
        /**
         * Ver convite (público)
         * @description Mostra o workspace e a situação do convite antes do login.
         */
        get: operations["verConvite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/convites/{token}/aceitar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["TokenConvite"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aceitar convite
         * @description Torna o usuário afiliado do workspace do convite.
         */
        post: operations["aceitarConvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/eu/shopee": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Situação da conexão com a Shopee
         * @description A credencial (AppID e Secret da Open API de afiliados) pertence ao usuário, não ao workspace. O Secret nunca aparece em resposta.
         */
        get: operations["verConexaoShopee"];
        /**
         * Conectar a conta de afiliado
         * @description Valida o AppID e o Secret com uma chamada de teste à Shopee e guarda a credencial cifrada (envelope encryption). Substitui a credencial anterior, se houver.
         */
        put: operations["conectarShopee"];
        post?: never;
        /** Desconectar (apaga a credencial) */
        delete: operations["desconectarShopee"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/radar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        /**
         * Radar de produtos em alta
         * @description Lista ranqueada do catálogo coletado pelo job `snapshot_catalogo` (credencial do app) com o score do job `calcular_tendencias`. Valores em centavos e comissão em basis points (1% = 100).
         */
        get: operations["radar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/radar/categorias": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        /** Categorias presentes no radar (para o filtro) */
        get: operations["radarCategorias"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/radar/produtos/{produtoId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                produtoId: string;
            };
            cookie?: never;
        };
        /** Detalhe do produto com histórico */
        get: operations["radarProduto"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/itens": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        /**
         * Produtos salvos pelo usuário no workspace
         * @description A coleção é do usuário dentro do workspace. Ninguém mais a vê, nem o mentor. Os mais recentes primeiro.
         */
        get: operations["listarItens"];
        put?: never;
        /**
         * Salvar produto
         * @description Salva um produto do radar (`produto_id`) ou colado como link da Shopee (`url`); informe só um dos dois. Um produto que não está no catálogo é buscado na Shopee com a credencial do app. O link de afiliado é gerado em segundo plano (job `gerar_link`) com a credencial do usuário, um por canal. Sem credencial conectada, o item fica com `link_status` = `pendente`. Salvar de novo o mesmo produto devolve o item existente (200).
         */
        post: operations["salvarItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/itens/produtos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        /** IDs dos produtos já salvos (para marcar o radar) */
        get: operations["produtosSalvos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/itens/links-pendentes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gerar os links que ficaram pendentes ou falharam
         * @description Use depois de conectar a conta da Shopee. Itens com link manual não mudam.
         */
        post: operations["gerarLinksPendentes"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/itens/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        /** Detalhe do item */
        get: operations["verItem"];
        put?: never;
        post?: never;
        /** Remover o item (e os seus links) */
        delete: operations["removerItem"];
        options?: never;
        head?: never;
        /**
         * Editar título, descrição, notas, tags, status e link
         * @description Campos ausentes não mudam. Texto vazio apaga o campo. `link_afiliado` com uma URL grava um link manual, que tem prioridade sobre o automático; `null` volta ao link automático e gera de novo.
         */
        patch: operations["atualizarItem"];
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/itens/{itemId}/link": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Gerar o link automático de novo
         * @description Descarta o link manual, se houver, e enfileira o job `gerar_link`.
         */
        post: operations["gerarLinkItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/itens/{itemId}/colecoes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Definir as coleções do item
         * @description Substitui a lista. Um item pode estar em várias coleções.
         */
        put: operations["definirColecoesItem"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/colecoes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        /** Coleções (pastas) do usuário no workspace */
        get: operations["listarColecoes"];
        put?: never;
        /** Criar coleção */
        post: operations["criarColecao"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/colecoes/{colecaoId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                colecaoId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Apagar coleção
         * @description Os itens continuam salvos; só saem da coleção.
         */
        delete: operations["apagarColecao"];
        options?: never;
        head?: never;
        /** Renomear coleção */
        patch: operations["renomearColecao"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Erro: {
            /** @description Código estável para o front. Em contas: nao_autenticado, dados_invalidos, json_invalido, sem_permissao, workspace_nao_encontrado, membro_nao_encontrado, convite_nao_encontrado, so_mentoria, dono_nao_sai, sem_assentos, ja_membro, convite_expirado, convite_usado, convite_revogado, convite_outro_email, erro_interno. Em shopee: credencial_invalida, shopee_limite, shopee_indisponivel. Em radar: produto_nao_encontrado. Em coleções: item_nao_encontrado, colecao_nao_encontrada, colecao_existente, link_invalido, link_curto, sem_credencial, importacao_indisponivel. */
            codigo: string;
            /** @description Texto pronto para mostrar ao usuário */
            mensagem: string;
        };
        Usuario: {
            /** Format: uuid */
            id: string;
            nome: string;
            /** Format: email */
            email: string;
            /** Format: date-time */
            criado_em: string;
        };
        /** @enum {string} */
        Papel: "dono" | "mentor" | "afiliado";
        Workspace: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            tipo: "pessoal" | "mentoria";
            nome: string;
            foto_url: string | null;
            /** @enum {string} */
            plano: "avulso" | "mentoria";
            status: string;
            papel: components["schemas"]["Papel"];
            /** Format: date-time */
            criado_em: string;
        };
        Membro: {
            /** Format: uuid */
            usuario_id: string;
            nome: string;
            /** Format: email */
            email: string;
            papel: components["schemas"]["Papel"];
            /** Format: date-time */
            entrou_em: string;
        };
        Convite: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string | null;
            /** Format: date-time */
            expira_em: string;
            /** Format: date-time */
            criado_em: string;
        };
        ConviteCriado: components["schemas"]["Convite"] & {
            /** @description Só aparece na criação */
            token: string;
            /**
             * Format: uri
             * @description Link para enviar ao afiliado ({APP_URL}/convite/{token})
             */
            url: string;
        };
        ConvitePublico: {
            workspace_nome: string;
            workspace_foto_url: string | null;
            /** @enum {string} */
            status: "valido" | "expirado" | "usado" | "revogado";
            /** Format: date-time */
            expira_em: string;
        };
        ConexaoShopee: {
            /**
             * @description `invalido`: a Shopee recusou a assinatura (Secret trocado). `expirado`: a Shopee negou acesso à conta (bloqueada, sem permissão).
             * @enum {string}
             */
            status: "desconectado" | "conectado" | "invalido" | "expirado";
            /** @description AppID mascarado, ex.: ••••5678 */
            app_id: string | null;
            /** Format: date-time */
            verificado_em: string | null;
        };
        Categoria: {
            /** Format: int64 */
            id: number;
            nome: string;
            produtos: number;
        };
        RadarItem: {
            /** Format: uuid */
            produto_id: string;
            nome: string;
            imagem_url: string | null;
            loja_nome: string;
            /** @description Página do produto na Shopee (sem link de afiliado) */
            url: string;
            categorias: number[];
            /** Format: int64 */
            preco_min_centavos: number;
            /** Format: int64 */
            preco_max_centavos: number;
            /** @description Comissão em basis points (1% = 100) */
            comissao_bp: number;
            /**
             * Format: int64
             * @description preço mínimo × comissão
             */
            ganho_por_venda_centavos: number;
            /**
             * Format: int64
             * @description Vendas acumuladas informadas pela Shopee
             */
            vendas: number;
            nota: number | null;
            /** @description Score de tendência de 0 a 100, relativo ao catálogo */
            score: number;
            /**
             * Format: int64
             * @description Crescimento de vendas estimado para 7 dias. Nulo quando ainda não há um dia de histórico.
             */
            vendas_7d: number | null;
            /**
             * Format: date-time
             * @description Coleta mais recente do produto
             */
            atualizado_em: string;
        };
        RadarPagina: {
            itens: components["schemas"]["RadarItem"][];
            total: number;
            pagina: number;
            por_pagina: number;
            /**
             * Format: date-time
             * @description Coleta mais recente do catálogo, para o "atualizado há X"
             */
            atualizado_em: string | null;
        };
        Snapshot: {
            /** Format: date-time */
            coletado_em: string;
            /** Format: int64 */
            preco_min_centavos: number;
            /** Format: int64 */
            preco_max_centavos: number;
            comissao_bp: number;
            /** Format: int64 */
            vendas: number;
            nota: number | null;
        };
        RadarDetalhe: {
            produto: components["schemas"]["RadarItem"];
            historico: components["schemas"]["Snapshot"][];
        };
        /** @enum {string} */
        StatusItem: "testando" | "campeao" | "descartado";
        /** @enum {string} */
        Canal: "instagram" | "tiktok" | "whatsapp" | "outro";
        ProdutoResumo: {
            /** Format: uuid */
            id: string;
            nome: string;
            imagem_url: string | null;
            loja_nome: string;
            /** @description Página do produto na Shopee (sem link de afiliado) */
            url: string;
            /** Format: int64 */
            preco_min_centavos: number;
            /** Format: int64 */
            preco_max_centavos: number;
            comissao_bp: number;
            /** Format: int64 */
            ganho_por_venda_centavos: number;
            /** Format: int64 */
            vendas: number;
            nota: number | null;
            /** Format: date-time */
            atualizado_em: string;
        };
        LinkCanal: {
            canal: components["schemas"]["Canal"];
            /** @description subIds enviados à Shopee, separados por vírgula */
            sub_id: string;
            url: string;
        };
        Item: {
            /** Format: uuid */
            id: string;
            produto: components["schemas"]["ProdutoResumo"];
            /** @description Título próprio; vazio usa o nome do produto */
            titulo: string;
            descricao: string;
            /** @description Notas pessoais; só o próprio usuário vê */
            notas: string;
            tags: string[];
            status: components["schemas"]["StatusItem"];
            /** @description Link principal (o manual, ou o automático do canal `outro`) */
            link_afiliado: string | null;
            /** @enum {string} */
            link_origem: "auto" | "manual";
            /**
             * @description `pendente`: sem credencial da Shopee conectada. `gerando`: o job `gerar_link` vai rodar. `falhou`: a Shopee não gerou o link depois das tentativas.
             * @enum {string}
             */
            link_status: "pendente" | "gerando" | "pronto" | "falhou";
            /** @description Links automáticos por canal (subId) */
            links: components["schemas"]["LinkCanal"][];
            colecao_ids: string[];
            /** Format: date-time */
            criado_em: string;
            /** Format: date-time */
            atualizado_em: string;
        };
        ItensPagina: {
            itens: components["schemas"]["Item"][];
            total: number;
            pagina: number;
            por_pagina: number;
        };
        Colecao: {
            /** Format: uuid */
            id: string;
            nome: string;
            /** @description Quantidade de itens */
            itens: number;
            /** Format: date-time */
            criado_em: string;
        };
        Prontidao: {
            [key: string]: "ok" | "falhou";
        };
    };
    responses: {
        /** @description Sem token ou token inválido (`nao_autenticado`) */
        NaoAutenticado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Erro"];
            };
        };
        /** @description Erro com código e mensagem para o usuário */
        Erro: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Erro"];
            };
        };
    };
    parameters: {
        WorkspaceId: string;
        ItemId: string;
        TokenConvite: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Processo ativo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status?: "ok";
                    };
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Todas as dependências respondem */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Prontidao"];
                };
            };
            /** @description Alguma dependência falhou */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Prontidao"];
                };
            };
        };
    };
    eu: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usuário */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Usuario"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
        };
    };
    listarWorkspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspaces, o pessoal primeiro */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"][];
                };
            };
            401: components["responses"]["NaoAutenticado"];
        };
    };
    criarMentoria: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    nome: string;
                    /**
                     * Format: uri
                     * @description URL https
                     */
                    foto_url?: string | null;
                };
            };
        };
        responses: {
            /** @description Mentoria criada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            422: components["responses"]["Erro"];
        };
    };
    verWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            404: components["responses"]["Erro"];
        };
    };
    atualizarWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    nome?: string;
                    /** @description URL https. String vazia remove a foto. */
                    foto_url?: string;
                };
            };
        };
        responses: {
            /** @description Workspace atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["Erro"];
            404: components["responses"]["Erro"];
            422: components["responses"]["Erro"];
        };
    };
    listarMembros: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Membros */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Membro"][];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["Erro"];
            404: components["responses"]["Erro"];
        };
    };
    removerMembro: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                usuarioId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removido */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["Erro"];
            404: components["responses"]["Erro"];
            409: components["responses"]["Erro"];
        };
    };
    listarConvites: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Convites ainda válidos, sem o token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Convite"][];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["Erro"];
            404: components["responses"]["Erro"];
        };
    };
    criarConvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email?: string | null;
                    /** @default 168 */
                    validade_horas?: number;
                };
            };
        };
        responses: {
            /** @description Convite criado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConviteCriado"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["Erro"];
            404: components["responses"]["Erro"];
            /** @description `so_mentoria` ou `sem_assentos` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            422: components["responses"]["Erro"];
        };
    };
    revogarConvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                conviteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["Erro"];
            404: components["responses"]["Erro"];
        };
    };
    verConvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["TokenConvite"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Convite */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConvitePublico"];
                };
            };
            404: components["responses"]["Erro"];
        };
    };
    aceitarConvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["TokenConvite"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace em que o usuário entrou */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            /** @description `convite_outro_email` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            404: components["responses"]["Erro"];
            /** @description `ja_membro` ou `sem_assentos` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            /** @description `convite_expirado`, `convite_usado` ou `convite_revogado` */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    verConexaoShopee: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Situação */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConexaoShopee"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
        };
    };
    conectarShopee: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    app_id: string;
                    secret: string;
                };
            };
        };
        responses: {
            /** @description Conectado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConexaoShopee"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            /** @description `dados_invalidos` ou `credencial_invalida` (a Shopee recusou o AppID ou o Secret) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            /** @description `shopee_limite` (a Shopee limitou as chamadas; tente de novo em instantes) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            /** @description `shopee_indisponivel` */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    desconectarShopee: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Desconectado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["NaoAutenticado"];
        };
    };
    radar: {
        parameters: {
            query?: {
                categoria?: number;
                /** @description Centavos */
                preco_min?: number;
                /** @description Centavos */
                preco_max?: number;
                /** @description Basis points */
                comissao_min?: number;
                nota_min?: number;
                /** @description Busca no nome do produto e da loja */
                q?: string;
                ordem?: "tendencia" | "comissao" | "ganho" | "vendas";
                pagina?: number;
                por_pagina?: number;
            };
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página do radar */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RadarPagina"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            404: components["responses"]["Erro"];
            422: components["responses"]["Erro"];
        };
    };
    radarCategorias: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categorias, as com mais produtos primeiro */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Categoria"][];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            404: components["responses"]["Erro"];
        };
    };
    radarProduto: {
        parameters: {
            query?: {
                /** @description Janela do histórico */
                dias?: number;
            };
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                produtoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Produto e snapshots da janela, do mais antigo ao mais novo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RadarDetalhe"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            404: components["responses"]["Erro"];
        };
    };
    listarItens: {
        parameters: {
            query?: {
                /** @description Busca no título próprio e no nome do produto */
                q?: string;
                status?: components["schemas"]["StatusItem"];
                /** @description Só os itens desta coleção */
                colecao?: string;
                tag?: string;
                pagina?: number;
                por_pagina?: number;
            };
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de itens */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItensPagina"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            404: components["responses"]["Erro"];
            422: components["responses"]["Erro"];
        };
    };
    salvarItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    produto_id?: string;
                    /** @description Link do produto na Shopee, ex.: https://shopee.com.br/Nome-i.123.456 */
                    url?: string;
                };
            };
        };
        responses: {
            /** @description O produto já estava salvo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            /** @description Salvo */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            /** @description `produto_nao_encontrado` (nem no catálogo nem na Shopee) ou `workspace_nao_encontrado` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            /** @description `dados_invalidos`, `link_invalido` ou `link_curto` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            /** @description `shopee_limite` */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            /** @description `shopee_indisponivel` */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            /** @description `importacao_indisponivel` (o servidor não tem a credencial do app para buscar produtos fora do catálogo) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    produtosSalvos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description produto_id de cada item salvo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            404: components["responses"]["Erro"];
        };
    };
    gerarLinksPendentes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Itens enfileirados */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        enfileirados: number;
                    };
                };
            };
            401: components["responses"]["NaoAutenticado"];
            404: components["responses"]["Erro"];
            /** @description `sem_credencial` (conecte a conta da Shopee antes) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    verItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            404: components["responses"]["Erro"];
        };
    };
    removerItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removido */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["NaoAutenticado"];
            404: components["responses"]["Erro"];
        };
    };
    atualizarItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    titulo?: string;
                    descricao?: string;
                    notas?: string;
                    tags?: string[];
                    status?: components["schemas"]["StatusItem"];
                    /** @description URL https */
                    link_afiliado?: string | null;
                };
            };
        };
        responses: {
            /** @description Item atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            404: components["responses"]["Erro"];
            422: components["responses"]["Erro"];
        };
    };
    gerarLinkItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Item com `link_status` = `gerando`, ou `pendente` sem credencial */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            404: components["responses"]["Erro"];
        };
    };
    definirColecoesItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                itemId: components["parameters"]["ItemId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    colecao_ids: string[];
                };
            };
        };
        responses: {
            /** @description Item atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Item"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            /** @description `item_nao_encontrado` ou `colecao_nao_encontrada` */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    listarColecoes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Coleções em ordem alfabética */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Colecao"][];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            404: components["responses"]["Erro"];
        };
    };
    criarColecao: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    nome: string;
                };
            };
        };
        responses: {
            /** @description Criada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Colecao"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            404: components["responses"]["Erro"];
            /** @description `colecao_existente` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            422: components["responses"]["Erro"];
        };
    };
    apagarColecao: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                colecaoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Apagada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["NaoAutenticado"];
            404: components["responses"]["Erro"];
        };
    };
    renomearColecao: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                colecaoId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    nome: string;
                };
            };
        };
        responses: {
            /** @description Renomeada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Colecao"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            404: components["responses"]["Erro"];
            /** @description `colecao_existente` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            422: components["responses"]["Erro"];
        };
    };
}
