/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verificação de vida do processo */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Verificação de prontidão (Postgres e Redis) */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/eu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Usuário autenticado
         * @description No primeiro acesso, cria o usuário a partir do perfil do Zitadel e o seu workspace pessoal.
         */
        get: operations["eu"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspaces de que o usuário participa (seletor do topo) */
        get: operations["listarWorkspaces"];
        put?: never;
        /**
         * Criar mentoria
         * @description Cria um workspace do tipo mentoria com o usuário como dono.
         */
        post: operations["criarMentoria"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        /** Detalhe do workspace */
        get: operations["verWorkspace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Alterar nome e foto (só o dono) */
        patch: operations["atualizarWorkspace"];
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/membros": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        /** Membros do workspace (dono e mentor) */
        get: operations["listarMembros"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/membros/{usuarioId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                usuarioId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Sair do workspace ou remover um membro
         * @description Com o próprio id, o usuário sai do workspace. Dono e mentor removem afiliados; só o dono remove mentores; o dono não sai nem é removido. Os dados pessoais do afiliado (coleção, credencial) continuam dele.
         */
        delete: operations["removerMembro"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/convites": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        /** Convites pendentes (dono e mentor) */
        get: operations["listarConvites"];
        put?: never;
        /**
         * Convidar afiliado
         * @description Gera um convite de uso único para um workspace de mentoria. Com e-mail, só a conta com aquele e-mail verificado pode aceitar. Convites pendentes ocupam assento do plano. O token só aparece nesta resposta.
         */
        post: operations["criarConvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/convites/{conviteId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                conviteId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancelar convite pendente */
        delete: operations["revogarConvite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/convites/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["TokenConvite"];
            };
            cookie?: never;
        };
        /**
         * Ver convite (público)
         * @description Mostra o workspace e a situação do convite antes do login.
         */
        get: operations["verConvite"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/convites/{token}/aceitar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["TokenConvite"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aceitar convite
         * @description Torna o usuário afiliado do workspace do convite.
         */
        post: operations["aceitarConvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/eu/shopee": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Situação da conexão com a Shopee
         * @description A credencial (AppID e Secret da Open API de afiliados) pertence ao usuário, não ao workspace. O Secret nunca aparece em resposta.
         */
        get: operations["verConexaoShopee"];
        /**
         * Conectar a conta de afiliado
         * @description Valida o AppID e o Secret com uma chamada de teste à Shopee e guarda a credencial cifrada (envelope encryption). Substitui a credencial anterior, se houver.
         */
        put: operations["conectarShopee"];
        post?: never;
        /** Desconectar (apaga a credencial) */
        delete: operations["desconectarShopee"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/radar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        /**
         * Radar de produtos em alta
         * @description Lista ranqueada do catálogo coletado pelo job `snapshot_catalogo` (credencial do app) com o score do job `calcular_tendencias`. Valores em centavos e comissão em basis points (1% = 100).
         */
        get: operations["radar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/radar/categorias": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        /** Categorias presentes no radar (para o filtro) */
        get: operations["radarCategorias"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/workspaces/{workspaceId}/radar/produtos/{produtoId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                produtoId: string;
            };
            cookie?: never;
        };
        /** Detalhe do produto com histórico */
        get: operations["radarProduto"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Erro: {
            /** @description Código estável para o front. Em contas: nao_autenticado, dados_invalidos, json_invalido, sem_permissao, workspace_nao_encontrado, membro_nao_encontrado, convite_nao_encontrado, so_mentoria, dono_nao_sai, sem_assentos, ja_membro, convite_expirado, convite_usado, convite_revogado, convite_outro_email, erro_interno. Em shopee: credencial_invalida, shopee_limite, shopee_indisponivel. Em radar: produto_nao_encontrado. */
            codigo: string;
            /** @description Texto pronto para mostrar ao usuário */
            mensagem: string;
        };
        Usuario: {
            /** Format: uuid */
            id: string;
            nome: string;
            /** Format: email */
            email: string;
            /** Format: date-time */
            criado_em: string;
        };
        /** @enum {string} */
        Papel: "dono" | "mentor" | "afiliado";
        Workspace: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            tipo: "pessoal" | "mentoria";
            nome: string;
            foto_url: string | null;
            /** @enum {string} */
            plano: "avulso" | "mentoria";
            status: string;
            papel: components["schemas"]["Papel"];
            /** Format: date-time */
            criado_em: string;
        };
        Membro: {
            /** Format: uuid */
            usuario_id: string;
            nome: string;
            /** Format: email */
            email: string;
            papel: components["schemas"]["Papel"];
            /** Format: date-time */
            entrou_em: string;
        };
        Convite: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string | null;
            /** Format: date-time */
            expira_em: string;
            /** Format: date-time */
            criado_em: string;
        };
        ConviteCriado: components["schemas"]["Convite"] & {
            /** @description Só aparece na criação */
            token: string;
            /**
             * Format: uri
             * @description Link para enviar ao afiliado ({APP_URL}/convite/{token})
             */
            url: string;
        };
        ConvitePublico: {
            workspace_nome: string;
            workspace_foto_url: string | null;
            /** @enum {string} */
            status: "valido" | "expirado" | "usado" | "revogado";
            /** Format: date-time */
            expira_em: string;
        };
        ConexaoShopee: {
            /**
             * @description `invalido`: a Shopee recusou a assinatura (Secret trocado). `expirado`: a Shopee negou acesso à conta (bloqueada, sem permissão).
             * @enum {string}
             */
            status: "desconectado" | "conectado" | "invalido" | "expirado";
            /** @description AppID mascarado, ex.: ••••5678 */
            app_id: string | null;
            /** Format: date-time */
            verificado_em: string | null;
        };
        Categoria: {
            /** Format: int64 */
            id: number;
            nome: string;
            produtos: number;
        };
        RadarItem: {
            /** Format: uuid */
            produto_id: string;
            nome: string;
            imagem_url: string | null;
            loja_nome: string;
            /** @description Página do produto na Shopee (sem link de afiliado) */
            url: string;
            categorias: number[];
            /** Format: int64 */
            preco_min_centavos: number;
            /** Format: int64 */
            preco_max_centavos: number;
            /** @description Comissão em basis points (1% = 100) */
            comissao_bp: number;
            /**
             * Format: int64
             * @description preço mínimo × comissão
             */
            ganho_por_venda_centavos: number;
            /**
             * Format: int64
             * @description Vendas acumuladas informadas pela Shopee
             */
            vendas: number;
            nota: number | null;
            /** @description Score de tendência de 0 a 100, relativo ao catálogo */
            score: number;
            /**
             * Format: int64
             * @description Crescimento de vendas estimado para 7 dias. Nulo quando ainda não há um dia de histórico.
             */
            vendas_7d: number | null;
            /**
             * Format: date-time
             * @description Coleta mais recente do produto
             */
            atualizado_em: string;
        };
        RadarPagina: {
            itens: components["schemas"]["RadarItem"][];
            total: number;
            pagina: number;
            por_pagina: number;
            /**
             * Format: date-time
             * @description Coleta mais recente do catálogo, para o "atualizado há X"
             */
            atualizado_em: string | null;
        };
        Snapshot: {
            /** Format: date-time */
            coletado_em: string;
            /** Format: int64 */
            preco_min_centavos: number;
            /** Format: int64 */
            preco_max_centavos: number;
            comissao_bp: number;
            /** Format: int64 */
            vendas: number;
            nota: number | null;
        };
        RadarDetalhe: {
            produto: components["schemas"]["RadarItem"];
            historico: components["schemas"]["Snapshot"][];
        };
        Prontidao: {
            [key: string]: "ok" | "falhou";
        };
    };
    responses: {
        /** @description Sem token ou token inválido (`nao_autenticado`) */
        NaoAutenticado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Erro"];
            };
        };
        /** @description Erro com código e mensagem para o usuário */
        Erro: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Erro"];
            };
        };
    };
    parameters: {
        WorkspaceId: string;
        TokenConvite: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Processo ativo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status?: "ok";
                    };
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Todas as dependências respondem */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Prontidao"];
                };
            };
            /** @description Alguma dependência falhou */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Prontidao"];
                };
            };
        };
    };
    eu: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usuário */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Usuario"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
        };
    };
    listarWorkspaces: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspaces, o pessoal primeiro */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"][];
                };
            };
            401: components["responses"]["NaoAutenticado"];
        };
    };
    criarMentoria: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    nome: string;
                    /**
                     * Format: uri
                     * @description URL https
                     */
                    foto_url?: string | null;
                };
            };
        };
        responses: {
            /** @description Mentoria criada */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            422: components["responses"]["Erro"];
        };
    };
    verWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            404: components["responses"]["Erro"];
        };
    };
    atualizarWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    nome?: string;
                    /** @description URL https. String vazia remove a foto. */
                    foto_url?: string;
                };
            };
        };
        responses: {
            /** @description Workspace atualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["Erro"];
            404: components["responses"]["Erro"];
            422: components["responses"]["Erro"];
        };
    };
    listarMembros: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Membros */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Membro"][];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["Erro"];
            404: components["responses"]["Erro"];
        };
    };
    removerMembro: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                usuarioId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removido */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["Erro"];
            404: components["responses"]["Erro"];
            409: components["responses"]["Erro"];
        };
    };
    listarConvites: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Convites ainda válidos, sem o token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Convite"][];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["Erro"];
            404: components["responses"]["Erro"];
        };
    };
    criarConvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email?: string | null;
                    /** @default 168 */
                    validade_horas?: number;
                };
            };
        };
        responses: {
            /** @description Convite criado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConviteCriado"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["Erro"];
            404: components["responses"]["Erro"];
            /** @description `so_mentoria` ou `sem_assentos` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            422: components["responses"]["Erro"];
        };
    };
    revogarConvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                conviteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancelado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["NaoAutenticado"];
            403: components["responses"]["Erro"];
            404: components["responses"]["Erro"];
        };
    };
    verConvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["TokenConvite"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Convite */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConvitePublico"];
                };
            };
            404: components["responses"]["Erro"];
        };
    };
    aceitarConvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: components["parameters"]["TokenConvite"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Workspace em que o usuário entrou */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Workspace"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            /** @description `convite_outro_email` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            404: components["responses"]["Erro"];
            /** @description `ja_membro` ou `sem_assentos` */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            /** @description `convite_expirado`, `convite_usado` ou `convite_revogado` */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    verConexaoShopee: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Situação */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConexaoShopee"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
        };
    };
    conectarShopee: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    app_id: string;
                    secret: string;
                };
            };
        };
        responses: {
            /** @description Conectado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConexaoShopee"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            /** @description `dados_invalidos` ou `credencial_invalida` (a Shopee recusou o AppID ou o Secret) */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            /** @description `shopee_limite` (a Shopee limitou as chamadas; tente de novo em instantes) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
            /** @description `shopee_indisponivel` */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Erro"];
                };
            };
        };
    };
    desconectarShopee: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Desconectado */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["NaoAutenticado"];
        };
    };
    radar: {
        parameters: {
            query?: {
                categoria?: number;
                /** @description Centavos */
                preco_min?: number;
                /** @description Centavos */
                preco_max?: number;
                /** @description Basis points */
                comissao_min?: number;
                nota_min?: number;
                /** @description Busca no nome do produto e da loja */
                q?: string;
                ordem?: "tendencia" | "comissao" | "ganho" | "vendas";
                pagina?: number;
                por_pagina?: number;
            };
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página do radar */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RadarPagina"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            404: components["responses"]["Erro"];
            422: components["responses"]["Erro"];
        };
    };
    radarCategorias: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categorias, as com mais produtos primeiro */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Categoria"][];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            404: components["responses"]["Erro"];
        };
    };
    radarProduto: {
        parameters: {
            query?: {
                /** @description Janela do histórico */
                dias?: number;
            };
            header?: never;
            path: {
                workspaceId: components["parameters"]["WorkspaceId"];
                produtoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Produto e snapshots da janela, do mais antigo ao mais novo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RadarDetalhe"];
                };
            };
            401: components["responses"]["NaoAutenticado"];
            404: components["responses"]["Erro"];
        };
    };
}
