// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countAffiliates = `-- name: CountAffiliates :one
SELECT count(*) FROM members WHERE workspace_id = $1 AND role = 'affiliate'
`

func (q *Queries) CountAffiliates(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAffiliates, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingInvites = `-- name: CountPendingInvites :one
SELECT count(*) FROM invites
WHERE workspace_id = $1
  AND used_by IS NULL
  AND revoked_at IS NULL
  AND expires_at > now()
`

func (q *Queries) CountPendingInvites(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingInvites, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (workspace_id, email, token_hash, expires_at, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, email, token_hash, expires_at, used_by, used_at, revoked_at, created_by, created_at
`

type CreateInviteParams struct {
	WorkspaceID uuid.UUID
	Email       *string
	TokenHash   []byte
	ExpiresAt   time.Time
	CreatedBy   uuid.UUID
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.WorkspaceID,
		arg.Email,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedBy,
		&i.UsedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (kind, name, photo_url, owner_id, plan)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, kind, name, photo_url, owner_id, plan, access_until, paid_at, seats, created_at
`

type CreateWorkspaceParams struct {
	Kind     WorkspaceKind
	Name     string
	PhotoURL *string
	OwnerID  uuid.UUID
	Plan     string
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.Kind,
		arg.Name,
		arg.PhotoURL,
		arg.OwnerID,
		arg.Plan,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.PhotoURL,
		&i.OwnerID,
		&i.Plan,
		&i.AccessUntil,
		&i.PaidAt,
		&i.Seats,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMember = `-- name: DeleteMember :execrows
DELETE FROM members WHERE workspace_id = $1 AND user_id = $2
`

type DeleteMemberParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) DeleteMember(ctx context.Context, arg DeleteMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMember, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const grantAccess = `-- name: GrantAccess :one
UPDATE workspaces
SET access_until = greatest(access_until, $1::timestamptz),
    paid_at = now(),
    seats = coalesce($2, seats)
WHERE id = $3
RETURNING id, kind, name, photo_url, owner_id, plan, access_until, paid_at, seats, created_at
`

type GrantAccessParams struct {
	Until time.Time
	Seats *int32
	ID    uuid.UUID
}

// Extends the access until `until` (never shortens it) and records the
// payment. Null seats keep the ones bought.
func (q *Queries) GrantAccess(ctx context.Context, arg GrantAccessParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, grantAccess, arg.Until, arg.Seats, arg.ID)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.PhotoURL,
		&i.OwnerID,
		&i.Plan,
		&i.AccessUntil,
		&i.PaidAt,
		&i.Seats,
		&i.CreatedAt,
	)
	return i, err
}

const insertMember = `-- name: InsertMember :exec
INSERT INTO members (workspace_id, user_id, role)
VALUES ($1, $2, $3)
`

type InsertMemberParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Role        MemberRole
}

func (q *Queries) InsertMember(ctx context.Context, arg InsertMemberParams) error {
	_, err := q.db.Exec(ctx, insertMember, arg.WorkspaceID, arg.UserID, arg.Role)
	return err
}

const inviteByHash = `-- name: InviteByHash :one
SELECT id, workspace_id, email, token_hash, expires_at, used_by, used_at, revoked_at, created_by, created_at FROM invites WHERE token_hash = $1
`

func (q *Queries) InviteByHash(ctx context.Context, tokenHash []byte) (Invite, error) {
	row := q.db.QueryRow(ctx, inviteByHash, tokenHash)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedBy,
		&i.UsedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const isStudentOfActiveMentorship = `-- name: IsStudentOfActiveMentorship :one
SELECT EXISTS (
    SELECT 1
    FROM members m
    JOIN workspaces w ON w.id = m.workspace_id
    WHERE m.user_id = $1
      AND m.role = 'affiliate'
      AND w.kind = 'mentorship'
      AND w.access_until > now()
)::boolean AS student
`

// Whether the user is an affiliate of a mentorship with access up to date.
// While they are, their personal workspace is not charged.
func (q *Queries) IsStudentOfActiveMentorship(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isStudentOfActiveMentorship, userID)
	var student bool
	err := row.Scan(&student)
	return student, err
}

const lockInviteByHash = `-- name: LockInviteByHash :one
SELECT id, workspace_id, email, token_hash, expires_at, used_by, used_at, revoked_at, created_by, created_at FROM invites WHERE token_hash = $1 FOR UPDATE
`

func (q *Queries) LockInviteByHash(ctx context.Context, tokenHash []byte) (Invite, error) {
	row := q.db.QueryRow(ctx, lockInviteByHash, tokenHash)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedBy,
		&i.UsedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const lockWorkspace = `-- name: LockWorkspace :one
SELECT id, kind, name, photo_url, owner_id, plan, access_until, paid_at, seats, created_at FROM workspaces WHERE id = $1 FOR UPDATE
`

// Locks the workspace row to serialize the seat count.
func (q *Queries) LockWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, lockWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.PhotoURL,
		&i.OwnerID,
		&i.Plan,
		&i.AccessUntil,
		&i.PaidAt,
		&i.Seats,
		&i.CreatedAt,
	)
	return i, err
}

const markInviteUsed = `-- name: MarkInviteUsed :exec
UPDATE invites SET used_by = $2, used_at = now() WHERE id = $1
`

type MarkInviteUsedParams struct {
	ID     uuid.UUID
	UsedBy *uuid.UUID
}

func (q *Queries) MarkInviteUsed(ctx context.Context, arg MarkInviteUsedParams) error {
	_, err := q.db.Exec(ctx, markInviteUsed, arg.ID, arg.UsedBy)
	return err
}

const memberByUser = `-- name: MemberByUser :one
SELECT workspace_id, user_id, role, shares_results, joined_at FROM members WHERE workspace_id = $1 AND user_id = $2
`

type MemberByUserParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) MemberByUser(ctx context.Context, arg MemberByUserParams) (Member, error) {
	row := q.db.QueryRow(ctx, memberByUser, arg.WorkspaceID, arg.UserID)
	var i Member
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.SharesResults,
		&i.JoinedAt,
	)
	return i, err
}

const pendingInvites = `-- name: PendingInvites :many
SELECT id, workspace_id, email, token_hash, expires_at, used_by, used_at, revoked_at, created_by, created_at FROM invites
WHERE workspace_id = $1
  AND used_by IS NULL
  AND revoked_at IS NULL
  AND expires_at > now()
ORDER BY created_at DESC
`

func (q *Queries) PendingInvites(ctx context.Context, workspaceID uuid.UUID) ([]Invite, error) {
	rows, err := q.db.Query(ctx, pendingInvites, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invite
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Email,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.UsedBy,
			&i.UsedAt,
			&i.RevokedAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const planLimit = `-- name: PlanLimit :one
SELECT value FROM plan_limits WHERE plan = $1 AND key = $2
`

type PlanLimitParams struct {
	Plan string
	Key  string
}

func (q *Queries) PlanLimit(ctx context.Context, arg PlanLimitParams) (int64, error) {
	row := q.db.QueryRow(ctx, planLimit, arg.Plan, arg.Key)
	var value int64
	err := row.Scan(&value)
	return value, err
}

const revokeAccess = `-- name: RevokeAccess :execrows
UPDATE workspaces SET access_until = least(access_until, now()) WHERE id = $1
`

func (q *Queries) RevokeAccess(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAccess, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeInvite = `-- name: RevokeInvite :execrows
UPDATE invites SET revoked_at = now()
WHERE id = $1
  AND workspace_id = $2
  AND used_by IS NULL
  AND revoked_at IS NULL
`

type RevokeInviteParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) RevokeInvite(ctx context.Context, arg RevokeInviteParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeInvite, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSeats = `-- name: SetSeats :exec
UPDATE workspaces SET seats = $2 WHERE id = $1
`

type SetSeatsParams struct {
	ID    uuid.UUID
	Seats *int32
}

func (q *Queries) SetSeats(ctx context.Context, arg SetSeatsParams) error {
	_, err := q.db.Exec(ctx, setSeats, arg.ID, arg.Seats)
	return err
}

const setSharesResults = `-- name: SetSharesResults :execrows
UPDATE members SET shares_results = $1
WHERE workspace_id = $2 AND user_id = $3
`

type SetSharesResultsParams struct {
	SharesResults bool
	WorkspaceID   uuid.UUID
	UserID        uuid.UUID
}

func (q *Queries) SetSharesResults(ctx context.Context, arg SetSharesResultsParams) (int64, error) {
	result, err := q.db.Exec(ctx, setSharesResults, arg.SharesResults, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces
SET name = coalesce($1, name),
    photo_url = CASE WHEN $2::boolean THEN NULL
                     ELSE coalesce($3, photo_url) END
WHERE id = $4
RETURNING id, kind, name, photo_url, owner_id, plan, access_until, paid_at, seats, created_at
`

type UpdateWorkspaceParams struct {
	Name       *string
	ClearPhoto bool
	PhotoURL   *string
	ID         uuid.UUID
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspace,
		arg.Name,
		arg.ClearPhoto,
		arg.PhotoURL,
		arg.ID,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.PhotoURL,
		&i.OwnerID,
		&i.Plan,
		&i.AccessUntil,
		&i.PaidAt,
		&i.Seats,
		&i.CreatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (auth_provider, auth_subject, name, email, email_verified)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (auth_provider, auth_subject) DO UPDATE
    SET name = EXCLUDED.name,
        email = EXCLUDED.email,
        email_verified = EXCLUDED.email_verified
RETURNING id, (xmax = 0)::boolean AS created
`

type UpsertUserParams struct {
	AuthProvider  string
	AuthSubject   string
	Name          string
	Email         string
	EmailVerified bool
}

type UpsertUserRow struct {
	ID      uuid.UUID
	Created bool
}

// Creates the user on first access or updates name and email. `created` says
// whether the row was just inserted.
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (UpsertUserRow, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.AuthProvider,
		arg.AuthSubject,
		arg.Name,
		arg.Email,
		arg.EmailVerified,
	)
	var i UpsertUserRow
	err := row.Scan(&i.ID, &i.Created)
	return i, err
}

const userByID = `-- name: UserByID :one
SELECT id, auth_provider, auth_subject, name, email, email_verified, created_at FROM users WHERE id = $1
`

func (q *Queries) UserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, userByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthProvider,
		&i.AuthSubject,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const userByIdentity = `-- name: UserByIdentity :one

SELECT id, auth_provider, auth_subject, name, email, email_verified, created_at FROM users WHERE auth_provider = $1 AND auth_subject = $2
`

type UserByIdentityParams struct {
	AuthProvider string
	AuthSubject  string
}

// Accounts: users, workspaces, members, invites and plan limits.
func (q *Queries) UserByIdentity(ctx context.Context, arg UserByIdentityParams) (User, error) {
	row := q.db.QueryRow(ctx, userByIdentity, arg.AuthProvider, arg.AuthSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.AuthProvider,
		&i.AuthSubject,
		&i.Name,
		&i.Email,
		&i.EmailVerified,
		&i.CreatedAt,
	)
	return i, err
}

const userWorkspaces = `-- name: UserWorkspaces :many
SELECT w.id, w.kind, w.name, w.photo_url, w.owner_id, w.plan, w.access_until, w.paid_at, w.seats, w.created_at, m.role
FROM members m
JOIN workspaces w ON w.id = m.workspace_id
WHERE m.user_id = $1
ORDER BY w.kind, w.created_at
`

type UserWorkspacesRow struct {
	ID          uuid.UUID
	Kind        WorkspaceKind
	Name        string
	PhotoURL    *string
	OwnerID     uuid.UUID
	Plan        string
	AccessUntil time.Time
	PaidAt      *time.Time
	Seats       *int32
	CreatedAt   time.Time
	Role        MemberRole
}

func (q *Queries) UserWorkspaces(ctx context.Context, userID uuid.UUID) ([]UserWorkspacesRow, error) {
	rows, err := q.db.Query(ctx, userWorkspaces, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserWorkspacesRow
	for rows.Next() {
		var i UserWorkspacesRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Name,
			&i.PhotoURL,
			&i.OwnerID,
			&i.Plan,
			&i.AccessUntil,
			&i.PaidAt,
			&i.Seats,
			&i.CreatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workspaceByID = `-- name: WorkspaceByID :one
SELECT id, kind, name, photo_url, owner_id, plan, access_until, paid_at, seats, created_at FROM workspaces WHERE id = $1
`

func (q *Queries) WorkspaceByID(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, workspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Name,
		&i.PhotoURL,
		&i.OwnerID,
		&i.Plan,
		&i.AccessUntil,
		&i.PaidAt,
		&i.Seats,
		&i.CreatedAt,
	)
	return i, err
}

const workspaceMembers = `-- name: WorkspaceMembers :many
SELECT m.user_id, u.name, u.email, m.role, m.joined_at, m.shares_results
FROM members m
JOIN users u ON u.id = m.user_id
WHERE m.workspace_id = $1
ORDER BY m.role, m.joined_at
`

type WorkspaceMembersRow struct {
	UserID        uuid.UUID
	Name          string
	Email         string
	Role          MemberRole
	JoinedAt      time.Time
	SharesResults bool
}

func (q *Queries) WorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, workspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspaceMembersRow
	for rows.Next() {
		var i WorkspaceMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.JoinedAt,
			&i.SharesResults,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
