// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const authAccountByEmail = `-- name: AuthAccountByEmail :one
SELECT id, email, name, password_hash, email_verified_at, created_at, updated_at FROM auth_accounts WHERE email = $1
`

func (q *Queries) AuthAccountByEmail(ctx context.Context, email string) (AuthAccount, error) {
	row := q.db.QueryRow(ctx, authAccountByEmail, email)
	var i AuthAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const authSessionByHash = `-- name: AuthSessionByHash :one
SELECT s.token_hash, s.account_id, s.created_at, s.last_seen_at, s.expires_at, a.id, a.email, a.name, a.password_hash, a.email_verified_at, a.created_at, a.updated_at
FROM auth_sessions s
JOIN auth_accounts a ON a.id = s.account_id
WHERE s.token_hash = $1
`

type AuthSessionByHashRow struct {
	AuthSession AuthSession
	AuthAccount AuthAccount
}

func (q *Queries) AuthSessionByHash(ctx context.Context, tokenHash []byte) (AuthSessionByHashRow, error) {
	row := q.db.QueryRow(ctx, authSessionByHash, tokenHash)
	var i AuthSessionByHashRow
	err := row.Scan(
		&i.AuthSession.TokenHash,
		&i.AuthSession.AccountID,
		&i.AuthSession.CreatedAt,
		&i.AuthSession.LastSeenAt,
		&i.AuthSession.ExpiresAt,
		&i.AuthAccount.ID,
		&i.AuthAccount.Email,
		&i.AuthAccount.Name,
		&i.AuthAccount.PasswordHash,
		&i.AuthAccount.EmailVerifiedAt,
		&i.AuthAccount.CreatedAt,
		&i.AuthAccount.UpdatedAt,
	)
	return i, err
}

const createAuthAccount = `-- name: CreateAuthAccount :one

INSERT INTO auth_accounts (email, name, password_hash)
VALUES ($1, $2, $3)
RETURNING id, email, name, password_hash, email_verified_at, created_at, updated_at
`

type CreateAuthAccountParams struct {
	Email        string
	Name         string
	PasswordHash string
}

// Queries of the internal identity provider. Generate the code with `make sqlc`.
func (q *Queries) CreateAuthAccount(ctx context.Context, arg CreateAuthAccountParams) (AuthAccount, error) {
	row := q.db.QueryRow(ctx, createAuthAccount, arg.Email, arg.Name, arg.PasswordHash)
	var i AuthAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAuthSession = `-- name: CreateAuthSession :exec
INSERT INTO auth_sessions (token_hash, account_id, created_at, last_seen_at, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateAuthSessionParams struct {
	TokenHash  []byte
	AccountID  uuid.UUID
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
}

func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) error {
	_, err := q.db.Exec(ctx, createAuthSession,
		arg.TokenHash,
		arg.AccountID,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.ExpiresAt,
	)
	return err
}

const createAuthToken = `-- name: CreateAuthToken :exec
INSERT INTO auth_tokens (token_hash, account_id, purpose, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateAuthTokenParams struct {
	TokenHash []byte
	AccountID uuid.UUID
	Purpose   string
	ExpiresAt time.Time
}

func (q *Queries) CreateAuthToken(ctx context.Context, arg CreateAuthTokenParams) error {
	_, err := q.db.Exec(ctx, createAuthToken,
		arg.TokenHash,
		arg.AccountID,
		arg.Purpose,
		arg.ExpiresAt,
	)
	return err
}

const deleteAuthSession = `-- name: DeleteAuthSession :execrows
DELETE FROM auth_sessions WHERE token_hash = $1
`

func (q *Queries) DeleteAuthSession(ctx context.Context, tokenHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAuthSession, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAuthSessionsOfAccount = `-- name: DeleteAuthSessionsOfAccount :exec
DELETE FROM auth_sessions WHERE account_id = $1
`

func (q *Queries) DeleteAuthSessionsOfAccount(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAuthSessionsOfAccount, accountID)
	return err
}

const deleteExpiredAuthSessions = `-- name: DeleteExpiredAuthSessions :exec
DELETE FROM auth_sessions WHERE account_id = $1 AND expires_at <= now()
`

func (q *Queries) DeleteExpiredAuthSessions(ctx context.Context, accountID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteExpiredAuthSessions, accountID)
	return err
}

const extendAuthSession = `-- name: ExtendAuthSession :exec
UPDATE auth_sessions SET last_seen_at = $2, expires_at = $3 WHERE token_hash = $1
`

type ExtendAuthSessionParams struct {
	TokenHash  []byte
	LastSeenAt time.Time
	ExpiresAt  time.Time
}

func (q *Queries) ExtendAuthSession(ctx context.Context, arg ExtendAuthSessionParams) error {
	_, err := q.db.Exec(ctx, extendAuthSession, arg.TokenHash, arg.LastSeenAt, arg.ExpiresAt)
	return err
}

const markAuthEmailVerified = `-- name: MarkAuthEmailVerified :one
UPDATE auth_accounts
SET email_verified_at = coalesce(email_verified_at, $1::timestamptz), updated_at = $1::timestamptz
WHERE id = $2
RETURNING id, email, name, password_hash, email_verified_at, created_at, updated_at
`

type MarkAuthEmailVerifiedParams struct {
	Now time.Time
	ID  uuid.UUID
}

func (q *Queries) MarkAuthEmailVerified(ctx context.Context, arg MarkAuthEmailVerifiedParams) (AuthAccount, error) {
	row := q.db.QueryRow(ctx, markAuthEmailVerified, arg.Now, arg.ID)
	var i AuthAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setAuthPassword = `-- name: SetAuthPassword :one
UPDATE auth_accounts
SET password_hash = $1,
    email_verified_at = coalesce(email_verified_at, $2::timestamptz),
    updated_at = $2::timestamptz
WHERE id = $3
RETURNING id, email, name, password_hash, email_verified_at, created_at, updated_at
`

type SetAuthPasswordParams struct {
	PasswordHash string
	Now          time.Time
	ID           uuid.UUID
}

func (q *Queries) SetAuthPassword(ctx context.Context, arg SetAuthPasswordParams) (AuthAccount, error) {
	row := q.db.QueryRow(ctx, setAuthPassword, arg.PasswordHash, arg.Now, arg.ID)
	var i AuthAccount
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.EmailVerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const useAuthToken = `-- name: UseAuthToken :one
UPDATE auth_tokens SET used_at = $1::timestamptz
WHERE token_hash = $2
  AND purpose = $3
  AND used_at IS NULL
  AND expires_at > $1::timestamptz
RETURNING account_id
`

type UseAuthTokenParams struct {
	Now       time.Time
	TokenHash []byte
	Purpose   string
}

// Consumes a valid token of the purpose and returns its account.
func (q *Queries) UseAuthToken(ctx context.Context, arg UseAuthTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, useAuthToken, arg.Now, arg.TokenHash, arg.Purpose)
	var account_id uuid.UUID
	err := row.Scan(&account_id)
	return account_id, err
}
