// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package dbgen

import (
	"context"
	"errors"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const insertSnapshot = `-- name: InsertSnapshot :batchexec
INSERT INTO product_snapshots (product_id, collected_at, min_price_cents, max_price_cents, commission_bp, sales, rating)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (product_id, collected_at) DO NOTHING
`

type InsertSnapshotBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertSnapshotParams struct {
	ProductID     uuid.UUID
	CollectedAt   time.Time
	MinPriceCents int64
	MaxPriceCents int64
	CommissionBp  int32
	Sales         int64
	Rating        *float64
}

func (q *Queries) InsertSnapshot(ctx context.Context, arg []InsertSnapshotParams) *InsertSnapshotBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ProductID,
			a.CollectedAt,
			a.MinPriceCents,
			a.MaxPriceCents,
			a.CommissionBp,
			a.Sales,
			a.Rating,
		}
		batch.Queue(insertSnapshot, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertSnapshotBatchResults{br, len(arg), false}
}

func (b *InsertSnapshotBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertSnapshotBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertProduct = `-- name: UpsertProduct :batchone
INSERT INTO products (
    source, item_id, shop_id, shop_name, name, image_url, category_id, categories, url,
    min_price_cents, max_price_cents, commission_bp, sales, rating, collected_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9,
    $10, $11, $12, $13, $14, $15
)
ON CONFLICT (source, item_id) DO UPDATE SET
    shop_id = excluded.shop_id,
    shop_name = excluded.shop_name,
    name = excluded.name,
    image_url = excluded.image_url,
    category_id = excluded.category_id,
    categories = excluded.categories,
    url = excluded.url,
    min_price_cents = excluded.min_price_cents,
    max_price_cents = excluded.max_price_cents,
    commission_bp = excluded.commission_bp,
    sales = excluded.sales,
    rating = excluded.rating,
    collected_at = excluded.collected_at
WHERE products.collected_at <= excluded.collected_at
RETURNING id
`

type UpsertProductBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertProductParams struct {
	Source        Source
	ItemID        int64
	ShopID        int64
	ShopName      string
	Name          string
	ImageURL      *string
	CategoryID    *int64
	Categories    []int64
	URL           string
	MinPriceCents int64
	MaxPriceCents int64
	CommissionBp  int32
	Sales         int64
	Rating        *float64
	CollectedAt   time.Time
}

func (q *Queries) UpsertProduct(ctx context.Context, arg []UpsertProductParams) *UpsertProductBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Source,
			a.ItemID,
			a.ShopID,
			a.ShopName,
			a.Name,
			a.ImageURL,
			a.CategoryID,
			a.Categories,
			a.URL,
			a.MinPriceCents,
			a.MaxPriceCents,
			a.CommissionBp,
			a.Sales,
			a.Rating,
			a.CollectedAt,
		}
		batch.Queue(upsertProduct, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertProductBatchResults{br, len(arg), false}
}

func (b *UpsertProductBatchResults) QueryRow(f func(int, uuid.UUID, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var id uuid.UUID
		if b.closed {
			if f != nil {
				f(t, id, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(&id)
		if f != nil {
			f(t, id, err)
		}
	}
}

func (b *UpsertProductBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertTrend = `-- name: UpsertTrend :batchexec
INSERT INTO trends (
    product_id, computed_at, score, earnings_per_sale_cents, sales_growth_7d,
    name, shop_name, image_url, category_id, categories, url,
    min_price_cents, max_price_cents, commission_bp, sales, rating, updated_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16, $17
)
ON CONFLICT (product_id) DO UPDATE SET
    computed_at = excluded.computed_at,
    score = excluded.score,
    earnings_per_sale_cents = excluded.earnings_per_sale_cents,
    sales_growth_7d = excluded.sales_growth_7d,
    name = excluded.name,
    shop_name = excluded.shop_name,
    image_url = excluded.image_url,
    category_id = excluded.category_id,
    categories = excluded.categories,
    url = excluded.url,
    min_price_cents = excluded.min_price_cents,
    max_price_cents = excluded.max_price_cents,
    commission_bp = excluded.commission_bp,
    sales = excluded.sales,
    rating = excluded.rating,
    updated_at = excluded.updated_at
`

type UpsertTrendBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertTrendParams struct {
	ProductID            uuid.UUID
	ComputedAt           time.Time
	Score                float64
	EarningsPerSaleCents int64
	SalesGrowth7d        *int64
	Name                 string
	ShopName             string
	ImageURL             *string
	CategoryID           *int64
	Categories           []int64
	URL                  string
	MinPriceCents        int64
	MaxPriceCents        int64
	CommissionBp         int32
	Sales                int64
	Rating               *float64
	UpdatedAt            time.Time
}

func (q *Queries) UpsertTrend(ctx context.Context, arg []UpsertTrendParams) *UpsertTrendBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ProductID,
			a.ComputedAt,
			a.Score,
			a.EarningsPerSaleCents,
			a.SalesGrowth7d,
			a.Name,
			a.ShopName,
			a.ImageURL,
			a.CategoryID,
			a.Categories,
			a.URL,
			a.MinPriceCents,
			a.MaxPriceCents,
			a.CommissionBp,
			a.Sales,
			a.Rating,
			a.UpdatedAt,
		}
		batch.Queue(upsertTrend, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertTrendBatchResults{br, len(arg), false}
}

func (b *UpsertTrendBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertTrendBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
