// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelSubscription = `-- name: CancelSubscription :one
UPDATE subscriptions
SET status = 'cancelled',
    payment_url = NULL,
    cancelled_at = now(),
    updated_at = now()
WHERE workspace_id = $1 AND cancelled_at IS NULL
RETURNING workspace_id, provider, external_customer_id, external_id, status, seats, amount_cents, next_due_date, payment_url, created_by, created_at, updated_at, cancelled_at
`

func (q *Queries) CancelSubscription(ctx context.Context, workspaceID uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, cancelSubscription, workspaceID)
	var i Subscription
	err := row.Scan(
		&i.WorkspaceID,
		&i.Provider,
		&i.ExternalCustomerID,
		&i.ExternalID,
		&i.Status,
		&i.Seats,
		&i.AmountCents,
		&i.NextDueDate,
		&i.PaymentURL,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const recordBillingEvent = `-- name: RecordBillingEvent :execrows
INSERT INTO billing_events (provider, event_id, workspace_id, kind)
VALUES ($1, $2, $3, $4)
ON CONFLICT (provider, event_id) DO NOTHING
`

type RecordBillingEventParams struct {
	Provider    string
	EventID     string
	WorkspaceID uuid.UUID
	Kind        string
}

// Returns 0 when the event was already processed (a gateway redelivery).
func (q *Queries) RecordBillingEvent(ctx context.Context, arg RecordBillingEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordBillingEvent,
		arg.Provider,
		arg.EventID,
		arg.WorkspaceID,
		arg.Kind,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveSubscription = `-- name: SaveSubscription :one
INSERT INTO subscriptions (
    workspace_id, provider, external_customer_id, external_id, status,
    seats, amount_cents, next_due_date, payment_url, created_by
) VALUES ($1, $2, $3, $4, 'pending', $5, $6, $7, $8, $9)
ON CONFLICT (workspace_id) DO UPDATE
    SET provider = EXCLUDED.provider,
        external_customer_id = EXCLUDED.external_customer_id,
        external_id = EXCLUDED.external_id,
        status = 'pending',
        seats = EXCLUDED.seats,
        amount_cents = EXCLUDED.amount_cents,
        next_due_date = EXCLUDED.next_due_date,
        payment_url = EXCLUDED.payment_url,
        created_by = EXCLUDED.created_by,
        updated_at = now(),
        cancelled_at = NULL
    WHERE subscriptions.cancelled_at IS NOT NULL
RETURNING workspace_id, provider, external_customer_id, external_id, status, seats, amount_cents, next_due_date, payment_url, created_by, created_at, updated_at, cancelled_at
`

type SaveSubscriptionParams struct {
	WorkspaceID        uuid.UUID
	Provider           string
	ExternalCustomerID string
	ExternalID         string
	Seats              int32
	AmountCents        int64
	NextDueDate        pgtype.Date
	PaymentURL         *string
	CreatedBy          uuid.UUID
}

// Stores the subscription of the workspace. A new one only replaces a
// cancelled one: no row returned means one is already in progress.
func (q *Queries) SaveSubscription(ctx context.Context, arg SaveSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, saveSubscription,
		arg.WorkspaceID,
		arg.Provider,
		arg.ExternalCustomerID,
		arg.ExternalID,
		arg.Seats,
		arg.AmountCents,
		arg.NextDueDate,
		arg.PaymentURL,
		arg.CreatedBy,
	)
	var i Subscription
	err := row.Scan(
		&i.WorkspaceID,
		&i.Provider,
		&i.ExternalCustomerID,
		&i.ExternalID,
		&i.Status,
		&i.Seats,
		&i.AmountCents,
		&i.NextDueDate,
		&i.PaymentURL,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const subscriptionByExternalID = `-- name: SubscriptionByExternalID :one
SELECT workspace_id, provider, external_customer_id, external_id, status, seats, amount_cents, next_due_date, payment_url, created_by, created_at, updated_at, cancelled_at FROM subscriptions WHERE provider = $1 AND external_id = $2
`

type SubscriptionByExternalIDParams struct {
	Provider   string
	ExternalID string
}

func (q *Queries) SubscriptionByExternalID(ctx context.Context, arg SubscriptionByExternalIDParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, subscriptionByExternalID, arg.Provider, arg.ExternalID)
	var i Subscription
	err := row.Scan(
		&i.WorkspaceID,
		&i.Provider,
		&i.ExternalCustomerID,
		&i.ExternalID,
		&i.Status,
		&i.Seats,
		&i.AmountCents,
		&i.NextDueDate,
		&i.PaymentURL,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const subscriptionByWorkspace = `-- name: SubscriptionByWorkspace :one

SELECT workspace_id, provider, external_customer_id, external_id, status, seats, amount_cents, next_due_date, payment_url, created_by, created_at, updated_at, cancelled_at FROM subscriptions WHERE workspace_id = $1
`

// Queries of the billing module. Generate the code with `make sqlc`.
func (q *Queries) SubscriptionByWorkspace(ctx context.Context, workspaceID uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, subscriptionByWorkspace, workspaceID)
	var i Subscription
	err := row.Scan(
		&i.WorkspaceID,
		&i.Provider,
		&i.ExternalCustomerID,
		&i.ExternalID,
		&i.Status,
		&i.Seats,
		&i.AmountCents,
		&i.NextDueDate,
		&i.PaymentURL,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const updateSubscriptionBilling = `-- name: UpdateSubscriptionBilling :one
UPDATE subscriptions
SET status = $1,
    next_due_date = coalesce($2, next_due_date),
    payment_url = coalesce($3, payment_url),
    updated_at = now()
WHERE workspace_id = $4
RETURNING workspace_id, provider, external_customer_id, external_id, status, seats, amount_cents, next_due_date, payment_url, created_by, created_at, updated_at, cancelled_at
`

type UpdateSubscriptionBillingParams struct {
	Status      SubscriptionStatus
	NextDueDate pgtype.Date
	PaymentURL  *string
	WorkspaceID uuid.UUID
}

// Status coming from the gateway. A null due date or payment_url keeps the
// current one (a confirmed payment brings no open invoice).
func (q *Queries) UpdateSubscriptionBilling(ctx context.Context, arg UpdateSubscriptionBillingParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionBilling,
		arg.Status,
		arg.NextDueDate,
		arg.PaymentURL,
		arg.WorkspaceID,
	)
	var i Subscription
	err := row.Scan(
		&i.WorkspaceID,
		&i.Provider,
		&i.ExternalCustomerID,
		&i.ExternalID,
		&i.Status,
		&i.Seats,
		&i.AmountCents,
		&i.NextDueDate,
		&i.PaymentURL,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const updateSubscriptionPlan = `-- name: UpdateSubscriptionPlan :one
UPDATE subscriptions
SET seats = $1,
    amount_cents = $2,
    updated_at = now()
WHERE workspace_id = $3 AND cancelled_at IS NULL
RETURNING workspace_id, provider, external_customer_id, external_id, status, seats, amount_cents, next_due_date, payment_url, created_by, created_at, updated_at, cancelled_at
`

type UpdateSubscriptionPlanParams struct {
	Seats       int32
	AmountCents int64
	WorkspaceID uuid.UUID
}

// Changes seats and amount of a subscription in progress (more or fewer
// affiliates in the group).
func (q *Queries) UpdateSubscriptionPlan(ctx context.Context, arg UpdateSubscriptionPlanParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscriptionPlan, arg.Seats, arg.AmountCents, arg.WorkspaceID)
	var i Subscription
	err := row.Scan(
		&i.WorkspaceID,
		&i.Provider,
		&i.ExternalCustomerID,
		&i.ExternalID,
		&i.Status,
		&i.Seats,
		&i.AmountCents,
		&i.NextDueDate,
		&i.PaymentURL,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}
