// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: collections.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addCollectionItem = `-- name: AddCollectionItem :exec
INSERT INTO collection_items (collection_id, item_id, workspace_id, user_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type AddCollectionItemParams struct {
	CollectionID uuid.UUID
	ItemID       uuid.UUID
	WorkspaceID  uuid.UUID
	UserID       uuid.UUID
}

func (q *Queries) AddCollectionItem(ctx context.Context, arg AddCollectionItemParams) error {
	_, err := q.db.Exec(ctx, addCollectionItem,
		arg.CollectionID,
		arg.ItemID,
		arg.WorkspaceID,
		arg.UserID,
	)
	return err
}

const channelLinksOfItems = `-- name: ChannelLinksOfItems :many
SELECT item_id, channel, sub_id, url FROM channel_links
WHERE workspace_id = $1 AND user_id = $2 AND item_id = ANY ($3::uuid[])
ORDER BY item_id, channel
`

type ChannelLinksOfItemsParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Ids         []uuid.UUID
}

type ChannelLinksOfItemsRow struct {
	ItemID  uuid.UUID
	Channel Channel
	SubID   string
	URL     string
}

func (q *Queries) ChannelLinksOfItems(ctx context.Context, arg ChannelLinksOfItemsParams) ([]ChannelLinksOfItemsRow, error) {
	rows, err := q.db.Query(ctx, channelLinksOfItems, arg.WorkspaceID, arg.UserID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChannelLinksOfItemsRow
	for rows.Next() {
		var i ChannelLinksOfItemsRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Channel,
			&i.SubID,
			&i.URL,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimPendingLinks = `-- name: ClaimPendingLinks :many
UPDATE saved_items SET link_status = 'generating', updated_at = now()
WHERE workspace_id = $1 AND user_id = $2
  AND link_origin = 'auto' AND link_status IN ('pending', 'failed')
RETURNING id
`

type ClaimPendingLinksParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

// Automatic links pending (no credential) or failed, to generate again.
func (q *Queries) ClaimPendingLinks(ctx context.Context, arg ClaimPendingLinksParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, claimPendingLinks, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearItemCollections = `-- name: ClearItemCollections :exec
DELETE FROM collection_items WHERE item_id = $1 AND workspace_id = $2 AND user_id = $3
`

type ClearItemCollectionsParams struct {
	ItemID      uuid.UUID
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) ClearItemCollections(ctx context.Context, arg ClearItemCollectionsParams) error {
	_, err := q.db.Exec(ctx, clearItemCollections, arg.ItemID, arg.WorkspaceID, arg.UserID)
	return err
}

const collectionByID = `-- name: CollectionByID :one
SELECT c.id, c.name, c.created_at,
    (SELECT count(*) FROM collection_items ci
     WHERE ci.collection_id = c.id AND ci.workspace_id = $1 AND ci.user_id = $2) AS items
FROM collections c
WHERE c.id = $3 AND c.workspace_id = $1 AND c.user_id = $2
`

type CollectionByIDParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	ID          uuid.UUID
}

type CollectionByIDRow struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	Items     int64
}

func (q *Queries) CollectionByID(ctx context.Context, arg CollectionByIDParams) (CollectionByIDRow, error) {
	row := q.db.QueryRow(ctx, collectionByID, arg.WorkspaceID, arg.UserID, arg.ID)
	var i CollectionByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.Items,
	)
	return i, err
}

const collectionByName = `-- name: CollectionByName :one
SELECT id FROM collections
WHERE workspace_id = $1 AND user_id = $2 AND lower(name) = lower($3)
`

type CollectionByNameParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Name        string
}

func (q *Queries) CollectionByName(ctx context.Context, arg CollectionByNameParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, collectionByName, arg.WorkspaceID, arg.UserID, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const collectionsOfItems = `-- name: CollectionsOfItems :many
SELECT item_id, collection_id FROM collection_items
WHERE workspace_id = $1 AND user_id = $2 AND item_id = ANY ($3::uuid[])
ORDER BY item_id, added_at
`

type CollectionsOfItemsParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Ids         []uuid.UUID
}

type CollectionsOfItemsRow struct {
	ItemID       uuid.UUID
	CollectionID uuid.UUID
}

func (q *Queries) CollectionsOfItems(ctx context.Context, arg CollectionsOfItemsParams) ([]CollectionsOfItemsRow, error) {
	rows, err := q.db.Query(ctx, collectionsOfItems, arg.WorkspaceID, arg.UserID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectionsOfItemsRow
	for rows.Next() {
		var i CollectionsOfItemsRow
		if err := rows.Scan(&i.ItemID, &i.CollectionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeAutoLink = `-- name: CompleteAutoLink :execrows
UPDATE saved_items SET affiliate_link = $1, link_status = 'ready', updated_at = now()
WHERE id = $2 AND workspace_id = $3 AND user_id = $4 AND link_origin = 'auto'
`

type CompleteAutoLinkParams struct {
	AffiliateLink *string
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
	UserID        uuid.UUID
}

func (q *Queries) CompleteAutoLink(ctx context.Context, arg CompleteAutoLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeAutoLink,
		arg.AffiliateLink,
		arg.ID,
		arg.WorkspaceID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countCollections = `-- name: CountCollections :one
SELECT count(*) FROM collections
WHERE workspace_id = $1 AND user_id = $2 AND id = ANY ($3::uuid[])
`

type CountCollectionsParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Ids         []uuid.UUID
}

func (q *Queries) CountCollections(ctx context.Context, arg CountCollectionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCollections, arg.WorkspaceID, arg.UserID, arg.Ids)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (workspace_id, user_id, name) VALUES ($1, $2, $3)
RETURNING id
`

type CreateCollectionParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Name        string
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createCollection, arg.WorkspaceID, arg.UserID, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createSavedItem = `-- name: CreateSavedItem :one

INSERT INTO saved_items (workspace_id, user_id, product_id, title, notes, link_status)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (workspace_id, user_id, product_id) DO NOTHING
RETURNING id, workspace_id, user_id, product_id, title, description, notes, tags, status, affiliate_link, link_origin, link_status, created_at, updated_at
`

type CreateSavedItemParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	ProductID   uuid.UUID
	Title       string
	Notes       string
	LinkStatus  LinkStatus
}

// Collections: every query filters by workspace_id and user_id, besides RLS.
func (q *Queries) CreateSavedItem(ctx context.Context, arg CreateSavedItemParams) (SavedItem, error) {
	row := q.db.QueryRow(ctx, createSavedItem,
		arg.WorkspaceID,
		arg.UserID,
		arg.ProductID,
		arg.Title,
		arg.Notes,
		arg.LinkStatus,
	)
	var i SavedItem
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.ProductID,
		&i.Title,
		&i.Description,
		&i.Notes,
		&i.Tags,
		&i.Status,
		&i.AffiliateLink,
		&i.LinkOrigin,
		&i.LinkStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChannelLinks = `-- name: DeleteChannelLinks :exec
DELETE FROM channel_links WHERE item_id = $1 AND workspace_id = $2 AND user_id = $3
`

type DeleteChannelLinksParams struct {
	ItemID      uuid.UUID
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) DeleteChannelLinks(ctx context.Context, arg DeleteChannelLinksParams) error {
	_, err := q.db.Exec(ctx, deleteChannelLinks, arg.ItemID, arg.WorkspaceID, arg.UserID)
	return err
}

const deleteCollection = `-- name: DeleteCollection :execrows
DELETE FROM collections WHERE id = $1 AND workspace_id = $2 AND user_id = $3
`

type DeleteCollectionParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) DeleteCollection(ctx context.Context, arg DeleteCollectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCollection, arg.ID, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSavedItem = `-- name: DeleteSavedItem :execrows
DELETE FROM saved_items WHERE id = $1 AND workspace_id = $2 AND user_id = $3
`

type DeleteSavedItemParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) DeleteSavedItem(ctx context.Context, arg DeleteSavedItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSavedItem, arg.ID, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listCollections = `-- name: ListCollections :many
SELECT c.id, c.name, c.created_at,
    (SELECT count(*) FROM collection_items ci
     WHERE ci.collection_id = c.id AND ci.workspace_id = $1 AND ci.user_id = $2) AS items
FROM collections c
WHERE c.workspace_id = $1 AND c.user_id = $2
ORDER BY lower(c.name)
`

type ListCollectionsParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

type ListCollectionsRow struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	Items     int64
}

func (q *Queries) ListCollections(ctx context.Context, arg ListCollectionsParams) ([]ListCollectionsRow, error) {
	rows, err := q.db.Query(ctx, listCollections, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCollectionsRow
	for rows.Next() {
		var i ListCollectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.Items,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedItems = `-- name: ListSavedItems :many
SELECT i.id, i.workspace_id, i.user_id, i.product_id, i.title, i.description, i.notes, i.tags, i.status, i.affiliate_link, i.link_origin, i.link_status, i.created_at, i.updated_at, count(*) OVER () AS total
FROM saved_items i
WHERE i.workspace_id = $1 AND i.user_id = $2
  AND ($3::item_status IS NULL OR i.status = $3)
  AND ($4::text IS NULL OR $4 = ANY (i.tags))
  AND ($5::text IS NULL
       OR i.title ILIKE '%' || $5 || '%'
       OR i.description ILIKE '%' || $5 || '%'
       OR i.notes ILIKE '%' || $5 || '%')
  AND ($6::uuid IS NULL OR EXISTS (
       SELECT 1 FROM collection_items ci
       WHERE ci.item_id = i.id AND ci.collection_id = $6
         AND ci.workspace_id = $1 AND ci.user_id = $2))
ORDER BY i.created_at DESC, i.id
LIMIT $8 OFFSET $7
`

type ListSavedItemsParams struct {
	WorkspaceID  uuid.UUID
	UserID       uuid.UUID
	Status       *ItemStatus
	Tag          *string
	Query        *string
	CollectionID *uuid.UUID
	RowOffset    int32
	RowLimit     int32
}

type ListSavedItemsRow struct {
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
	UserID        uuid.UUID
	ProductID     uuid.UUID
	Title         string
	Description   string
	Notes         string
	Tags          []string
	Status        ItemStatus
	AffiliateLink *string
	LinkOrigin    LinkOrigin
	LinkStatus    LinkStatus
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Total         int64
}

func (q *Queries) ListSavedItems(ctx context.Context, arg ListSavedItemsParams) ([]ListSavedItemsRow, error) {
	rows, err := q.db.Query(ctx, listSavedItems,
		arg.WorkspaceID,
		arg.UserID,
		arg.Status,
		arg.Tag,
		arg.Query,
		arg.CollectionID,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSavedItemsRow
	for rows.Next() {
		var i ListSavedItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.ProductID,
			&i.Title,
			&i.Description,
			&i.Notes,
			&i.Tags,
			&i.Status,
			&i.AffiliateLink,
			&i.LinkOrigin,
			&i.LinkStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLinkStatus = `-- name: MarkLinkStatus :exec
UPDATE saved_items SET link_status = $1, updated_at = now()
WHERE id = $2 AND workspace_id = $3 AND user_id = $4 AND link_origin = 'auto'
`

type MarkLinkStatusParams struct {
	LinkStatus  LinkStatus
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

// Only touches automatic links: a manual link saved while the job ran wins.
func (q *Queries) MarkLinkStatus(ctx context.Context, arg MarkLinkStatusParams) error {
	_, err := q.db.Exec(ctx, markLinkStatus,
		arg.LinkStatus,
		arg.ID,
		arg.WorkspaceID,
		arg.UserID,
	)
	return err
}

const renameCollection = `-- name: RenameCollection :execrows
UPDATE collections SET name = $1
WHERE id = $2 AND workspace_id = $3 AND user_id = $4
`

type RenameCollectionParams struct {
	Name        string
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) RenameCollection(ctx context.Context, arg RenameCollectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameCollection,
		arg.Name,
		arg.ID,
		arg.WorkspaceID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetAutoLink = `-- name: ResetAutoLink :one
UPDATE saved_items SET
    affiliate_link = NULL, link_origin = 'auto', link_status = $1, updated_at = now()
WHERE id = $2 AND workspace_id = $3 AND user_id = $4
RETURNING id, workspace_id, user_id, product_id, title, description, notes, tags, status, affiliate_link, link_origin, link_status, created_at, updated_at
`

type ResetAutoLinkParams struct {
	LinkStatus  LinkStatus
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

// Back to the automatic link: clears the current one and waits for the
// generate_affiliate_link job.
func (q *Queries) ResetAutoLink(ctx context.Context, arg ResetAutoLinkParams) (SavedItem, error) {
	row := q.db.QueryRow(ctx, resetAutoLink,
		arg.LinkStatus,
		arg.ID,
		arg.WorkspaceID,
		arg.UserID,
	)
	var i SavedItem
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.ProductID,
		&i.Title,
		&i.Description,
		&i.Notes,
		&i.Tags,
		&i.Status,
		&i.AffiliateLink,
		&i.LinkOrigin,
		&i.LinkStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const saveChannelLink = `-- name: SaveChannelLink :exec
INSERT INTO channel_links (item_id, workspace_id, user_id, channel, sub_id, url)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (item_id, channel) DO UPDATE SET sub_id = excluded.sub_id, url = excluded.url, generated_at = now()
`

type SaveChannelLinkParams struct {
	ItemID      uuid.UUID
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Channel     Channel
	SubID       string
	URL         string
}

func (q *Queries) SaveChannelLink(ctx context.Context, arg SaveChannelLinkParams) error {
	_, err := q.db.Exec(ctx, saveChannelLink,
		arg.ItemID,
		arg.WorkspaceID,
		arg.UserID,
		arg.Channel,
		arg.SubID,
		arg.URL,
	)
	return err
}

const savedItemByID = `-- name: SavedItemByID :one
SELECT id, workspace_id, user_id, product_id, title, description, notes, tags, status, affiliate_link, link_origin, link_status, created_at, updated_at FROM saved_items
WHERE id = $1 AND workspace_id = $2 AND user_id = $3
`

type SavedItemByIDParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) SavedItemByID(ctx context.Context, arg SavedItemByIDParams) (SavedItem, error) {
	row := q.db.QueryRow(ctx, savedItemByID, arg.ID, arg.WorkspaceID, arg.UserID)
	var i SavedItem
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.ProductID,
		&i.Title,
		&i.Description,
		&i.Notes,
		&i.Tags,
		&i.Status,
		&i.AffiliateLink,
		&i.LinkOrigin,
		&i.LinkStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const savedItemByProduct = `-- name: SavedItemByProduct :one
SELECT id, workspace_id, user_id, product_id, title, description, notes, tags, status, affiliate_link, link_origin, link_status, created_at, updated_at FROM saved_items
WHERE workspace_id = $1 AND user_id = $2 AND product_id = $3
`

type SavedItemByProductParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	ProductID   uuid.UUID
}

func (q *Queries) SavedItemByProduct(ctx context.Context, arg SavedItemByProductParams) (SavedItem, error) {
	row := q.db.QueryRow(ctx, savedItemByProduct, arg.WorkspaceID, arg.UserID, arg.ProductID)
	var i SavedItem
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.ProductID,
		&i.Title,
		&i.Description,
		&i.Notes,
		&i.Tags,
		&i.Status,
		&i.AffiliateLink,
		&i.LinkOrigin,
		&i.LinkStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const savedItemsByProducts = `-- name: SavedItemsByProducts :many
SELECT id, workspace_id, user_id, product_id, title, description, notes, tags, status, affiliate_link, link_origin, link_status, created_at, updated_at FROM saved_items
WHERE workspace_id = $1 AND user_id = $2 AND product_id = ANY ($3::uuid[])
`

type SavedItemsByProductsParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	ProductIds  []uuid.UUID
}

func (q *Queries) SavedItemsByProducts(ctx context.Context, arg SavedItemsByProductsParams) ([]SavedItem, error) {
	rows, err := q.db.Query(ctx, savedItemsByProducts, arg.WorkspaceID, arg.UserID, arg.ProductIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SavedItem
	for rows.Next() {
		var i SavedItem
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.ProductID,
			&i.Title,
			&i.Description,
			&i.Notes,
			&i.Tags,
			&i.Status,
			&i.AffiliateLink,
			&i.LinkOrigin,
			&i.LinkStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const savedProductIDs = `-- name: SavedProductIDs :many
SELECT product_id FROM saved_items
WHERE workspace_id = $1 AND user_id = $2
ORDER BY created_at DESC
`

type SavedProductIDsParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) SavedProductIDs(ctx context.Context, arg SavedProductIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, savedProductIDs, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var product_id uuid.UUID
		if err := rows.Scan(&product_id); err != nil {
			return nil, err
		}
		items = append(items, product_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setManualLink = `-- name: SetManualLink :one
UPDATE saved_items SET
    affiliate_link = $1, link_origin = 'manual', link_status = 'ready', updated_at = now()
WHERE id = $2 AND workspace_id = $3 AND user_id = $4
RETURNING id, workspace_id, user_id, product_id, title, description, notes, tags, status, affiliate_link, link_origin, link_status, created_at, updated_at
`

type SetManualLinkParams struct {
	AffiliateLink *string
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
	UserID        uuid.UUID
}

func (q *Queries) SetManualLink(ctx context.Context, arg SetManualLinkParams) (SavedItem, error) {
	row := q.db.QueryRow(ctx, setManualLink,
		arg.AffiliateLink,
		arg.ID,
		arg.WorkspaceID,
		arg.UserID,
	)
	var i SavedItem
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.ProductID,
		&i.Title,
		&i.Description,
		&i.Notes,
		&i.Tags,
		&i.Status,
		&i.AffiliateLink,
		&i.LinkOrigin,
		&i.LinkStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSavedItem = `-- name: UpdateSavedItem :one
UPDATE saved_items SET
    title = coalesce($1, title),
    description = coalesce($2, description),
    notes = coalesce($3, notes),
    tags = coalesce($4::text[], tags),
    status = coalesce($5::item_status, status),
    updated_at = now()
WHERE id = $6 AND workspace_id = $7 AND user_id = $8
RETURNING id, workspace_id, user_id, product_id, title, description, notes, tags, status, affiliate_link, link_origin, link_status, created_at, updated_at
`

type UpdateSavedItemParams struct {
	Title       *string
	Description *string
	Notes       *string
	Tags        []string
	Status      *ItemStatus
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) UpdateSavedItem(ctx context.Context, arg UpdateSavedItemParams) (SavedItem, error) {
	row := q.db.QueryRow(ctx, updateSavedItem,
		arg.Title,
		arg.Description,
		arg.Notes,
		arg.Tags,
		arg.Status,
		arg.ID,
		arg.WorkspaceID,
		arg.UserID,
	)
	var i SavedItem
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.ProductID,
		&i.Title,
		&i.Description,
		&i.Notes,
		&i.Tags,
		&i.Status,
		&i.AffiliateLink,
		&i.LinkOrigin,
		&i.LinkStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
