// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: curation.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addCuratedListItem = `-- name: AddCuratedListItem :execrows
INSERT INTO curated_list_items (list_id, workspace_id, product_id, comment, position)
SELECT $1::uuid, $2::uuid, $3::uuid,
       $4::text, coalesce(max(li.position), 0) + 1
FROM curated_list_items li
WHERE li.list_id = $1::uuid AND li.workspace_id = $2::uuid
ON CONFLICT (list_id, product_id) DO NOTHING
`

type AddCuratedListItemParams struct {
	ListID      uuid.UUID
	WorkspaceID uuid.UUID
	ProductID   uuid.UUID
	Comment     string
}

// Goes to the end of the list; a product already in it is left as is.
func (q *Queries) AddCuratedListItem(ctx context.Context, arg AddCuratedListItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, addCuratedListItem,
		arg.ListID,
		arg.WorkspaceID,
		arg.ProductID,
		arg.Comment,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const commentCuratedListItem = `-- name: CommentCuratedListItem :execrows
UPDATE curated_list_items SET comment = $1
WHERE list_id = $2 AND workspace_id = $3 AND product_id = $4
`

type CommentCuratedListItemParams struct {
	Comment     string
	ListID      uuid.UUID
	WorkspaceID uuid.UUID
	ProductID   uuid.UUID
}

func (q *Queries) CommentCuratedListItem(ctx context.Context, arg CommentCuratedListItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, commentCuratedListItem,
		arg.Comment,
		arg.ListID,
		arg.WorkspaceID,
		arg.ProductID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countCuratedLists = `-- name: CountCuratedLists :one

SELECT count(*) FROM curated_lists WHERE workspace_id = $1
`

// Curation: every query filters by workspace_id, besides RLS (which hides the
// drafts from whoever is not owner or mentor).
func (q *Queries) CountCuratedLists(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCuratedLists, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCuratedList = `-- name: CreateCuratedList :one
INSERT INTO curated_lists (workspace_id, author_id, title, description)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateCuratedListParams struct {
	WorkspaceID uuid.UUID
	AuthorID    uuid.UUID
	Title       string
	Description string
}

func (q *Queries) CreateCuratedList(ctx context.Context, arg CreateCuratedListParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createCuratedList,
		arg.WorkspaceID,
		arg.AuthorID,
		arg.Title,
		arg.Description,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const curatedList = `-- name: CuratedList :one
SELECT l.id, l.title, l.description, l.published_at, l.created_at, l.updated_at,
    (SELECT count(*) FROM curated_list_items li
     WHERE li.list_id = l.id AND li.workspace_id = $1) AS products,
    (SELECT count(DISTINCT i.user_id) FROM list_imports i
     WHERE i.list_id = l.id AND i.workspace_id = $1) AS importers,
    EXISTS (SELECT 1 FROM list_imports i
            WHERE i.list_id = l.id AND i.workspace_id = $1 AND i.user_id = $2) AS imported_by_me
FROM curated_lists l
WHERE l.id = $3 AND l.workspace_id = $1
  AND ($4::boolean OR l.published_at IS NOT NULL)
`

type CuratedListParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	ID          uuid.UUID
	Drafts      bool
}

type CuratedListRow struct {
	ID           uuid.UUID
	Title        string
	Description  string
	PublishedAt  *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Products     int64
	Importers    int64
	ImportedByMe bool
}

func (q *Queries) CuratedList(ctx context.Context, arg CuratedListParams) (CuratedListRow, error) {
	row := q.db.QueryRow(ctx, curatedList,
		arg.WorkspaceID,
		arg.UserID,
		arg.ID,
		arg.Drafts,
	)
	var i CuratedListRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Products,
		&i.Importers,
		&i.ImportedByMe,
	)
	return i, err
}

const curatedListItems = `-- name: CuratedListItems :many
SELECT product_id, comment, position FROM curated_list_items
WHERE list_id = $1 AND workspace_id = $2
ORDER BY position, product_id
`

type CuratedListItemsParams struct {
	ListID      uuid.UUID
	WorkspaceID uuid.UUID
}

type CuratedListItemsRow struct {
	ProductID uuid.UUID
	Comment   string
	Position  int32
}

func (q *Queries) CuratedListItems(ctx context.Context, arg CuratedListItemsParams) ([]CuratedListItemsRow, error) {
	rows, err := q.db.Query(ctx, curatedListItems, arg.ListID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CuratedListItemsRow
	for rows.Next() {
		var i CuratedListItemsRow
		if err := rows.Scan(&i.ProductID, &i.Comment, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const curatedLists = `-- name: CuratedLists :many
SELECT l.id, l.title, l.description, l.published_at, l.created_at, l.updated_at,
    (SELECT count(*) FROM curated_list_items li
     WHERE li.list_id = l.id AND li.workspace_id = $1) AS products,
    (SELECT count(DISTINCT i.user_id) FROM list_imports i
     WHERE i.list_id = l.id AND i.workspace_id = $1) AS importers,
    EXISTS (SELECT 1 FROM list_imports i
            WHERE i.list_id = l.id AND i.workspace_id = $1 AND i.user_id = $2) AS imported_by_me
FROM curated_lists l
WHERE l.workspace_id = $1
  AND ($3::boolean OR l.published_at IS NOT NULL)
ORDER BY l.published_at IS NOT NULL, coalesce(l.published_at, l.created_at) DESC, l.id
`

type CuratedListsParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Drafts      bool
}

type CuratedListsRow struct {
	ID           uuid.UUID
	Title        string
	Description  string
	PublishedAt  *time.Time
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Products     int64
	Importers    int64
	ImportedByMe bool
}

// Drafts only come with drafts = true (and RLS only shows them to owner and
// mentor). importers counts the group; imported_by_me, the user.
func (q *Queries) CuratedLists(ctx context.Context, arg CuratedListsParams) ([]CuratedListsRow, error) {
	rows, err := q.db.Query(ctx, curatedLists, arg.WorkspaceID, arg.UserID, arg.Drafts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CuratedListsRow
	for rows.Next() {
		var i CuratedListsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.PublishedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Products,
			&i.Importers,
			&i.ImportedByMe,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCuratedList = `-- name: DeleteCuratedList :execrows
DELETE FROM curated_lists WHERE id = $1 AND workspace_id = $2
`

type DeleteCuratedListParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) DeleteCuratedList(ctx context.Context, arg DeleteCuratedListParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCuratedList, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listImporters = `-- name: ListImporters :many
SELECT user_id, count(*) AS products, max(imported_at)::timestamptz AS last_imported_at FROM list_imports
WHERE list_id = $1 AND workspace_id = $2
GROUP BY user_id
ORDER BY last_imported_at DESC
`

type ListImportersParams struct {
	ListID      uuid.UUID
	WorkspaceID uuid.UUID
}

type ListImportersRow struct {
	UserID         uuid.UUID
	Products       int64
	LastImportedAt time.Time
}

func (q *Queries) ListImporters(ctx context.Context, arg ListImportersParams) ([]ListImportersRow, error) {
	rows, err := q.db.Query(ctx, listImporters, arg.ListID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListImportersRow
	for rows.Next() {
		var i ListImportersRow
		if err := rows.Scan(&i.UserID, &i.Products, &i.LastImportedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportersByProduct = `-- name: ListImportersByProduct :many
SELECT product_id, count(*) AS importers FROM list_imports
WHERE list_id = $1 AND workspace_id = $2
GROUP BY product_id
`

type ListImportersByProductParams struct {
	ListID      uuid.UUID
	WorkspaceID uuid.UUID
}

type ListImportersByProductRow struct {
	ProductID uuid.UUID
	Importers int64
}

func (q *Queries) ListImportersByProduct(ctx context.Context, arg ListImportersByProductParams) ([]ListImportersByProductRow, error) {
	rows, err := q.db.Query(ctx, listImportersByProduct, arg.ListID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListImportersByProductRow
	for rows.Next() {
		var i ListImportersByProductRow
		if err := rows.Scan(&i.ProductID, &i.Importers); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCuratedList = `-- name: LockCuratedList :one
SELECT id FROM curated_lists
WHERE id = $1 AND workspace_id = $2
FOR UPDATE
`

type LockCuratedListParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) LockCuratedList(ctx context.Context, arg LockCuratedListParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockCuratedList, arg.ID, arg.WorkspaceID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const publishCuratedList = `-- name: PublishCuratedList :execrows
UPDATE curated_lists SET published_at = now(), updated_at = now()
WHERE id = $1 AND workspace_id = $2 AND published_at IS NULL
`

type PublishCuratedListParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

// Only the first publication counts: publishing again changes nothing.
func (q *Queries) PublishCuratedList(ctx context.Context, arg PublishCuratedListParams) (int64, error) {
	result, err := q.db.Exec(ctx, publishCuratedList, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const publishedListImports = `-- name: PublishedListImports :many
SELECT i.list_id, i.user_id, i.product_id, i.imported_at
FROM list_imports i
JOIN curated_lists l ON l.id = i.list_id AND l.workspace_id = i.workspace_id
WHERE i.workspace_id = $1 AND l.published_at IS NOT NULL
`

type PublishedListImportsRow struct {
	ListID     uuid.UUID
	UserID     uuid.UUID
	ProductID  uuid.UUID
	ImportedAt time.Time
}

// Every import of the published lists, for the results per list.
func (q *Queries) PublishedListImports(ctx context.Context, workspaceID uuid.UUID) ([]PublishedListImportsRow, error) {
	rows, err := q.db.Query(ctx, publishedListImports, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublishedListImportsRow
	for rows.Next() {
		var i PublishedListImportsRow
		if err := rows.Scan(
			&i.ListID,
			&i.UserID,
			&i.ProductID,
			&i.ImportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordListImports = `-- name: RecordListImports :exec
INSERT INTO list_imports (list_id, workspace_id, user_id, product_id)
SELECT $1::uuid, $2::uuid, $3::uuid,
       unnest($4::uuid[])
ON CONFLICT DO NOTHING
`

type RecordListImportsParams struct {
	ListID      uuid.UUID
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	ProductIds  []uuid.UUID
}

func (q *Queries) RecordListImports(ctx context.Context, arg RecordListImportsParams) error {
	_, err := q.db.Exec(ctx, recordListImports,
		arg.ListID,
		arg.WorkspaceID,
		arg.UserID,
		arg.ProductIds,
	)
	return err
}

const removeCuratedListItem = `-- name: RemoveCuratedListItem :execrows
DELETE FROM curated_list_items
WHERE list_id = $1 AND workspace_id = $2 AND product_id = $3
`

type RemoveCuratedListItemParams struct {
	ListID      uuid.UUID
	WorkspaceID uuid.UUID
	ProductID   uuid.UUID
}

func (q *Queries) RemoveCuratedListItem(ctx context.Context, arg RemoveCuratedListItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeCuratedListItem, arg.ListID, arg.WorkspaceID, arg.ProductID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reorderCuratedListItems = `-- name: ReorderCuratedListItems :execrows
UPDATE curated_list_items li SET position = o.position
FROM unnest($3::uuid[]) WITH ORDINALITY AS o(product_id, position)
WHERE li.list_id = $1 AND li.workspace_id = $2 AND li.product_id = o.product_id
`

type ReorderCuratedListItemsParams struct {
	ListID      uuid.UUID
	WorkspaceID uuid.UUID
	ProductIds  []uuid.UUID
}

func (q *Queries) ReorderCuratedListItems(ctx context.Context, arg ReorderCuratedListItemsParams) (int64, error) {
	result, err := q.db.Exec(ctx, reorderCuratedListItems, arg.ListID, arg.WorkspaceID, arg.ProductIds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchCuratedList = `-- name: TouchCuratedList :exec
UPDATE curated_lists SET updated_at = now() WHERE id = $1 AND workspace_id = $2
`

type TouchCuratedListParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) TouchCuratedList(ctx context.Context, arg TouchCuratedListParams) error {
	_, err := q.db.Exec(ctx, touchCuratedList, arg.ID, arg.WorkspaceID)
	return err
}

const updateCuratedList = `-- name: UpdateCuratedList :execrows
UPDATE curated_lists SET
    title = coalesce($1, title),
    description = coalesce($2, description),
    updated_at = now()
WHERE id = $3 AND workspace_id = $4
`

type UpdateCuratedListParams struct {
	Title       *string
	Description *string
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) UpdateCuratedList(ctx context.Context, arg UpdateCuratedListParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCuratedList,
		arg.Title,
		arg.Description,
		arg.ID,
		arg.WorkspaceID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
