// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: media.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const addVideoUsage = `-- name: AddVideoUsage :one
INSERT INTO video_usage (workspace_id, bytes) VALUES ($1, greatest($2::bigint, 0))
ON CONFLICT (workspace_id) DO UPDATE SET bytes = greatest(video_usage.bytes + $2::bigint, 0)
RETURNING bytes
`

type AddVideoUsageParams struct {
	WorkspaceID uuid.UUID
	Delta       int64
}

// Adds (or subtracts) bytes to the usage of the workspace and returns the new total.
func (q *Queries) AddVideoUsage(ctx context.Context, arg AddVideoUsageParams) (int64, error) {
	row := q.db.QueryRow(ctx, addVideoUsage, arg.WorkspaceID, arg.Delta)
	var bytes int64
	err := row.Scan(&bytes)
	return bytes, err
}

const createEmbedVideo = `-- name: CreateEmbedVideo :one

INSERT INTO videos (workspace_id, owner_id, kind, platform, status, title, author, url, embed_id, thumbnail_url, verified_at)
VALUES ($1, $2, 'embed', $3, 'ready', $4, $5, $6, $7, $8, now())
ON CONFLICT (workspace_id, owner_id, platform, embed_id) WHERE kind = 'embed'
DO UPDATE SET title = excluded.title, author = excluded.author, url = excluded.url,
    thumbnail_url = excluded.thumbnail_url, status = 'ready', verified_at = now(), updated_at = now()
RETURNING id, (xmax = 0)::boolean AS created
`

type CreateEmbedVideoParams struct {
	WorkspaceID  uuid.UUID
	OwnerID      uuid.UUID
	Platform     string
	Title        string
	Author       string
	URL          *string
	EmbedID      *string
	ThumbnailURL *string
}

type CreateEmbedVideoRow struct {
	ID      uuid.UUID
	Created bool
}

// Queries of the media module. Every query filters by workspace_id, besides
// the RLS (which shows the user their videos and the shared ones in the
// workspace).
// Pasting the same video again returns the existing one (xmax <> 0 on the upsert).
func (q *Queries) CreateEmbedVideo(ctx context.Context, arg CreateEmbedVideoParams) (CreateEmbedVideoRow, error) {
	row := q.db.QueryRow(ctx, createEmbedVideo,
		arg.WorkspaceID,
		arg.OwnerID,
		arg.Platform,
		arg.Title,
		arg.Author,
		arg.URL,
		arg.EmbedID,
		arg.ThumbnailURL,
	)
	var i CreateEmbedVideoRow
	err := row.Scan(&i.ID, &i.Created)
	return i, err
}

const createUploadVideo = `-- name: CreateUploadVideo :one
INSERT INTO videos (id, workspace_id, owner_id, kind, platform, status, title, storage_key, upload_id,
                    file_name, content_type, size_bytes, usage_rights_at)
VALUES ($1, $2, $3, 'upload', 'upload', 'uploading', $4, $5, $6,
        $7, $8, $9, now())
RETURNING id, workspace_id, owner_id, kind, platform, status, title, author, shared, url, embed_id, thumbnail_url, verified_at, storage_key, upload_id, file_name, content_type, size_bytes, duration_s, width, height, usage_rights_at, created_at, updated_at
`

type CreateUploadVideoParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	OwnerID     uuid.UUID
	Title       string
	StorageKey  *string
	UploadID    *string
	FileName    *string
	ContentType *string
	SizeBytes   int64
}

func (q *Queries) CreateUploadVideo(ctx context.Context, arg CreateUploadVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, createUploadVideo,
		arg.ID,
		arg.WorkspaceID,
		arg.OwnerID,
		arg.Title,
		arg.StorageKey,
		arg.UploadID,
		arg.FileName,
		arg.ContentType,
		arg.SizeBytes,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.OwnerID,
		&i.Kind,
		&i.Platform,
		&i.Status,
		&i.Title,
		&i.Author,
		&i.Shared,
		&i.URL,
		&i.EmbedID,
		&i.ThumbnailURL,
		&i.VerifiedAt,
		&i.StorageKey,
		&i.UploadID,
		&i.FileName,
		&i.ContentType,
		&i.SizeBytes,
		&i.DurationS,
		&i.Width,
		&i.Height,
		&i.UsageRightsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteVideo = `-- name: DeleteVideo :execrows
DELETE FROM videos WHERE id = $1 AND workspace_id = $2 AND owner_id = $3
`

type DeleteVideoParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	OwnerID     uuid.UUID
}

func (q *Queries) DeleteVideo(ctx context.Context, arg DeleteVideoParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVideo, arg.ID, arg.WorkspaceID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const linkVideo = `-- name: LinkVideo :execrows
INSERT INTO video_links (video_id, workspace_id, owner_id, target_kind, target_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
`

type LinkVideoParams struct {
	VideoID     uuid.UUID
	WorkspaceID uuid.UUID
	OwnerID     uuid.UUID
	TargetKind  VideoTarget
	TargetID    uuid.UUID
}

func (q *Queries) LinkVideo(ctx context.Context, arg LinkVideoParams) (int64, error) {
	result, err := q.db.Exec(ctx, linkVideo,
		arg.VideoID,
		arg.WorkspaceID,
		arg.OwnerID,
		arg.TargetKind,
		arg.TargetID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const linksOfVideos = `-- name: LinksOfVideos :many
SELECT video_id, target_kind, target_id FROM video_links
WHERE workspace_id = $1 AND video_id = ANY($2::uuid[])
ORDER BY created_at
`

type LinksOfVideosParams struct {
	WorkspaceID uuid.UUID
	VideoIds    []uuid.UUID
}

type LinksOfVideosRow struct {
	VideoID    uuid.UUID
	TargetKind VideoTarget
	TargetID   uuid.UUID
}

func (q *Queries) LinksOfVideos(ctx context.Context, arg LinksOfVideosParams) ([]LinksOfVideosRow, error) {
	rows, err := q.db.Query(ctx, linksOfVideos, arg.WorkspaceID, arg.VideoIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LinksOfVideosRow
	for rows.Next() {
		var i LinksOfVideosRow
		if err := rows.Scan(&i.VideoID, &i.TargetKind, &i.TargetID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockOwnVideo = `-- name: LockOwnVideo :one
SELECT id, workspace_id, owner_id, kind, platform, status, title, author, shared, url, embed_id, thumbnail_url, verified_at, storage_key, upload_id, file_name, content_type, size_bytes, duration_s, width, height, usage_rights_at, created_at, updated_at FROM videos WHERE id = $1 AND workspace_id = $2 AND owner_id = $3 FOR UPDATE
`

type LockOwnVideoParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	OwnerID     uuid.UUID
}

func (q *Queries) LockOwnVideo(ctx context.Context, arg LockOwnVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, lockOwnVideo, arg.ID, arg.WorkspaceID, arg.OwnerID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.OwnerID,
		&i.Kind,
		&i.Platform,
		&i.Status,
		&i.Title,
		&i.Author,
		&i.Shared,
		&i.URL,
		&i.EmbedID,
		&i.ThumbnailURL,
		&i.VerifiedAt,
		&i.StorageKey,
		&i.UploadID,
		&i.FileName,
		&i.ContentType,
		&i.SizeBytes,
		&i.DurationS,
		&i.Width,
		&i.Height,
		&i.UsageRightsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markEmbedRevalidated = `-- name: MarkEmbedRevalidated :exec
UPDATE videos SET status = $1, title = coalesce($2, title),
    author = coalesce($3, author), thumbnail_url = coalesce($4, thumbnail_url),
    verified_at = now(), updated_at = now()
WHERE id = $5 AND workspace_id = $6 AND owner_id = $7
`

type MarkEmbedRevalidatedParams struct {
	Status       VideoStatus
	Title        *string
	Author       *string
	ThumbnailURL *string
	ID           uuid.UUID
	WorkspaceID  uuid.UUID
	OwnerID      uuid.UUID
}

func (q *Queries) MarkEmbedRevalidated(ctx context.Context, arg MarkEmbedRevalidatedParams) error {
	_, err := q.db.Exec(ctx, markEmbedRevalidated,
		arg.Status,
		arg.Title,
		arg.Author,
		arg.ThumbnailURL,
		arg.ID,
		arg.WorkspaceID,
		arg.OwnerID,
	)
	return err
}

const markVideoProcessed = `-- name: MarkVideoProcessed :exec
UPDATE videos SET status = 'ready', duration_s = $1, width = $2, height = $3, updated_at = now()
WHERE id = $4 AND workspace_id = $5 AND owner_id = $6
`

type MarkVideoProcessedParams struct {
	DurationS   *int32
	Width       *int32
	Height      *int32
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	OwnerID     uuid.UUID
}

func (q *Queries) MarkVideoProcessed(ctx context.Context, arg MarkVideoProcessedParams) error {
	_, err := q.db.Exec(ctx, markVideoProcessed,
		arg.DurationS,
		arg.Width,
		arg.Height,
		arg.ID,
		arg.WorkspaceID,
		arg.OwnerID,
	)
	return err
}

const markVideoUploaded = `-- name: MarkVideoUploaded :exec
UPDATE videos SET status = 'processing', upload_id = NULL, size_bytes = $1, updated_at = now()
WHERE id = $2 AND workspace_id = $3 AND owner_id = $4
`

type MarkVideoUploadedParams struct {
	SizeBytes   int64
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	OwnerID     uuid.UUID
}

func (q *Queries) MarkVideoUploaded(ctx context.Context, arg MarkVideoUploadedParams) error {
	_, err := q.db.Exec(ctx, markVideoUploaded,
		arg.SizeBytes,
		arg.ID,
		arg.WorkspaceID,
		arg.OwnerID,
	)
	return err
}

const renameVideo = `-- name: RenameVideo :execrows
UPDATE videos SET title = $1, updated_at = now()
WHERE id = $2 AND workspace_id = $3 AND owner_id = $4
`

type RenameVideoParams struct {
	Title       string
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	OwnerID     uuid.UUID
}

func (q *Queries) RenameVideo(ctx context.Context, arg RenameVideoParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameVideo,
		arg.Title,
		arg.ID,
		arg.WorkspaceID,
		arg.OwnerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setVideoStatus = `-- name: SetVideoStatus :exec
UPDATE videos SET status = $1, updated_at = now()
WHERE id = $2 AND workspace_id = $3 AND owner_id = $4
`

type SetVideoStatusParams struct {
	Status      VideoStatus
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	OwnerID     uuid.UUID
}

func (q *Queries) SetVideoStatus(ctx context.Context, arg SetVideoStatusParams) error {
	_, err := q.db.Exec(ctx, setVideoStatus,
		arg.Status,
		arg.ID,
		arg.WorkspaceID,
		arg.OwnerID,
	)
	return err
}

const shareVideo = `-- name: ShareVideo :execrows
UPDATE videos SET shared = $1, updated_at = now()
WHERE id = $2 AND workspace_id = $3 AND owner_id = $4
`

type ShareVideoParams struct {
	Shared      bool
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	OwnerID     uuid.UUID
}

func (q *Queries) ShareVideo(ctx context.Context, arg ShareVideoParams) (int64, error) {
	result, err := q.db.Exec(ctx, shareVideo,
		arg.Shared,
		arg.ID,
		arg.WorkspaceID,
		arg.OwnerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unlinkVideo = `-- name: UnlinkVideo :execrows
DELETE FROM video_links
WHERE workspace_id = $1 AND video_id = $2 AND target_kind = $3 AND target_id = $4
`

type UnlinkVideoParams struct {
	WorkspaceID uuid.UUID
	VideoID     uuid.UUID
	TargetKind  VideoTarget
	TargetID    uuid.UUID
}

func (q *Queries) UnlinkVideo(ctx context.Context, arg UnlinkVideoParams) (int64, error) {
	result, err := q.db.Exec(ctx, unlinkVideo,
		arg.WorkspaceID,
		arg.VideoID,
		arg.TargetKind,
		arg.TargetID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unlinkVideoTarget = `-- name: UnlinkVideoTarget :exec
DELETE FROM video_links WHERE workspace_id = $1 AND target_kind = $2 AND target_id = $3
`

type UnlinkVideoTargetParams struct {
	WorkspaceID uuid.UUID
	TargetKind  VideoTarget
	TargetID    uuid.UUID
}

func (q *Queries) UnlinkVideoTarget(ctx context.Context, arg UnlinkVideoTargetParams) error {
	_, err := q.db.Exec(ctx, unlinkVideoTarget, arg.WorkspaceID, arg.TargetKind, arg.TargetID)
	return err
}

const videoByID = `-- name: VideoByID :one
SELECT id, workspace_id, owner_id, kind, platform, status, title, author, shared, url, embed_id, thumbnail_url, verified_at, storage_key, upload_id, file_name, content_type, size_bytes, duration_s, width, height, usage_rights_at, created_at, updated_at FROM videos WHERE id = $1 AND workspace_id = $2
`

type VideoByIDParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) VideoByID(ctx context.Context, arg VideoByIDParams) (Video, error) {
	row := q.db.QueryRow(ctx, videoByID, arg.ID, arg.WorkspaceID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.OwnerID,
		&i.Kind,
		&i.Platform,
		&i.Status,
		&i.Title,
		&i.Author,
		&i.Shared,
		&i.URL,
		&i.EmbedID,
		&i.ThumbnailURL,
		&i.VerifiedAt,
		&i.StorageKey,
		&i.UploadID,
		&i.FileName,
		&i.ContentType,
		&i.SizeBytes,
		&i.DurationS,
		&i.Width,
		&i.Height,
		&i.UsageRightsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const videoUsage = `-- name: VideoUsage :one
SELECT coalesce((SELECT bytes FROM video_usage WHERE workspace_id = $1), 0)::bigint
`

func (q *Queries) VideoUsage(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, videoUsage, workspaceID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const videosForTargets = `-- name: VideosForTargets :many
SELECT v.id, v.workspace_id, v.owner_id, v.kind, v.platform, v.status, v.title, v.author, v.shared, v.url, v.embed_id, v.thumbnail_url, v.verified_at, v.storage_key, v.upload_id, v.file_name, v.content_type, v.size_bytes, v.duration_s, v.width, v.height, v.usage_rights_at, v.created_at, v.updated_at, vl.target_id FROM video_links vl
JOIN videos v ON v.id = vl.video_id AND v.workspace_id = vl.workspace_id
WHERE vl.workspace_id = $1
  AND vl.target_kind = $2
  AND vl.target_id = ANY($3::uuid[])
ORDER BY vl.created_at, v.id
`

type VideosForTargetsParams struct {
	WorkspaceID uuid.UUID
	TargetKind  VideoTarget
	TargetIds   []uuid.UUID
}

type VideosForTargetsRow struct {
	Video    Video
	TargetID uuid.UUID
}

// The videos linked to any of these targets, with the target of each link.
func (q *Queries) VideosForTargets(ctx context.Context, arg VideosForTargetsParams) ([]VideosForTargetsRow, error) {
	rows, err := q.db.Query(ctx, videosForTargets, arg.WorkspaceID, arg.TargetKind, arg.TargetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VideosForTargetsRow
	for rows.Next() {
		var i VideosForTargetsRow
		if err := rows.Scan(
			&i.Video.ID,
			&i.Video.WorkspaceID,
			&i.Video.OwnerID,
			&i.Video.Kind,
			&i.Video.Platform,
			&i.Video.Status,
			&i.Video.Title,
			&i.Video.Author,
			&i.Video.Shared,
			&i.Video.URL,
			&i.Video.EmbedID,
			&i.Video.ThumbnailURL,
			&i.Video.VerifiedAt,
			&i.Video.StorageKey,
			&i.Video.UploadID,
			&i.Video.FileName,
			&i.Video.ContentType,
			&i.Video.SizeBytes,
			&i.Video.DurationS,
			&i.Video.Width,
			&i.Video.Height,
			&i.Video.UsageRightsAt,
			&i.Video.CreatedAt,
			&i.Video.UpdatedAt,
			&i.TargetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workspaceVideos = `-- name: WorkspaceVideos :many
SELECT id, workspace_id, owner_id, kind, platform, status, title, author, shared, url, embed_id, thumbnail_url, verified_at, storage_key, upload_id, file_name, content_type, size_bytes, duration_s, width, height, usage_rights_at, created_at, updated_at FROM videos
WHERE workspace_id = $1
  AND (NOT $2::boolean OR owner_id = $3)
ORDER BY created_at DESC, id
LIMIT 500
`

type WorkspaceVideosParams struct {
	WorkspaceID uuid.UUID
	OnlyMine    bool
	OwnerID     uuid.UUID
}

// The videos the user sees in the workspace: theirs and the shared ones.
func (q *Queries) WorkspaceVideos(ctx context.Context, arg WorkspaceVideosParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, workspaceVideos, arg.WorkspaceID, arg.OnlyMine, arg.OwnerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.OwnerID,
			&i.Kind,
			&i.Platform,
			&i.Status,
			&i.Title,
			&i.Author,
			&i.Shared,
			&i.URL,
			&i.EmbedID,
			&i.ThumbnailURL,
			&i.VerifiedAt,
			&i.StorageKey,
			&i.UploadID,
			&i.FileName,
			&i.ContentType,
			&i.SizeBytes,
			&i.DurationS,
			&i.Width,
			&i.Height,
			&i.UsageRightsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
