// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Channel string

const (
	ChannelInstagram Channel = "instagram"
	ChannelTiktok    Channel = "tiktok"
	ChannelWhatsapp  Channel = "whatsapp"
	ChannelOther     Channel = "other"
)

func (e *Channel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Channel(s)
	case string:
		*e = Channel(s)
	default:
		return fmt.Errorf("unsupported scan type for Channel: %T", src)
	}
	return nil
}

type NullChannel struct {
	Channel Channel
	Valid   bool // Valid is true if Channel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChannel) Scan(value interface{}) error {
	if value == nil {
		ns.Channel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Channel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Channel), nil
}

type CredentialStatus string

const (
	CredentialStatusConnected CredentialStatus = "connected"
	CredentialStatusInvalid   CredentialStatus = "invalid"
	CredentialStatusExpired   CredentialStatus = "expired"
)

func (e *CredentialStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CredentialStatus(s)
	case string:
		*e = CredentialStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CredentialStatus: %T", src)
	}
	return nil
}

type NullCredentialStatus struct {
	CredentialStatus CredentialStatus
	Valid            bool // Valid is true if CredentialStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCredentialStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CredentialStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CredentialStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCredentialStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CredentialStatus), nil
}

type ItemStatus string

const (
	ItemStatusTesting   ItemStatus = "testing"
	ItemStatusWinner    ItemStatus = "winner"
	ItemStatusDiscarded ItemStatus = "discarded"
)

func (e *ItemStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ItemStatus(s)
	case string:
		*e = ItemStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ItemStatus: %T", src)
	}
	return nil
}

type NullItemStatus struct {
	ItemStatus ItemStatus
	Valid      bool // Valid is true if ItemStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullItemStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ItemStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ItemStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullItemStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ItemStatus), nil
}

type LinkOrigin string

const (
	LinkOriginAuto   LinkOrigin = "auto"
	LinkOriginManual LinkOrigin = "manual"
)

func (e *LinkOrigin) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LinkOrigin(s)
	case string:
		*e = LinkOrigin(s)
	default:
		return fmt.Errorf("unsupported scan type for LinkOrigin: %T", src)
	}
	return nil
}

type NullLinkOrigin struct {
	LinkOrigin LinkOrigin
	Valid      bool // Valid is true if LinkOrigin is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLinkOrigin) Scan(value interface{}) error {
	if value == nil {
		ns.LinkOrigin, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LinkOrigin.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLinkOrigin) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LinkOrigin), nil
}

type LinkStatus string

const (
	LinkStatusPending    LinkStatus = "pending"
	LinkStatusGenerating LinkStatus = "generating"
	LinkStatusReady      LinkStatus = "ready"
	LinkStatusFailed     LinkStatus = "failed"
)

func (e *LinkStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LinkStatus(s)
	case string:
		*e = LinkStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LinkStatus: %T", src)
	}
	return nil
}

type NullLinkStatus struct {
	LinkStatus LinkStatus
	Valid      bool // Valid is true if LinkStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLinkStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LinkStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LinkStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLinkStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LinkStatus), nil
}

type MemberRole string

const (
	MemberRoleOwner     MemberRole = "owner"
	MemberRoleMentor    MemberRole = "mentor"
	MemberRoleAffiliate MemberRole = "affiliate"
)

func (e *MemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberRole(s)
	case string:
		*e = MemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberRole: %T", src)
	}
	return nil
}

type NullMemberRole struct {
	MemberRole MemberRole
	Valid      bool // Valid is true if MemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.MemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberRole), nil
}

type OrderStatus string

const (
	OrderStatusUnpaid    OrderStatus = "unpaid"
	OrderStatusPending   OrderStatus = "pending"
	OrderStatusCompleted OrderStatus = "completed"
	OrderStatusCancelled OrderStatus = "cancelled"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus
	Valid       bool // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type Source string

const (
	SourceShopee Source = "shopee"
)

func (e *Source) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Source(s)
	case string:
		*e = Source(s)
	default:
		return fmt.Errorf("unsupported scan type for Source: %T", src)
	}
	return nil
}

type NullSource struct {
	Source Source
	Valid  bool // Valid is true if Source is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSource) Scan(value interface{}) error {
	if value == nil {
		ns.Source, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Source.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Source), nil
}

type SubscriptionStatus string

const (
	SubscriptionStatusPending   SubscriptionStatus = "pending"
	SubscriptionStatusActive    SubscriptionStatus = "active"
	SubscriptionStatusOverdue   SubscriptionStatus = "overdue"
	SubscriptionStatusCancelled SubscriptionStatus = "cancelled"
)

func (e *SubscriptionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionStatus(s)
	case string:
		*e = SubscriptionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionStatus: %T", src)
	}
	return nil
}

type NullSubscriptionStatus struct {
	SubscriptionStatus SubscriptionStatus
	Valid              bool // Valid is true if SubscriptionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionStatus), nil
}

type VideoKind string

const (
	VideoKindEmbed  VideoKind = "embed"
	VideoKindUpload VideoKind = "upload"
)

func (e *VideoKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VideoKind(s)
	case string:
		*e = VideoKind(s)
	default:
		return fmt.Errorf("unsupported scan type for VideoKind: %T", src)
	}
	return nil
}

type NullVideoKind struct {
	VideoKind VideoKind
	Valid     bool // Valid is true if VideoKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVideoKind) Scan(value interface{}) error {
	if value == nil {
		ns.VideoKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VideoKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVideoKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VideoKind), nil
}

type VideoStatus string

const (
	VideoStatusUploading   VideoStatus = "uploading"
	VideoStatusProcessing  VideoStatus = "processing"
	VideoStatusReady       VideoStatus = "ready"
	VideoStatusFailed      VideoStatus = "failed"
	VideoStatusUnavailable VideoStatus = "unavailable"
)

func (e *VideoStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VideoStatus(s)
	case string:
		*e = VideoStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for VideoStatus: %T", src)
	}
	return nil
}

type NullVideoStatus struct {
	VideoStatus VideoStatus
	Valid       bool // Valid is true if VideoStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVideoStatus) Scan(value interface{}) error {
	if value == nil {
		ns.VideoStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VideoStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVideoStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VideoStatus), nil
}

type VideoTarget string

const (
	VideoTargetProduct VideoTarget = "product"
	VideoTargetList    VideoTarget = "list"
)

func (e *VideoTarget) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VideoTarget(s)
	case string:
		*e = VideoTarget(s)
	default:
		return fmt.Errorf("unsupported scan type for VideoTarget: %T", src)
	}
	return nil
}

type NullVideoTarget struct {
	VideoTarget VideoTarget
	Valid       bool // Valid is true if VideoTarget is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVideoTarget) Scan(value interface{}) error {
	if value == nil {
		ns.VideoTarget, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VideoTarget.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVideoTarget) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VideoTarget), nil
}

type WorkspaceKind string

const (
	WorkspaceKindPersonal   WorkspaceKind = "personal"
	WorkspaceKindMentorship WorkspaceKind = "mentorship"
)

func (e *WorkspaceKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkspaceKind(s)
	case string:
		*e = WorkspaceKind(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkspaceKind: %T", src)
	}
	return nil
}

type NullWorkspaceKind struct {
	WorkspaceKind WorkspaceKind
	Valid         bool // Valid is true if WorkspaceKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkspaceKind) Scan(value interface{}) error {
	if value == nil {
		ns.WorkspaceKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkspaceKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkspaceKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkspaceKind), nil
}

type AuthAccount struct {
	ID              uuid.UUID
	Email           string
	Name            string
	PasswordHash    string
	EmailVerifiedAt *time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type AuthSession struct {
	TokenHash  []byte
	AccountID  uuid.UUID
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
}

type AuthToken struct {
	TokenHash []byte
	AccountID uuid.UUID
	Purpose   string
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type BillingEvent struct {
	Provider    string
	EventID     string
	WorkspaceID uuid.UUID
	Kind        string
	ReceivedAt  time.Time
}

type Category struct {
	Source    Source
	ID        int64
	Name      string
	Monitored bool
}

type ChannelLink struct {
	ItemID      uuid.UUID
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Channel     Channel
	SubID       string
	URL         string
	GeneratedAt time.Time
}

type Collection struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Name        string
	CreatedAt   time.Time
}

type CollectionItem struct {
	CollectionID uuid.UUID
	ItemID       uuid.UUID
	WorkspaceID  uuid.UUID
	UserID       uuid.UUID
	AddedAt      time.Time
}

type Conversion struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	WorkspaceID     uuid.UUID
	Source          string
	ConversionID    int64
	OrderID         string
	ItemID          int64
	ModelID         int64
	ProductID       *uuid.UUID
	ItemName        string
	ShopName        string
	SubID           string
	Channel         *Channel
	Status          OrderStatus
	Quantity        int32
	AmountCents     int64
	CommissionCents int64
	OccurredAt      time.Time
	ClickedAt       *time.Time
	SyncedAt        time.Time
}

type ConversionSync struct {
	UserID      uuid.UUID
	Status      string
	RequestedAt time.Time
	FinishedAt  *time.Time
	Conversions int32
	Error       *string
}

type CuratedList struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	AuthorID    uuid.UUID
	Title       string
	Description string
	PublishedAt *time.Time
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type CuratedListItem struct {
	ListID      uuid.UUID
	WorkspaceID uuid.UUID
	ProductID   uuid.UUID
	Comment     string
	Position    int32
}

type Invite struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Email       *string
	TokenHash   []byte
	ExpiresAt   time.Time
	UsedBy      *uuid.UUID
	UsedAt      *time.Time
	RevokedAt   *time.Time
	CreatedBy   uuid.UUID
	CreatedAt   time.Time
}

type ListImport struct {
	ListID      uuid.UUID
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	ProductID   uuid.UUID
	ImportedAt  time.Time
}

type Member struct {
	WorkspaceID   uuid.UUID
	UserID        uuid.UUID
	Role          MemberRole
	SharesResults bool
	JoinedAt      time.Time
}

type Notification struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Kind        string
	Key         string
	Title       string
	Body        string
	URL         string
	CreatedAt   time.Time
	ReadAt      *time.Time
	EmailedAt   *time.Time
	PushedAt    *time.Time
}

type NotificationPreference struct {
	UserID    uuid.UUID
	Email     bool
	UpdatedAt time.Time
}

type PlanLimit struct {
	Plan  string
	Key   string
	Value int64
}

type Product struct {
	ID            uuid.UUID
	Source        Source
	ItemID        int64
	ShopID        int64
	ShopName      string
	Name          string
	ImageURL      *string
	CategoryID    *int64
	Categories    []int64
	URL           string
	MinPriceCents int64
	MaxPriceCents int64
	CommissionBp  int32
	Sales         int64
	Rating        *float64
	CollectedAt   time.Time
	CreatedAt     time.Time
}

type ProductSnapshot struct {
	ProductID     uuid.UUID
	CollectedAt   time.Time
	MinPriceCents int64
	MaxPriceCents int64
	CommissionBp  int32
	Sales         int64
	Rating        *float64
}

type ProductSnapshotsDefault struct {
	ProductID     uuid.UUID
	CollectedAt   time.Time
	MinPriceCents int64
	MaxPriceCents int64
	CommissionBp  int32
	Sales         int64
	Rating        *float64
}

type PushSubscription struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Endpoint  string
	P256dh    string
	Auth      string
	CreatedAt time.Time
}

type SavedItem struct {
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
	UserID        uuid.UUID
	ProductID     uuid.UUID
	Title         string
	Description   string
	Notes         string
	Tags          []string
	Status        ItemStatus
	AffiliateLink *string
	LinkOrigin    LinkOrigin
	LinkStatus    LinkStatus
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type ShopeeCredential struct {
	UserID          uuid.UUID
	AppID           string
	EncryptedSecret []byte
	EncryptedDek    []byte
	KekID           string
	Status          CredentialStatus
	VerifiedAt      time.Time
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Subscription struct {
	WorkspaceID        uuid.UUID
	Provider           string
	ExternalCustomerID string
	ExternalID         string
	Status             SubscriptionStatus
	Seats              int32
	AmountCents        int64
	NextDueDate        pgtype.Date
	PaymentURL         *string
	CreatedBy          uuid.UUID
	CreatedAt          time.Time
	UpdatedAt          time.Time
	CancelledAt        *time.Time
}

type Trend struct {
	ProductID            uuid.UUID
	ComputedAt           time.Time
	Score                float64
	EarningsPerSaleCents int64
	SalesGrowth7d        *int64
	Name                 string
	ShopName             string
	ImageURL             *string
	CategoryID           *int64
	Categories           []int64
	URL                  string
	MinPriceCents        int64
	MaxPriceCents        int64
	CommissionBp         int32
	Sales                int64
	Rating               *float64
	UpdatedAt            time.Time
	Search               interface{}
}

type User struct {
	ID            uuid.UUID
	AuthProvider  string
	AuthSubject   string
	Name          string
	Email         string
	EmailVerified bool
	CreatedAt     time.Time
}

type Video struct {
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
	OwnerID       uuid.UUID
	Kind          VideoKind
	Platform      string
	Status        VideoStatus
	Title         string
	Author        string
	Shared        bool
	URL           *string
	EmbedID       *string
	ThumbnailURL  *string
	VerifiedAt    *time.Time
	StorageKey    *string
	UploadID      *string
	FileName      *string
	ContentType   *string
	SizeBytes     int64
	DurationS     *int32
	Width         *int32
	Height        *int32
	UsageRightsAt *time.Time
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type VideoLink struct {
	VideoID     uuid.UUID
	WorkspaceID uuid.UUID
	OwnerID     uuid.UUID
	TargetKind  VideoTarget
	TargetID    uuid.UUID
	CreatedAt   time.Time
}

type VideoUsage struct {
	WorkspaceID uuid.UUID
	Bytes       int64
}

type Workspace struct {
	ID          uuid.UUID
	Kind        WorkspaceKind
	Name        string
	PhotoURL    *string
	OwnerID     uuid.UUID
	Plan        string
	AccessUntil time.Time
	PaidAt      *time.Time
	Seats       *int32
	CreatedAt   time.Time
}
