// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const countPushSubscriptions = `-- name: CountPushSubscriptions :one
SELECT count(*) FROM push_subscriptions WHERE user_id = $1
`

func (q *Queries) CountPushSubscriptions(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPushSubscriptions, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) FROM notifications
WHERE workspace_id = $1 AND user_id = $2 AND read_at IS NULL
`

type CountUnreadNotificationsParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) CountUnreadNotifications(ctx context.Context, arg CountUnreadNotificationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, arg.WorkspaceID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one

INSERT INTO notifications (workspace_id, user_id, kind, key, title, body, url)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (workspace_id, user_id, key) DO UPDATE SET key = excluded.key
RETURNING id, workspace_id, user_id, kind, key, title, body, url, created_at, read_at, emailed_at, pushed_at
`

type CreateNotificationParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Kind        string
	Key         string
	Title       string
	Body        string
	URL         string
}

// Queries of the notifications module. The inbox filters by workspace and
// user; push subscriptions and preferences, by user. RLS repeats the filters.
// Idempotent by key: repeating the delivery returns the same notification.
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.WorkspaceID,
		arg.UserID,
		arg.Kind,
		arg.Key,
		arg.Title,
		arg.Body,
		arg.URL,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.Kind,
		&i.Key,
		&i.Title,
		&i.Body,
		&i.URL,
		&i.CreatedAt,
		&i.ReadAt,
		&i.EmailedAt,
		&i.PushedAt,
	)
	return i, err
}

const deletePushSubscription = `-- name: DeletePushSubscription :execrows
DELETE FROM push_subscriptions WHERE user_id = $1 AND endpoint = $2
`

type DeletePushSubscriptionParams struct {
	UserID   uuid.UUID
	Endpoint string
}

func (q *Queries) DeletePushSubscription(ctx context.Context, arg DeletePushSubscriptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePushSubscription, arg.UserID, arg.Endpoint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET read_at = now()
WHERE workspace_id = $1 AND user_id = $2 AND read_at IS NULL
`

type MarkAllNotificationsReadParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, arg MarkAllNotificationsReadParams) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, arg.WorkspaceID, arg.UserID)
	return err
}

const markNotificationEmailed = `-- name: MarkNotificationEmailed :exec
UPDATE notifications SET emailed_at = now()
WHERE id = $1 AND workspace_id = $2 AND user_id = $3
`

type MarkNotificationEmailedParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) MarkNotificationEmailed(ctx context.Context, arg MarkNotificationEmailedParams) error {
	_, err := q.db.Exec(ctx, markNotificationEmailed, arg.ID, arg.WorkspaceID, arg.UserID)
	return err
}

const markNotificationPushed = `-- name: MarkNotificationPushed :exec
UPDATE notifications SET pushed_at = now()
WHERE id = $1 AND workspace_id = $2 AND user_id = $3
`

type MarkNotificationPushedParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) MarkNotificationPushed(ctx context.Context, arg MarkNotificationPushedParams) error {
	_, err := q.db.Exec(ctx, markNotificationPushed, arg.ID, arg.WorkspaceID, arg.UserID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :execrows
UPDATE notifications SET read_at = coalesce(read_at, now())
WHERE id = $1 AND workspace_id = $2 AND user_id = $3
`

type MarkNotificationReadParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const notificationInbox = `-- name: NotificationInbox :many
SELECT id, workspace_id, user_id, kind, key, title, body, url, created_at, read_at, emailed_at, pushed_at FROM notifications
WHERE workspace_id = $1 AND user_id = $2
ORDER BY created_at DESC, id
LIMIT $3
`

type NotificationInboxParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	MaxRows     int32
}

func (q *Queries) NotificationInbox(ctx context.Context, arg NotificationInboxParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, notificationInbox, arg.WorkspaceID, arg.UserID, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UserID,
			&i.Kind,
			&i.Key,
			&i.Title,
			&i.Body,
			&i.URL,
			&i.CreatedAt,
			&i.ReadAt,
			&i.EmailedAt,
			&i.PushedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const notificationPreferencesByUser = `-- name: NotificationPreferencesByUser :one
SELECT user_id, email, updated_at FROM notification_preferences WHERE user_id = $1
`

func (q *Queries) NotificationPreferencesByUser(ctx context.Context, userID uuid.UUID) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, notificationPreferencesByUser, userID)
	var i NotificationPreference
	err := row.Scan(&i.UserID, &i.Email, &i.UpdatedAt)
	return i, err
}

const pushSubscriptionsByUser = `-- name: PushSubscriptionsByUser :many
SELECT id, user_id, endpoint, p256dh, auth, created_at FROM push_subscriptions WHERE user_id = $1 ORDER BY created_at, id
`

func (q *Queries) PushSubscriptionsByUser(ctx context.Context, userID uuid.UUID) ([]PushSubscription, error) {
	rows, err := q.db.Query(ctx, pushSubscriptionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushSubscription
	for rows.Next() {
		var i PushSubscription
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveNotificationPreferences = `-- name: SaveNotificationPreferences :exec
INSERT INTO notification_preferences (user_id, email)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE SET email = excluded.email, updated_at = now()
`

type SaveNotificationPreferencesParams struct {
	UserID uuid.UUID
	Email  bool
}

func (q *Queries) SaveNotificationPreferences(ctx context.Context, arg SaveNotificationPreferencesParams) error {
	_, err := q.db.Exec(ctx, saveNotificationPreferences, arg.UserID, arg.Email)
	return err
}

const savePushSubscription = `-- name: SavePushSubscription :exec
INSERT INTO push_subscriptions (user_id, endpoint, p256dh, auth)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, endpoint) DO UPDATE SET p256dh = excluded.p256dh, auth = excluded.auth
`

type SavePushSubscriptionParams struct {
	UserID   uuid.UUID
	Endpoint string
	P256dh   string
	Auth     string
}

func (q *Queries) SavePushSubscription(ctx context.Context, arg SavePushSubscriptionParams) error {
	_, err := q.db.Exec(ctx, savePushSubscription,
		arg.UserID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
	)
	return err
}
