// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const categoryNames = `-- name: CategoryNames :many
SELECT id, name FROM categories WHERE source = $1 AND id = ANY ($2::bigint[])
`

type CategoryNamesParams struct {
	Source Source
	Ids    []int64
}

type CategoryNamesRow struct {
	ID   int64
	Name string
}

func (q *Queries) CategoryNames(ctx context.Context, arg CategoryNamesParams) ([]CategoryNamesRow, error) {
	rows, err := q.db.Query(ctx, categoryNames, arg.Source, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoryNamesRow
	for rows.Next() {
		var i CategoryNamesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ensureSnapshotPartition = `-- name: EnsureSnapshotPartition :exec
SELECT ensure_snapshot_partition(($1::timestamptz)::date)
`

func (q *Queries) EnsureSnapshotPartition(ctx context.Context, month time.Time) error {
	_, err := q.db.Exec(ctx, ensureSnapshotPartition, month)
	return err
}

const monitoredCategories = `-- name: MonitoredCategories :many
SELECT id FROM categories WHERE source = $1 AND monitored ORDER BY id
`

func (q *Queries) MonitoredCategories(ctx context.Context, source Source) ([]int64, error) {
	rows, err := q.db.Query(ctx, monitoredCategories, source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productByID = `-- name: ProductByID :one
SELECT id, source, item_id, shop_id, shop_name, name, image_url, category_id, categories, url, min_price_cents, max_price_cents, commission_bp, sales, rating, collected_at, created_at FROM products WHERE id = $1
`

func (q *Queries) ProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, productByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ItemID,
		&i.ShopID,
		&i.ShopName,
		&i.Name,
		&i.ImageURL,
		&i.CategoryID,
		&i.Categories,
		&i.URL,
		&i.MinPriceCents,
		&i.MaxPriceCents,
		&i.CommissionBp,
		&i.Sales,
		&i.Rating,
		&i.CollectedAt,
		&i.CreatedAt,
	)
	return i, err
}

const productByItem = `-- name: ProductByItem :one
SELECT id, source, item_id, shop_id, shop_name, name, image_url, category_id, categories, url, min_price_cents, max_price_cents, commission_bp, sales, rating, collected_at, created_at FROM products WHERE source = $1 AND item_id = $2
`

type ProductByItemParams struct {
	Source Source
	ItemID int64
}

func (q *Queries) ProductByItem(ctx context.Context, arg ProductByItemParams) (Product, error) {
	row := q.db.QueryRow(ctx, productByItem, arg.Source, arg.ItemID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ItemID,
		&i.ShopID,
		&i.ShopName,
		&i.Name,
		&i.ImageURL,
		&i.CategoryID,
		&i.Categories,
		&i.URL,
		&i.MinPriceCents,
		&i.MaxPriceCents,
		&i.CommissionBp,
		&i.Sales,
		&i.Rating,
		&i.CollectedAt,
		&i.CreatedAt,
	)
	return i, err
}

const productHistory = `-- name: ProductHistory :many
SELECT collected_at, min_price_cents, max_price_cents, commission_bp, sales, rating
FROM product_snapshots
WHERE product_id = $1 AND collected_at >= $2
ORDER BY collected_at
`

type ProductHistoryParams struct {
	ProductID uuid.UUID
	Since     time.Time
}

type ProductHistoryRow struct {
	CollectedAt   time.Time
	MinPriceCents int64
	MaxPriceCents int64
	CommissionBp  int32
	Sales         int64
	Rating        *float64
}

func (q *Queries) ProductHistory(ctx context.Context, arg ProductHistoryParams) ([]ProductHistoryRow, error) {
	rows, err := q.db.Query(ctx, productHistory, arg.ProductID, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductHistoryRow
	for rows.Next() {
		var i ProductHistoryRow
		if err := rows.Scan(
			&i.CollectedAt,
			&i.MinPriceCents,
			&i.MaxPriceCents,
			&i.CommissionBp,
			&i.Sales,
			&i.Rating,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productIDByItem = `-- name: ProductIDByItem :one
SELECT id FROM products WHERE source = $1 AND item_id = $2
`

type ProductIDByItemParams struct {
	Source Source
	ItemID int64
}

func (q *Queries) ProductIDByItem(ctx context.Context, arg ProductIDByItemParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, productIDByItem, arg.Source, arg.ItemID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const productsByIDs = `-- name: ProductsByIDs :many
SELECT id, source, item_id, shop_id, shop_name, name, image_url, category_id, categories, url, min_price_cents, max_price_cents, commission_bp, sales, rating, collected_at, created_at FROM products WHERE id = ANY ($1::uuid[])
`

func (q *Queries) ProductsByIDs(ctx context.Context, ids []uuid.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, productsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ItemID,
			&i.ShopID,
			&i.ShopName,
			&i.Name,
			&i.ImageURL,
			&i.CategoryID,
			&i.Categories,
			&i.URL,
			&i.MinPriceCents,
			&i.MaxPriceCents,
			&i.CommissionBp,
			&i.Sales,
			&i.Rating,
			&i.CollectedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productsForTrends = `-- name: ProductsForTrends :many
SELECT
    p.id, p.source, p.item_id, p.name, p.shop_name, p.image_url, p.category_id, p.categories, p.url,
    p.min_price_cents, p.max_price_cents, p.commission_bp, p.sales, p.rating, p.collected_at,
    COALESCE(before.sales, after.sales)::bigint AS base_sales,
    COALESCE(before.collected_at, after.collected_at)::timestamptz AS base_collected_at
FROM products p
LEFT JOIN LATERAL (
    SELECT s.sales, s.collected_at FROM product_snapshots s
    WHERE s.product_id = p.id
      AND s.collected_at BETWEEN p.collected_at - interval '14 days' AND p.collected_at - interval '7 days'
    ORDER BY s.collected_at DESC
    LIMIT 1
) before ON true
LEFT JOIN LATERAL (
    SELECT s.sales, s.collected_at FROM product_snapshots s
    WHERE s.product_id = p.id AND s.collected_at > p.collected_at - interval '7 days'
    ORDER BY s.collected_at
    LIMIT 1
) after ON true
WHERE p.collected_at >= $1
`

type ProductsForTrendsRow struct {
	ID              uuid.UUID
	Source          Source
	ItemID          int64
	Name            string
	ShopName        string
	ImageURL        *string
	CategoryID      *int64
	Categories      []int64
	URL             string
	MinPriceCents   int64
	MaxPriceCents   int64
	CommissionBp    int32
	Sales           int64
	Rating          *float64
	CollectedAt     time.Time
	BaseSales       int64
	BaseCollectedAt time.Time
}

// Current data of each product collected since @since and the baseline to
// measure its growth: the latest snapshot 7 to 14 days old or, while there is
// none, the oldest of the last 7 days.
func (q *Queries) ProductsForTrends(ctx context.Context, since time.Time) ([]ProductsForTrendsRow, error) {
	rows, err := q.db.Query(ctx, productsForTrends, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductsForTrendsRow
	for rows.Next() {
		var i ProductsForTrendsRow
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ItemID,
			&i.Name,
			&i.ShopName,
			&i.ImageURL,
			&i.CategoryID,
			&i.Categories,
			&i.URL,
			&i.MinPriceCents,
			&i.MaxPriceCents,
			&i.CommissionBp,
			&i.Sales,
			&i.Rating,
			&i.CollectedAt,
			&i.BaseSales,
			&i.BaseCollectedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCategory = `-- name: UpsertCategory :exec
INSERT INTO categories (source, id, name, monitored) VALUES ($1, $2, $3, $4)
ON CONFLICT (source, id) DO UPDATE SET name = excluded.name, monitored = excluded.monitored
`

type UpsertCategoryParams struct {
	Source    Source
	ID        int64
	Name      string
	Monitored bool
}

func (q *Queries) UpsertCategory(ctx context.Context, arg UpsertCategoryParams) error {
	_, err := q.db.Exec(ctx, upsertCategory,
		arg.Source,
		arg.ID,
		arg.Name,
		arg.Monitored,
	)
	return err
}
