// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shopee.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const connectedShopeeUsers = `-- name: ConnectedShopeeUsers :many
SELECT user_id FROM shopee_credentials WHERE status = 'connected' ORDER BY user_id
`

// Only the worker (owner role of the tables) uses it, to schedule the sync.
func (q *Queries) ConnectedShopeeUsers(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, connectedShopeeUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteShopeeCredential = `-- name: DeleteShopeeCredential :exec
DELETE FROM shopee_credentials WHERE user_id = $1
`

func (q *Queries) DeleteShopeeCredential(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteShopeeCredential, userID)
	return err
}

const saveShopeeCredential = `-- name: SaveShopeeCredential :one
INSERT INTO shopee_credentials (user_id, app_id, encrypted_secret, encrypted_dek, kek_id, status, verified_at)
VALUES ($1, $2, $3, $4, $5, 'connected', $6)
ON CONFLICT (user_id) DO UPDATE SET
    app_id = excluded.app_id,
    encrypted_secret = excluded.encrypted_secret,
    encrypted_dek = excluded.encrypted_dek,
    kek_id = excluded.kek_id,
    status = 'connected',
    verified_at = excluded.verified_at,
    updated_at = now()
RETURNING user_id, app_id, encrypted_secret, encrypted_dek, kek_id, status, verified_at, created_at, updated_at
`

type SaveShopeeCredentialParams struct {
	UserID          uuid.UUID
	AppID           string
	EncryptedSecret []byte
	EncryptedDek    []byte
	KekID           string
	VerifiedAt      time.Time
}

func (q *Queries) SaveShopeeCredential(ctx context.Context, arg SaveShopeeCredentialParams) (ShopeeCredential, error) {
	row := q.db.QueryRow(ctx, saveShopeeCredential,
		arg.UserID,
		arg.AppID,
		arg.EncryptedSecret,
		arg.EncryptedDek,
		arg.KekID,
		arg.VerifiedAt,
	)
	var i ShopeeCredential
	err := row.Scan(
		&i.UserID,
		&i.AppID,
		&i.EncryptedSecret,
		&i.EncryptedDek,
		&i.KekID,
		&i.Status,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setShopeeCredentialStatus = `-- name: SetShopeeCredentialStatus :execrows
UPDATE shopee_credentials
SET status = $2, verified_at = now(), updated_at = now()
WHERE user_id = $1
`

type SetShopeeCredentialStatusParams struct {
	UserID uuid.UUID
	Status CredentialStatus
}

func (q *Queries) SetShopeeCredentialStatus(ctx context.Context, arg SetShopeeCredentialStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setShopeeCredentialStatus, arg.UserID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const shopeeCredentialByUser = `-- name: ShopeeCredentialByUser :one
SELECT user_id, app_id, encrypted_secret, encrypted_dek, kek_id, status, verified_at, created_at, updated_at FROM shopee_credentials WHERE user_id = $1
`

func (q *Queries) ShopeeCredentialByUser(ctx context.Context, userID uuid.UUID) (ShopeeCredential, error) {
	row := q.db.QueryRow(ctx, shopeeCredentialByUser, userID)
	var i ShopeeCredential
	err := row.Scan(
		&i.UserID,
		&i.AppID,
		&i.EncryptedSecret,
		&i.EncryptedDek,
		&i.KekID,
		&i.Status,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
