// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trends.sql

package dbgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteStaleTrends = `-- name: DeleteStaleTrends :execrows
DELETE FROM trends WHERE computed_at < $1
`

func (q *Queries) DeleteStaleTrends(ctx context.Context, computedAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleTrends, computedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const radar = `-- name: Radar :many
SELECT
    product_id, name, image_url, shop_name, url, categories,
    min_price_cents, max_price_cents, commission_bp, earnings_per_sale_cents,
    sales, rating, score, sales_growth_7d, updated_at,
    count(*) OVER () AS total
FROM trends
WHERE ($1::bigint IS NULL OR $1::bigint = ANY (categories))
  AND ($2::bigint IS NULL OR min_price_cents >= $2::bigint)
  AND ($3::bigint IS NULL OR min_price_cents <= $3::bigint)
  AND ($4::integer IS NULL OR commission_bp >= $4::integer)
  AND ($5::numeric IS NULL OR rating >= $5::numeric)
  AND (
    $6::text IS NULL
    OR search @@ websearch_to_tsquery('portuguese', $6::text)
    OR name ILIKE $7::text ESCAPE '\'
    OR shop_name ILIKE $7::text ESCAPE '\'
  )
ORDER BY
    CASE WHEN $8::text = 'commission' THEN commission_bp END DESC,
    CASE WHEN $8::text = 'earnings' THEN earnings_per_sale_cents END DESC,
    CASE WHEN $8::text = 'sales' THEN sales END DESC,
    score DESC, sales DESC, product_id
LIMIT $10 OFFSET $9
`

type RadarParams struct {
	Category      *int64
	MinPrice      *int64
	MaxPrice      *int64
	MinCommission *int32
	MinRating     *float64
	Query         *string
	Pattern       *string
	Sort          string
	RowOffset     int32
	RowLimit      int32
}

type RadarRow struct {
	ProductID            uuid.UUID
	Name                 string
	ImageURL             *string
	ShopName             string
	URL                  string
	Categories           []int64
	MinPriceCents        int64
	MaxPriceCents        int64
	CommissionBp         int32
	EarningsPerSaleCents int64
	Sales                int64
	Rating               *float64
	Score                float64
	SalesGrowth7d        *int64
	UpdatedAt            time.Time
	Total                int64
}

func (q *Queries) Radar(ctx context.Context, arg RadarParams) ([]RadarRow, error) {
	rows, err := q.db.Query(ctx, radar,
		arg.Category,
		arg.MinPrice,
		arg.MaxPrice,
		arg.MinCommission,
		arg.MinRating,
		arg.Query,
		arg.Pattern,
		arg.Sort,
		arg.RowOffset,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RadarRow
	for rows.Next() {
		var i RadarRow
		if err := rows.Scan(
			&i.ProductID,
			&i.Name,
			&i.ImageURL,
			&i.ShopName,
			&i.URL,
			&i.Categories,
			&i.MinPriceCents,
			&i.MaxPriceCents,
			&i.CommissionBp,
			&i.EarningsPerSaleCents,
			&i.Sales,
			&i.Rating,
			&i.Score,
			&i.SalesGrowth7d,
			&i.UpdatedAt,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const radarCategories = `-- name: RadarCategories :many
SELECT category_id::bigint AS id, count(*) AS products
FROM trends
WHERE category_id IS NOT NULL
GROUP BY category_id
ORDER BY products DESC, category_id
`

type RadarCategoriesRow struct {
	ID       int64
	Products int64
}

func (q *Queries) RadarCategories(ctx context.Context) ([]RadarCategoriesRow, error) {
	rows, err := q.db.Query(ctx, radarCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RadarCategoriesRow
	for rows.Next() {
		var i RadarCategoriesRow
		if err := rows.Scan(&i.ID, &i.Products); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const radarItem = `-- name: RadarItem :one
SELECT
    product_id, name, image_url, shop_name, url, categories,
    min_price_cents, max_price_cents, commission_bp, earnings_per_sale_cents,
    sales, rating, score, sales_growth_7d, updated_at
FROM trends WHERE product_id = $1
`

type RadarItemRow struct {
	ProductID            uuid.UUID
	Name                 string
	ImageURL             *string
	ShopName             string
	URL                  string
	Categories           []int64
	MinPriceCents        int64
	MaxPriceCents        int64
	CommissionBp         int32
	EarningsPerSaleCents int64
	Sales                int64
	Rating               *float64
	Score                float64
	SalesGrowth7d        *int64
	UpdatedAt            time.Time
}

func (q *Queries) RadarItem(ctx context.Context, productID uuid.UUID) (RadarItemRow, error) {
	row := q.db.QueryRow(ctx, radarItem, productID)
	var i RadarItemRow
	err := row.Scan(
		&i.ProductID,
		&i.Name,
		&i.ImageURL,
		&i.ShopName,
		&i.URL,
		&i.Categories,
		&i.MinPriceCents,
		&i.MaxPriceCents,
		&i.CommissionBp,
		&i.EarningsPerSaleCents,
		&i.Sales,
		&i.Rating,
		&i.Score,
		&i.SalesGrowth7d,
		&i.UpdatedAt,
	)
	return i, err
}

const radarUpdatedAt = `-- name: RadarUpdatedAt :one
SELECT updated_at FROM trends ORDER BY updated_at DESC LIMIT 1
`

func (q *Queries) RadarUpdatedAt(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, radarUpdatedAt)
	var updated_at time.Time
	err := row.Scan(&updated_at)
	return updated_at, err
}
