// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contas.sql

package contasdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const atualizarWorkspace = `-- name: AtualizarWorkspace :one
UPDATE workspaces
SET nome = coalesce($1, nome),
    foto_url = CASE WHEN $2::boolean THEN NULL
                    ELSE coalesce($3, foto_url) END
WHERE id = $4
RETURNING id, tipo, nome, foto_url, dono_id, plano, status, criado_em
`

type AtualizarWorkspaceParams struct {
	Nome       *string
	LimparFoto bool
	FotoUrl    *string
	ID         uuid.UUID
}

func (q *Queries) AtualizarWorkspace(ctx context.Context, arg AtualizarWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, atualizarWorkspace,
		arg.Nome,
		arg.LimparFoto,
		arg.FotoUrl,
		arg.ID,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Tipo,
		&i.Nome,
		&i.FotoUrl,
		&i.DonoID,
		&i.Plano,
		&i.Status,
		&i.CriadoEm,
	)
	return i, err
}

const contarAfiliados = `-- name: ContarAfiliados :one
SELECT count(*) FROM membros WHERE workspace_id = $1 AND papel = 'afiliado'
`

func (q *Queries) ContarAfiliados(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, contarAfiliados, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const contarConvitesPendentes = `-- name: ContarConvitesPendentes :one
SELECT count(*) FROM convites
WHERE workspace_id = $1
  AND usado_por IS NULL
  AND revogado_em IS NULL
  AND expira_em > now()
`

func (q *Queries) ContarConvitesPendentes(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, contarConvitesPendentes, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const convitePorHash = `-- name: ConvitePorHash :one
SELECT id, workspace_id, email, token_hash, expira_em, usado_por, usado_em, revogado_em, criado_por, criado_em FROM convites WHERE token_hash = $1
`

func (q *Queries) ConvitePorHash(ctx context.Context, tokenHash []byte) (Convite, error) {
	row := q.db.QueryRow(ctx, convitePorHash, tokenHash)
	var i Convite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.TokenHash,
		&i.ExpiraEm,
		&i.UsadoPor,
		&i.UsadoEm,
		&i.RevogadoEm,
		&i.CriadoPor,
		&i.CriadoEm,
	)
	return i, err
}

const convitesPendentes = `-- name: ConvitesPendentes :many
SELECT id, workspace_id, email, token_hash, expira_em, usado_por, usado_em, revogado_em, criado_por, criado_em FROM convites
WHERE workspace_id = $1
  AND usado_por IS NULL
  AND revogado_em IS NULL
  AND expira_em > now()
ORDER BY criado_em DESC
`

func (q *Queries) ConvitesPendentes(ctx context.Context, workspaceID uuid.UUID) ([]Convite, error) {
	rows, err := q.db.Query(ctx, convitesPendentes, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Convite
	for rows.Next() {
		var i Convite
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Email,
			&i.TokenHash,
			&i.ExpiraEm,
			&i.UsadoPor,
			&i.UsadoEm,
			&i.RevogadoEm,
			&i.CriadoPor,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const criarConvite = `-- name: CriarConvite :one
INSERT INTO convites (workspace_id, email, token_hash, expira_em, criado_por)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, email, token_hash, expira_em, usado_por, usado_em, revogado_em, criado_por, criado_em
`

type CriarConviteParams struct {
	WorkspaceID uuid.UUID
	Email       *string
	TokenHash   []byte
	ExpiraEm    time.Time
	CriadoPor   uuid.UUID
}

func (q *Queries) CriarConvite(ctx context.Context, arg CriarConviteParams) (Convite, error) {
	row := q.db.QueryRow(ctx, criarConvite,
		arg.WorkspaceID,
		arg.Email,
		arg.TokenHash,
		arg.ExpiraEm,
		arg.CriadoPor,
	)
	var i Convite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.TokenHash,
		&i.ExpiraEm,
		&i.UsadoPor,
		&i.UsadoEm,
		&i.RevogadoEm,
		&i.CriadoPor,
		&i.CriadoEm,
	)
	return i, err
}

const criarWorkspace = `-- name: CriarWorkspace :one
INSERT INTO workspaces (tipo, nome, foto_url, dono_id, plano)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tipo, nome, foto_url, dono_id, plano, status, criado_em
`

type CriarWorkspaceParams struct {
	Tipo    WorkspaceTipo
	Nome    string
	FotoUrl *string
	DonoID  uuid.UUID
	Plano   string
}

func (q *Queries) CriarWorkspace(ctx context.Context, arg CriarWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, criarWorkspace,
		arg.Tipo,
		arg.Nome,
		arg.FotoUrl,
		arg.DonoID,
		arg.Plano,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Tipo,
		&i.Nome,
		&i.FotoUrl,
		&i.DonoID,
		&i.Plano,
		&i.Status,
		&i.CriadoEm,
	)
	return i, err
}

const inserirMembro = `-- name: InserirMembro :exec
INSERT INTO membros (workspace_id, usuario_id, papel)
VALUES ($1, $2, $3)
`

type InserirMembroParams struct {
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
	Papel       MembroPapel
}

func (q *Queries) InserirMembro(ctx context.Context, arg InserirMembroParams) error {
	_, err := q.db.Exec(ctx, inserirMembro, arg.WorkspaceID, arg.UsuarioID, arg.Papel)
	return err
}

const limite = `-- name: Limite :one
SELECT valor FROM limites WHERE plano = $1 AND chave = $2
`

type LimiteParams struct {
	Plano string
	Chave string
}

func (q *Queries) Limite(ctx context.Context, arg LimiteParams) (int64, error) {
	row := q.db.QueryRow(ctx, limite, arg.Plano, arg.Chave)
	var valor int64
	err := row.Scan(&valor)
	return valor, err
}

const marcarConviteUsado = `-- name: MarcarConviteUsado :exec
UPDATE convites SET usado_por = $2, usado_em = now() WHERE id = $1
`

type MarcarConviteUsadoParams struct {
	ID       uuid.UUID
	UsadoPor *uuid.UUID
}

func (q *Queries) MarcarConviteUsado(ctx context.Context, arg MarcarConviteUsadoParams) error {
	_, err := q.db.Exec(ctx, marcarConviteUsado, arg.ID, arg.UsadoPor)
	return err
}

const membro = `-- name: Membro :one
SELECT workspace_id, usuario_id, papel, consente_resultados, entrou_em FROM membros WHERE workspace_id = $1 AND usuario_id = $2
`

type MembroParams struct {
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
}

func (q *Queries) Membro(ctx context.Context, arg MembroParams) (Membro, error) {
	row := q.db.QueryRow(ctx, membro, arg.WorkspaceID, arg.UsuarioID)
	var i Membro
	err := row.Scan(
		&i.WorkspaceID,
		&i.UsuarioID,
		&i.Papel,
		&i.ConsenteResultados,
		&i.EntrouEm,
	)
	return i, err
}

const membrosDoWorkspace = `-- name: MembrosDoWorkspace :many
SELECT m.usuario_id, u.nome, u.email, m.papel, m.entrou_em
FROM membros m
JOIN usuarios u ON u.id = m.usuario_id
WHERE m.workspace_id = $1
ORDER BY m.papel, m.entrou_em
`

type MembrosDoWorkspaceRow struct {
	UsuarioID uuid.UUID
	Nome      string
	Email     string
	Papel     MembroPapel
	EntrouEm  time.Time
}

func (q *Queries) MembrosDoWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]MembrosDoWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, membrosDoWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MembrosDoWorkspaceRow
	for rows.Next() {
		var i MembrosDoWorkspaceRow
		if err := rows.Scan(
			&i.UsuarioID,
			&i.Nome,
			&i.Email,
			&i.Papel,
			&i.EntrouEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removerMembro = `-- name: RemoverMembro :execrows
DELETE FROM membros WHERE workspace_id = $1 AND usuario_id = $2
`

type RemoverMembroParams struct {
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
}

func (q *Queries) RemoverMembro(ctx context.Context, arg RemoverMembroParams) (int64, error) {
	result, err := q.db.Exec(ctx, removerMembro, arg.WorkspaceID, arg.UsuarioID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revogarConvite = `-- name: RevogarConvite :execrows
UPDATE convites SET revogado_em = now()
WHERE id = $1
  AND workspace_id = $2
  AND usado_por IS NULL
  AND revogado_em IS NULL
`

type RevogarConviteParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) RevogarConvite(ctx context.Context, arg RevogarConviteParams) (int64, error) {
	result, err := q.db.Exec(ctx, revogarConvite, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const travarConvitePorHash = `-- name: TravarConvitePorHash :one
SELECT id, workspace_id, email, token_hash, expira_em, usado_por, usado_em, revogado_em, criado_por, criado_em FROM convites WHERE token_hash = $1 FOR UPDATE
`

func (q *Queries) TravarConvitePorHash(ctx context.Context, tokenHash []byte) (Convite, error) {
	row := q.db.QueryRow(ctx, travarConvitePorHash, tokenHash)
	var i Convite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.TokenHash,
		&i.ExpiraEm,
		&i.UsadoPor,
		&i.UsadoEm,
		&i.RevogadoEm,
		&i.CriadoPor,
		&i.CriadoEm,
	)
	return i, err
}

const travarWorkspace = `-- name: TravarWorkspace :one
SELECT id, tipo, nome, foto_url, dono_id, plano, status, criado_em FROM workspaces WHERE id = $1 FOR UPDATE
`

// Trava a linha do workspace para serializar a contagem de assentos.
func (q *Queries) TravarWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, travarWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Tipo,
		&i.Nome,
		&i.FotoUrl,
		&i.DonoID,
		&i.Plano,
		&i.Status,
		&i.CriadoEm,
	)
	return i, err
}

const upsertUsuario = `-- name: UpsertUsuario :one
INSERT INTO usuarios (zitadel_sub, nome, email, email_verificado)
VALUES ($1, $2, $3, $4)
ON CONFLICT (zitadel_sub) DO UPDATE
    SET nome = EXCLUDED.nome,
        email = EXCLUDED.email,
        email_verificado = EXCLUDED.email_verificado
RETURNING id, (xmax = 0)::boolean AS criado
`

type UpsertUsuarioParams struct {
	ZitadelSub      string
	Nome            string
	Email           string
	EmailVerificado bool
}

type UpsertUsuarioRow struct {
	ID     uuid.UUID
	Criado bool
}

// Cria o usuário no primeiro acesso ou atualiza nome e e-mail. `criado` diz
// se a linha acabou de ser inserida.
func (q *Queries) UpsertUsuario(ctx context.Context, arg UpsertUsuarioParams) (UpsertUsuarioRow, error) {
	row := q.db.QueryRow(ctx, upsertUsuario,
		arg.ZitadelSub,
		arg.Nome,
		arg.Email,
		arg.EmailVerificado,
	)
	var i UpsertUsuarioRow
	err := row.Scan(&i.ID, &i.Criado)
	return i, err
}

const usuarioPorID = `-- name: UsuarioPorID :one
SELECT id, zitadel_sub, nome, email, email_verificado, criado_em FROM usuarios WHERE id = $1
`

func (q *Queries) UsuarioPorID(ctx context.Context, id uuid.UUID) (Usuario, error) {
	row := q.db.QueryRow(ctx, usuarioPorID, id)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.ZitadelSub,
		&i.Nome,
		&i.Email,
		&i.EmailVerificado,
		&i.CriadoEm,
	)
	return i, err
}

const usuarioPorSub = `-- name: UsuarioPorSub :one

SELECT id, zitadel_sub, nome, email, email_verificado, criado_em FROM usuarios WHERE zitadel_sub = $1
`

// Queries do módulo contas. Gere o código com `make sqlc`.
func (q *Queries) UsuarioPorSub(ctx context.Context, zitadelSub string) (Usuario, error) {
	row := q.db.QueryRow(ctx, usuarioPorSub, zitadelSub)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.ZitadelSub,
		&i.Nome,
		&i.Email,
		&i.EmailVerificado,
		&i.CriadoEm,
	)
	return i, err
}

const workspace = `-- name: Workspace :one
SELECT id, tipo, nome, foto_url, dono_id, plano, status, criado_em FROM workspaces WHERE id = $1
`

func (q *Queries) Workspace(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, workspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Tipo,
		&i.Nome,
		&i.FotoUrl,
		&i.DonoID,
		&i.Plano,
		&i.Status,
		&i.CriadoEm,
	)
	return i, err
}

const workspacesDoUsuario = `-- name: WorkspacesDoUsuario :many
SELECT w.id, w.tipo, w.nome, w.foto_url, w.dono_id, w.plano, w.status, w.criado_em, m.papel
FROM membros m
JOIN workspaces w ON w.id = m.workspace_id
WHERE m.usuario_id = $1
ORDER BY w.tipo, w.criado_em
`

type WorkspacesDoUsuarioRow struct {
	ID       uuid.UUID
	Tipo     WorkspaceTipo
	Nome     string
	FotoUrl  *string
	DonoID   uuid.UUID
	Plano    string
	Status   string
	CriadoEm time.Time
	Papel    MembroPapel
}

func (q *Queries) WorkspacesDoUsuario(ctx context.Context, usuarioID uuid.UUID) ([]WorkspacesDoUsuarioRow, error) {
	rows, err := q.db.Query(ctx, workspacesDoUsuario, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorkspacesDoUsuarioRow
	for rows.Next() {
		var i WorkspacesDoUsuarioRow
		if err := rows.Scan(
			&i.ID,
			&i.Tipo,
			&i.Nome,
			&i.FotoUrl,
			&i.DonoID,
			&i.Plano,
			&i.Status,
			&i.CriadoEm,
			&i.Papel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
