// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package contasdb

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type MembroPapel string

const (
	MembroPapelDono     MembroPapel = "dono"
	MembroPapelMentor   MembroPapel = "mentor"
	MembroPapelAfiliado MembroPapel = "afiliado"
)

func (e *MembroPapel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MembroPapel(s)
	case string:
		*e = MembroPapel(s)
	default:
		return fmt.Errorf("unsupported scan type for MembroPapel: %T", src)
	}
	return nil
}

type NullMembroPapel struct {
	MembroPapel MembroPapel
	Valid       bool // Valid is true if MembroPapel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMembroPapel) Scan(value interface{}) error {
	if value == nil {
		ns.MembroPapel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MembroPapel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMembroPapel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MembroPapel), nil
}

type WorkspaceTipo string

const (
	WorkspaceTipoPessoal  WorkspaceTipo = "pessoal"
	WorkspaceTipoMentoria WorkspaceTipo = "mentoria"
)

func (e *WorkspaceTipo) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkspaceTipo(s)
	case string:
		*e = WorkspaceTipo(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkspaceTipo: %T", src)
	}
	return nil
}

type NullWorkspaceTipo struct {
	WorkspaceTipo WorkspaceTipo
	Valid         bool // Valid is true if WorkspaceTipo is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkspaceTipo) Scan(value interface{}) error {
	if value == nil {
		ns.WorkspaceTipo, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkspaceTipo.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkspaceTipo) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkspaceTipo), nil
}

type Convite struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Email       *string
	TokenHash   []byte
	ExpiraEm    time.Time
	UsadoPor    *uuid.UUID
	UsadoEm     *time.Time
	RevogadoEm  *time.Time
	CriadoPor   uuid.UUID
	CriadoEm    time.Time
}

type Limite struct {
	Plano string
	Chave string
	Valor int64
}

type Membro struct {
	WorkspaceID        uuid.UUID
	UsuarioID          uuid.UUID
	Papel              MembroPapel
	ConsenteResultados bool
	EntrouEm           time.Time
}

type Usuario struct {
	ID              uuid.UUID
	ZitadelSub      string
	Nome            string
	Email           string
	EmailVerificado bool
	CriadoEm        time.Time
}

type Workspace struct {
	ID       uuid.UUID
	Tipo     WorkspaceTipo
	Nome     string
	FotoUrl  *string
	DonoID   uuid.UUID
	Plano    string
	Status   string
	CriadoEm time.Time
}
