// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package contasdb

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type CredencialStatus string

const (
	CredencialStatusConectado CredencialStatus = "conectado"
	CredencialStatusInvalido  CredencialStatus = "invalido"
	CredencialStatusExpirado  CredencialStatus = "expirado"
)

func (e *CredencialStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CredencialStatus(s)
	case string:
		*e = CredencialStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CredencialStatus: %T", src)
	}
	return nil
}

type NullCredencialStatus struct {
	CredencialStatus CredencialStatus
	Valid            bool // Valid is true if CredencialStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCredencialStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CredencialStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CredencialStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCredencialStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CredencialStatus), nil
}

type Fonte string

const (
	FonteShopee Fonte = "shopee"
)

func (e *Fonte) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Fonte(s)
	case string:
		*e = Fonte(s)
	default:
		return fmt.Errorf("unsupported scan type for Fonte: %T", src)
	}
	return nil
}

type NullFonte struct {
	Fonte Fonte
	Valid bool // Valid is true if Fonte is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFonte) Scan(value interface{}) error {
	if value == nil {
		ns.Fonte, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Fonte.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFonte) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Fonte), nil
}

type MembroPapel string

const (
	MembroPapelDono     MembroPapel = "dono"
	MembroPapelMentor   MembroPapel = "mentor"
	MembroPapelAfiliado MembroPapel = "afiliado"
)

func (e *MembroPapel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MembroPapel(s)
	case string:
		*e = MembroPapel(s)
	default:
		return fmt.Errorf("unsupported scan type for MembroPapel: %T", src)
	}
	return nil
}

type NullMembroPapel struct {
	MembroPapel MembroPapel
	Valid       bool // Valid is true if MembroPapel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMembroPapel) Scan(value interface{}) error {
	if value == nil {
		ns.MembroPapel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MembroPapel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMembroPapel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MembroPapel), nil
}

type WorkspaceTipo string

const (
	WorkspaceTipoPessoal  WorkspaceTipo = "pessoal"
	WorkspaceTipoMentoria WorkspaceTipo = "mentoria"
)

func (e *WorkspaceTipo) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WorkspaceTipo(s)
	case string:
		*e = WorkspaceTipo(s)
	default:
		return fmt.Errorf("unsupported scan type for WorkspaceTipo: %T", src)
	}
	return nil
}

type NullWorkspaceTipo struct {
	WorkspaceTipo WorkspaceTipo
	Valid         bool // Valid is true if WorkspaceTipo is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWorkspaceTipo) Scan(value interface{}) error {
	if value == nil {
		ns.WorkspaceTipo, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WorkspaceTipo.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWorkspaceTipo) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WorkspaceTipo), nil
}

type Categoria struct {
	Fonte     Fonte
	ID        int64
	Nome      string
	Monitorar bool
}

type Convite struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Email       *string
	TokenHash   []byte
	ExpiraEm    time.Time
	UsadoPor    *uuid.UUID
	UsadoEm     *time.Time
	RevogadoEm  *time.Time
	CriadoPor   uuid.UUID
	CriadoEm    time.Time
}

type CredenciaisShopee struct {
	UsuarioID     uuid.UUID
	AppID         string
	SecretCifrado []byte
	DekCifrada    []byte
	KekID         string
	Status        CredencialStatus
	VerificadoEm  time.Time
	CriadoEm      time.Time
	AtualizadoEm  time.Time
}

type Limite struct {
	Plano string
	Chave string
	Valor int64
}

type Membro struct {
	WorkspaceID        uuid.UUID
	UsuarioID          uuid.UUID
	Papel              MembroPapel
	ConsenteResultados bool
	EntrouEm           time.Time
}

type Produto struct {
	ID               uuid.UUID
	Fonte            Fonte
	ItemID           int64
	LojaID           int64
	LojaNome         string
	Nome             string
	ImagemUrl        *string
	CategoriaID      *int64
	Categorias       []int64
	Url              string
	PrecoMinCentavos int64
	PrecoMaxCentavos int64
	ComissaoBp       int32
	Vendas           int64
	Nota             *float64
	ColetadoEm       time.Time
	CriadoEm         time.Time
}

type ProdutoSnapshot struct {
	ProdutoID        uuid.UUID
	ColetadoEm       time.Time
	PrecoMinCentavos int64
	PrecoMaxCentavos int64
	ComissaoBp       int32
	Vendas           int64
	Nota             *float64
}

type ProdutoSnapshotsPadrao struct {
	ProdutoID        uuid.UUID
	ColetadoEm       time.Time
	PrecoMinCentavos int64
	PrecoMaxCentavos int64
	ComissaoBp       int32
	Vendas           int64
	Nota             *float64
}

type Tendencia struct {
	ProdutoID             uuid.UUID
	CalculadoEm           time.Time
	Score                 float64
	GanhoPorVendaCentavos int64
	VariacaoVendas7d      *int64
	Nome                  string
	LojaNome              string
	ImagemUrl             *string
	CategoriaID           *int64
	Categorias            []int64
	Url                   string
	PrecoMinCentavos      int64
	PrecoMaxCentavos      int64
	ComissaoBp            int32
	Vendas                int64
	Nota                  *float64
	AtualizadoEm          time.Time
	Busca                 interface{}
}

type Usuario struct {
	ID              uuid.UUID
	ZitadelSub      string
	Nome            string
	Email           string
	EmailVerificado bool
	CriadoEm        time.Time
}

type Workspace struct {
	ID       uuid.UUID
	Tipo     WorkspaceTipo
	Nome     string
	FotoUrl  *string
	DonoID   uuid.UUID
	Plano    string
	Status   string
	CriadoEm time.Time
}
