// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: colecoes.sql

package colecoesdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const adicionarColecaoItem = `-- name: AdicionarColecaoItem :exec
INSERT INTO colecao_itens (colecao_id, item_id, workspace_id, usuario_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type AdicionarColecaoItemParams struct {
	ColecaoID   uuid.UUID
	ItemID      uuid.UUID
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
}

func (q *Queries) AdicionarColecaoItem(ctx context.Context, arg AdicionarColecaoItemParams) error {
	_, err := q.db.Exec(ctx, adicionarColecaoItem,
		arg.ColecaoID,
		arg.ItemID,
		arg.WorkspaceID,
		arg.UsuarioID,
	)
	return err
}

const apagarColecao = `-- name: ApagarColecao :execrows
DELETE FROM colecoes WHERE id = $1 AND workspace_id = $2 AND usuario_id = $3
`

type ApagarColecaoParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
}

func (q *Queries) ApagarColecao(ctx context.Context, arg ApagarColecaoParams) (int64, error) {
	result, err := q.db.Exec(ctx, apagarColecao, arg.ID, arg.WorkspaceID, arg.UsuarioID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const apagarLinksCanal = `-- name: ApagarLinksCanal :exec
DELETE FROM links_canal WHERE item_id = $1 AND workspace_id = $2 AND usuario_id = $3
`

type ApagarLinksCanalParams struct {
	ItemID      uuid.UUID
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
}

func (q *Queries) ApagarLinksCanal(ctx context.Context, arg ApagarLinksCanalParams) error {
	_, err := q.db.Exec(ctx, apagarLinksCanal, arg.ItemID, arg.WorkspaceID, arg.UsuarioID)
	return err
}

const atualizarItem = `-- name: AtualizarItem :one
UPDATE itens_colecao SET
    titulo = coalesce($1, titulo),
    descricao = coalesce($2, descricao),
    notas = coalesce($3, notas),
    tags = coalesce($4::text[], tags),
    status = coalesce($5::item_status, status),
    atualizado_em = now()
WHERE id = $6 AND workspace_id = $7 AND usuario_id = $8
RETURNING id, workspace_id, usuario_id, produto_id, titulo, descricao, notas, tags, status, link_afiliado, link_origem, link_status, criado_em, atualizado_em
`

type AtualizarItemParams struct {
	Titulo      *string
	Descricao   *string
	Notas       *string
	Tags        []string
	Status      *ItemStatus
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
}

func (q *Queries) AtualizarItem(ctx context.Context, arg AtualizarItemParams) (ItensColecao, error) {
	row := q.db.QueryRow(ctx, atualizarItem,
		arg.Titulo,
		arg.Descricao,
		arg.Notas,
		arg.Tags,
		arg.Status,
		arg.ID,
		arg.WorkspaceID,
		arg.UsuarioID,
	)
	var i ItensColecao
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UsuarioID,
		&i.ProdutoID,
		&i.Titulo,
		&i.Descricao,
		&i.Notas,
		&i.Tags,
		&i.Status,
		&i.LinkAfiliado,
		&i.LinkOrigem,
		&i.LinkStatus,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const colecao = `-- name: Colecao :one
SELECT c.id, c.nome, c.criado_em,
    (SELECT count(*) FROM colecao_itens ci
     WHERE ci.colecao_id = c.id AND ci.workspace_id = $1 AND ci.usuario_id = $2) AS itens
FROM colecoes c
WHERE c.id = $3 AND c.workspace_id = $1 AND c.usuario_id = $2
`

type ColecaoParams struct {
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
	ID          uuid.UUID
}

type ColecaoRow struct {
	ID       uuid.UUID
	Nome     string
	CriadoEm time.Time
	Itens    int64
}

func (q *Queries) Colecao(ctx context.Context, arg ColecaoParams) (ColecaoRow, error) {
	row := q.db.QueryRow(ctx, colecao, arg.WorkspaceID, arg.UsuarioID, arg.ID)
	var i ColecaoRow
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.CriadoEm,
		&i.Itens,
	)
	return i, err
}

const colecoesDosItens = `-- name: ColecoesDosItens :many
SELECT item_id, colecao_id FROM colecao_itens
WHERE workspace_id = $1 AND usuario_id = $2 AND item_id = ANY ($3::uuid[])
ORDER BY item_id, adicionado_em
`

type ColecoesDosItensParams struct {
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
	Ids         []uuid.UUID
}

type ColecoesDosItensRow struct {
	ItemID    uuid.UUID
	ColecaoID uuid.UUID
}

func (q *Queries) ColecoesDosItens(ctx context.Context, arg ColecoesDosItensParams) ([]ColecoesDosItensRow, error) {
	rows, err := q.db.Query(ctx, colecoesDosItens, arg.WorkspaceID, arg.UsuarioID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ColecoesDosItensRow
	for rows.Next() {
		var i ColecoesDosItensRow
		if err := rows.Scan(&i.ItemID, &i.ColecaoID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const concluirLink = `-- name: ConcluirLink :execrows
UPDATE itens_colecao SET link_afiliado = $1, link_status = 'pronto', atualizado_em = now()
WHERE id = $2 AND workspace_id = $3 AND usuario_id = $4 AND link_origem = 'auto'
`

type ConcluirLinkParams struct {
	LinkAfiliado *string
	ID           uuid.UUID
	WorkspaceID  uuid.UUID
	UsuarioID    uuid.UUID
}

func (q *Queries) ConcluirLink(ctx context.Context, arg ConcluirLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, concluirLink,
		arg.LinkAfiliado,
		arg.ID,
		arg.WorkspaceID,
		arg.UsuarioID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const contarColecoes = `-- name: ContarColecoes :one
SELECT count(*) FROM colecoes
WHERE workspace_id = $1 AND usuario_id = $2 AND id = ANY ($3::uuid[])
`

type ContarColecoesParams struct {
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
	Ids         []uuid.UUID
}

func (q *Queries) ContarColecoes(ctx context.Context, arg ContarColecoesParams) (int64, error) {
	row := q.db.QueryRow(ctx, contarColecoes, arg.WorkspaceID, arg.UsuarioID, arg.Ids)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const criarColecao = `-- name: CriarColecao :one
INSERT INTO colecoes (workspace_id, usuario_id, nome) VALUES ($1, $2, $3)
RETURNING id
`

type CriarColecaoParams struct {
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
	Nome        string
}

func (q *Queries) CriarColecao(ctx context.Context, arg CriarColecaoParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, criarColecao, arg.WorkspaceID, arg.UsuarioID, arg.Nome)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const criarItem = `-- name: CriarItem :one

INSERT INTO itens_colecao (workspace_id, usuario_id, produto_id, titulo, link_status)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (workspace_id, usuario_id, produto_id) DO NOTHING
RETURNING id, workspace_id, usuario_id, produto_id, titulo, descricao, notas, tags, status, link_afiliado, link_origem, link_status, criado_em, atualizado_em
`

type CriarItemParams struct {
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
	ProdutoID   uuid.UUID
	Titulo      string
	LinkStatus  LinkStatus
}

// Toda query filtra por workspace_id e usuario_id, além da RLS.
func (q *Queries) CriarItem(ctx context.Context, arg CriarItemParams) (ItensColecao, error) {
	row := q.db.QueryRow(ctx, criarItem,
		arg.WorkspaceID,
		arg.UsuarioID,
		arg.ProdutoID,
		arg.Titulo,
		arg.LinkStatus,
	)
	var i ItensColecao
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UsuarioID,
		&i.ProdutoID,
		&i.Titulo,
		&i.Descricao,
		&i.Notas,
		&i.Tags,
		&i.Status,
		&i.LinkAfiliado,
		&i.LinkOrigem,
		&i.LinkStatus,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const definirLinkManual = `-- name: DefinirLinkManual :one
UPDATE itens_colecao SET
    link_afiliado = $1, link_origem = 'manual', link_status = 'pronto', atualizado_em = now()
WHERE id = $2 AND workspace_id = $3 AND usuario_id = $4
RETURNING id, workspace_id, usuario_id, produto_id, titulo, descricao, notas, tags, status, link_afiliado, link_origem, link_status, criado_em, atualizado_em
`

type DefinirLinkManualParams struct {
	LinkAfiliado *string
	ID           uuid.UUID
	WorkspaceID  uuid.UUID
	UsuarioID    uuid.UUID
}

func (q *Queries) DefinirLinkManual(ctx context.Context, arg DefinirLinkManualParams) (ItensColecao, error) {
	row := q.db.QueryRow(ctx, definirLinkManual,
		arg.LinkAfiliado,
		arg.ID,
		arg.WorkspaceID,
		arg.UsuarioID,
	)
	var i ItensColecao
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UsuarioID,
		&i.ProdutoID,
		&i.Titulo,
		&i.Descricao,
		&i.Notas,
		&i.Tags,
		&i.Status,
		&i.LinkAfiliado,
		&i.LinkOrigem,
		&i.LinkStatus,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const item = `-- name: Item :one
SELECT id, workspace_id, usuario_id, produto_id, titulo, descricao, notas, tags, status, link_afiliado, link_origem, link_status, criado_em, atualizado_em FROM itens_colecao
WHERE id = $1 AND workspace_id = $2 AND usuario_id = $3
`

type ItemParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
}

func (q *Queries) Item(ctx context.Context, arg ItemParams) (ItensColecao, error) {
	row := q.db.QueryRow(ctx, item, arg.ID, arg.WorkspaceID, arg.UsuarioID)
	var i ItensColecao
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UsuarioID,
		&i.ProdutoID,
		&i.Titulo,
		&i.Descricao,
		&i.Notas,
		&i.Tags,
		&i.Status,
		&i.LinkAfiliado,
		&i.LinkOrigem,
		&i.LinkStatus,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const itemPorProduto = `-- name: ItemPorProduto :one
SELECT id, workspace_id, usuario_id, produto_id, titulo, descricao, notas, tags, status, link_afiliado, link_origem, link_status, criado_em, atualizado_em FROM itens_colecao
WHERE workspace_id = $1 AND usuario_id = $2 AND produto_id = $3
`

type ItemPorProdutoParams struct {
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
	ProdutoID   uuid.UUID
}

func (q *Queries) ItemPorProduto(ctx context.Context, arg ItemPorProdutoParams) (ItensColecao, error) {
	row := q.db.QueryRow(ctx, itemPorProduto, arg.WorkspaceID, arg.UsuarioID, arg.ProdutoID)
	var i ItensColecao
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UsuarioID,
		&i.ProdutoID,
		&i.Titulo,
		&i.Descricao,
		&i.Notas,
		&i.Tags,
		&i.Status,
		&i.LinkAfiliado,
		&i.LinkOrigem,
		&i.LinkStatus,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const itensSemLink = `-- name: ItensSemLink :many
UPDATE itens_colecao SET link_status = 'gerando', atualizado_em = now()
WHERE workspace_id = $1 AND usuario_id = $2
  AND link_origem = 'auto' AND link_status IN ('pendente', 'falhou')
RETURNING id
`

type ItensSemLinkParams struct {
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
}

// Links automáticos pendentes (sem credencial) ou que falharam, para gerar de novo.
func (q *Queries) ItensSemLink(ctx context.Context, arg ItensSemLinkParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, itensSemLink, arg.WorkspaceID, arg.UsuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const limparColecoesDoItem = `-- name: LimparColecoesDoItem :exec
DELETE FROM colecao_itens WHERE item_id = $1 AND workspace_id = $2 AND usuario_id = $3
`

type LimparColecoesDoItemParams struct {
	ItemID      uuid.UUID
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
}

func (q *Queries) LimparColecoesDoItem(ctx context.Context, arg LimparColecoesDoItemParams) error {
	_, err := q.db.Exec(ctx, limparColecoesDoItem, arg.ItemID, arg.WorkspaceID, arg.UsuarioID)
	return err
}

const linksDosItens = `-- name: LinksDosItens :many
SELECT item_id, canal, sub_id, url FROM links_canal
WHERE workspace_id = $1 AND usuario_id = $2 AND item_id = ANY ($3::uuid[])
ORDER BY item_id, canal
`

type LinksDosItensParams struct {
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
	Ids         []uuid.UUID
}

type LinksDosItensRow struct {
	ItemID uuid.UUID
	Canal  Canal
	SubID  string
	Url    string
}

func (q *Queries) LinksDosItens(ctx context.Context, arg LinksDosItensParams) ([]LinksDosItensRow, error) {
	rows, err := q.db.Query(ctx, linksDosItens, arg.WorkspaceID, arg.UsuarioID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LinksDosItensRow
	for rows.Next() {
		var i LinksDosItensRow
		if err := rows.Scan(
			&i.ItemID,
			&i.Canal,
			&i.SubID,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarColecoes = `-- name: ListarColecoes :many
SELECT c.id, c.nome, c.criado_em,
    (SELECT count(*) FROM colecao_itens ci
     WHERE ci.colecao_id = c.id AND ci.workspace_id = $1 AND ci.usuario_id = $2) AS itens
FROM colecoes c
WHERE c.workspace_id = $1 AND c.usuario_id = $2
ORDER BY lower(c.nome)
`

type ListarColecoesParams struct {
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
}

type ListarColecoesRow struct {
	ID       uuid.UUID
	Nome     string
	CriadoEm time.Time
	Itens    int64
}

func (q *Queries) ListarColecoes(ctx context.Context, arg ListarColecoesParams) ([]ListarColecoesRow, error) {
	rows, err := q.db.Query(ctx, listarColecoes, arg.WorkspaceID, arg.UsuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarColecoesRow
	for rows.Next() {
		var i ListarColecoesRow
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.CriadoEm,
			&i.Itens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarItens = `-- name: ListarItens :many
SELECT i.id, i.workspace_id, i.usuario_id, i.produto_id, i.titulo, i.descricao, i.notas, i.tags, i.status, i.link_afiliado, i.link_origem, i.link_status, i.criado_em, i.atualizado_em, count(*) OVER () AS total
FROM itens_colecao i
WHERE i.workspace_id = $1 AND i.usuario_id = $2
  AND ($3::item_status IS NULL OR i.status = $3)
  AND ($4::text IS NULL OR $4 = ANY (i.tags))
  AND ($5::text IS NULL
       OR i.titulo ILIKE '%' || $5 || '%'
       OR i.descricao ILIKE '%' || $5 || '%'
       OR i.notas ILIKE '%' || $5 || '%')
  AND ($6::uuid IS NULL OR EXISTS (
       SELECT 1 FROM colecao_itens ci
       WHERE ci.item_id = i.id AND ci.colecao_id = $6
         AND ci.workspace_id = $1 AND ci.usuario_id = $2))
ORDER BY i.criado_em DESC, i.id
LIMIT $8 OFFSET $7
`

type ListarItensParams struct {
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
	Status      *ItemStatus
	Tag         *string
	Busca       *string
	ColecaoID   *uuid.UUID
	Desloc      int32
	Limite      int32
}

type ListarItensRow struct {
	ID           uuid.UUID
	WorkspaceID  uuid.UUID
	UsuarioID    uuid.UUID
	ProdutoID    uuid.UUID
	Titulo       string
	Descricao    string
	Notas        string
	Tags         []string
	Status       ItemStatus
	LinkAfiliado *string
	LinkOrigem   LinkOrigem
	LinkStatus   LinkStatus
	CriadoEm     time.Time
	AtualizadoEm time.Time
	Total        int64
}

func (q *Queries) ListarItens(ctx context.Context, arg ListarItensParams) ([]ListarItensRow, error) {
	rows, err := q.db.Query(ctx, listarItens,
		arg.WorkspaceID,
		arg.UsuarioID,
		arg.Status,
		arg.Tag,
		arg.Busca,
		arg.ColecaoID,
		arg.Desloc,
		arg.Limite,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarItensRow
	for rows.Next() {
		var i ListarItensRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UsuarioID,
			&i.ProdutoID,
			&i.Titulo,
			&i.Descricao,
			&i.Notas,
			&i.Tags,
			&i.Status,
			&i.LinkAfiliado,
			&i.LinkOrigem,
			&i.LinkStatus,
			&i.CriadoEm,
			&i.AtualizadoEm,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marcarLinkStatus = `-- name: MarcarLinkStatus :exec
UPDATE itens_colecao SET link_status = $1, atualizado_em = now()
WHERE id = $2 AND workspace_id = $3 AND usuario_id = $4 AND link_origem = 'auto'
`

type MarcarLinkStatusParams struct {
	LinkStatus  LinkStatus
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
}

// Só mexe em links automáticos: um link manual gravado enquanto o job rodava vence.
func (q *Queries) MarcarLinkStatus(ctx context.Context, arg MarcarLinkStatusParams) error {
	_, err := q.db.Exec(ctx, marcarLinkStatus,
		arg.LinkStatus,
		arg.ID,
		arg.WorkspaceID,
		arg.UsuarioID,
	)
	return err
}

const prepararLinkAuto = `-- name: PrepararLinkAuto :one
UPDATE itens_colecao SET
    link_afiliado = NULL, link_origem = 'auto', link_status = $1, atualizado_em = now()
WHERE id = $2 AND workspace_id = $3 AND usuario_id = $4
RETURNING id, workspace_id, usuario_id, produto_id, titulo, descricao, notas, tags, status, link_afiliado, link_origem, link_status, criado_em, atualizado_em
`

type PrepararLinkAutoParams struct {
	LinkStatus  LinkStatus
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
}

// Volta ao link automático: apaga o atual e espera o job gerar_link.
func (q *Queries) PrepararLinkAuto(ctx context.Context, arg PrepararLinkAutoParams) (ItensColecao, error) {
	row := q.db.QueryRow(ctx, prepararLinkAuto,
		arg.LinkStatus,
		arg.ID,
		arg.WorkspaceID,
		arg.UsuarioID,
	)
	var i ItensColecao
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UsuarioID,
		&i.ProdutoID,
		&i.Titulo,
		&i.Descricao,
		&i.Notas,
		&i.Tags,
		&i.Status,
		&i.LinkAfiliado,
		&i.LinkOrigem,
		&i.LinkStatus,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const produtosSalvos = `-- name: ProdutosSalvos :many
SELECT produto_id FROM itens_colecao
WHERE workspace_id = $1 AND usuario_id = $2
ORDER BY criado_em DESC
`

type ProdutosSalvosParams struct {
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
}

func (q *Queries) ProdutosSalvos(ctx context.Context, arg ProdutosSalvosParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, produtosSalvos, arg.WorkspaceID, arg.UsuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var produto_id uuid.UUID
		if err := rows.Scan(&produto_id); err != nil {
			return nil, err
		}
		items = append(items, produto_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removerItem = `-- name: RemoverItem :execrows
DELETE FROM itens_colecao WHERE id = $1 AND workspace_id = $2 AND usuario_id = $3
`

type RemoverItemParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
}

func (q *Queries) RemoverItem(ctx context.Context, arg RemoverItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, removerItem, arg.ID, arg.WorkspaceID, arg.UsuarioID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renomearColecao = `-- name: RenomearColecao :execrows
UPDATE colecoes SET nome = $1
WHERE id = $2 AND workspace_id = $3 AND usuario_id = $4
`

type RenomearColecaoParams struct {
	Nome        string
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
}

func (q *Queries) RenomearColecao(ctx context.Context, arg RenomearColecaoParams) (int64, error) {
	result, err := q.db.Exec(ctx, renomearColecao,
		arg.Nome,
		arg.ID,
		arg.WorkspaceID,
		arg.UsuarioID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const salvarLinkCanal = `-- name: SalvarLinkCanal :exec
INSERT INTO links_canal (item_id, workspace_id, usuario_id, canal, sub_id, url)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (item_id, canal) DO UPDATE SET sub_id = excluded.sub_id, url = excluded.url, gerado_em = now()
`

type SalvarLinkCanalParams struct {
	ItemID      uuid.UUID
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
	Canal       Canal
	SubID       string
	Url         string
}

func (q *Queries) SalvarLinkCanal(ctx context.Context, arg SalvarLinkCanalParams) error {
	_, err := q.db.Exec(ctx, salvarLinkCanal,
		arg.ItemID,
		arg.WorkspaceID,
		arg.UsuarioID,
		arg.Canal,
		arg.SubID,
		arg.Url,
	)
	return err
}
