// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notificacoes.sql

package notificacoesdb

import (
	"context"

	"github.com/google/uuid"
)

const apagarInscricao = `-- name: ApagarInscricao :execrows
DELETE FROM push_inscricoes WHERE usuario_id = $1 AND endpoint = $2
`

type ApagarInscricaoParams struct {
	UsuarioID uuid.UUID
	Endpoint  string
}

func (q *Queries) ApagarInscricao(ctx context.Context, arg ApagarInscricaoParams) (int64, error) {
	result, err := q.db.Exec(ctx, apagarInscricao, arg.UsuarioID, arg.Endpoint)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const caixa = `-- name: Caixa :many
SELECT id, workspace_id, usuario_id, tipo, chave, titulo, corpo, url, criado_em, lida_em, email_em, push_em FROM notificacoes
WHERE workspace_id = $1 AND usuario_id = $2
ORDER BY criado_em DESC, id
LIMIT $3
`

type CaixaParams struct {
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
	Limite      int32
}

func (q *Queries) Caixa(ctx context.Context, arg CaixaParams) ([]Notificacao, error) {
	rows, err := q.db.Query(ctx, caixa, arg.WorkspaceID, arg.UsuarioID, arg.Limite)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notificacao
	for rows.Next() {
		var i Notificacao
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UsuarioID,
			&i.Tipo,
			&i.Chave,
			&i.Titulo,
			&i.Corpo,
			&i.Url,
			&i.CriadoEm,
			&i.LidaEm,
			&i.EmailEm,
			&i.PushEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contarInscricoes = `-- name: ContarInscricoes :one
SELECT count(*) FROM push_inscricoes WHERE usuario_id = $1
`

func (q *Queries) ContarInscricoes(ctx context.Context, usuarioID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, contarInscricoes, usuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const contarNaoLidas = `-- name: ContarNaoLidas :one
SELECT count(*) FROM notificacoes
WHERE workspace_id = $1 AND usuario_id = $2 AND lida_em IS NULL
`

type ContarNaoLidasParams struct {
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
}

func (q *Queries) ContarNaoLidas(ctx context.Context, arg ContarNaoLidasParams) (int64, error) {
	row := q.db.QueryRow(ctx, contarNaoLidas, arg.WorkspaceID, arg.UsuarioID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const criarNotificacao = `-- name: CriarNotificacao :one

INSERT INTO notificacoes (workspace_id, usuario_id, tipo, chave, titulo, corpo, url)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (workspace_id, usuario_id, chave) DO UPDATE SET chave = excluded.chave
RETURNING id, workspace_id, usuario_id, tipo, chave, titulo, corpo, url, criado_em, lida_em, email_em, push_em
`

type CriarNotificacaoParams struct {
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
	Tipo        string
	Chave       string
	Titulo      string
	Corpo       string
	Url         string
}

// Queries do módulo notificacoes. A caixa filtra por workspace e usuário;
// inscrições e preferências, pelo usuário. A RLS repete os filtros.
// Idempotente pela chave: repetir a entrega devolve a mesma notificação.
func (q *Queries) CriarNotificacao(ctx context.Context, arg CriarNotificacaoParams) (Notificacao, error) {
	row := q.db.QueryRow(ctx, criarNotificacao,
		arg.WorkspaceID,
		arg.UsuarioID,
		arg.Tipo,
		arg.Chave,
		arg.Titulo,
		arg.Corpo,
		arg.Url,
	)
	var i Notificacao
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UsuarioID,
		&i.Tipo,
		&i.Chave,
		&i.Titulo,
		&i.Corpo,
		&i.Url,
		&i.CriadoEm,
		&i.LidaEm,
		&i.EmailEm,
		&i.PushEm,
	)
	return i, err
}

const inscricoes = `-- name: Inscricoes :many
SELECT id, usuario_id, endpoint, p256dh, auth, criado_em FROM push_inscricoes WHERE usuario_id = $1 ORDER BY criado_em
`

func (q *Queries) Inscricoes(ctx context.Context, usuarioID uuid.UUID) ([]PushInscricao, error) {
	rows, err := q.db.Query(ctx, inscricoes, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PushInscricao
	for rows.Next() {
		var i PushInscricao
		if err := rows.Scan(
			&i.ID,
			&i.UsuarioID,
			&i.Endpoint,
			&i.P256dh,
			&i.Auth,
			&i.CriadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marcarEmail = `-- name: MarcarEmail :exec
UPDATE notificacoes SET email_em = now()
WHERE id = $1 AND workspace_id = $2 AND usuario_id = $3
`

type MarcarEmailParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
}

func (q *Queries) MarcarEmail(ctx context.Context, arg MarcarEmailParams) error {
	_, err := q.db.Exec(ctx, marcarEmail, arg.ID, arg.WorkspaceID, arg.UsuarioID)
	return err
}

const marcarLida = `-- name: MarcarLida :execrows
UPDATE notificacoes SET lida_em = coalesce(lida_em, now())
WHERE id = $1 AND workspace_id = $2 AND usuario_id = $3
`

type MarcarLidaParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
}

func (q *Queries) MarcarLida(ctx context.Context, arg MarcarLidaParams) (int64, error) {
	result, err := q.db.Exec(ctx, marcarLida, arg.ID, arg.WorkspaceID, arg.UsuarioID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const marcarPush = `-- name: MarcarPush :exec
UPDATE notificacoes SET push_em = now()
WHERE id = $1 AND workspace_id = $2 AND usuario_id = $3
`

type MarcarPushParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
}

func (q *Queries) MarcarPush(ctx context.Context, arg MarcarPushParams) error {
	_, err := q.db.Exec(ctx, marcarPush, arg.ID, arg.WorkspaceID, arg.UsuarioID)
	return err
}

const marcarTodasLidas = `-- name: MarcarTodasLidas :exec
UPDATE notificacoes SET lida_em = now()
WHERE workspace_id = $1 AND usuario_id = $2 AND lida_em IS NULL
`

type MarcarTodasLidasParams struct {
	WorkspaceID uuid.UUID
	UsuarioID   uuid.UUID
}

func (q *Queries) MarcarTodasLidas(ctx context.Context, arg MarcarTodasLidasParams) error {
	_, err := q.db.Exec(ctx, marcarTodasLidas, arg.WorkspaceID, arg.UsuarioID)
	return err
}

const preferencias = `-- name: Preferencias :one
SELECT usuario_id, email, atualizado_em FROM preferencias_notificacao WHERE usuario_id = $1
`

func (q *Queries) Preferencias(ctx context.Context, usuarioID uuid.UUID) (PreferenciaNotificacao, error) {
	row := q.db.QueryRow(ctx, preferencias, usuarioID)
	var i PreferenciaNotificacao
	err := row.Scan(&i.UsuarioID, &i.Email, &i.AtualizadoEm)
	return i, err
}

const salvarInscricao = `-- name: SalvarInscricao :exec
INSERT INTO push_inscricoes (usuario_id, endpoint, p256dh, auth)
VALUES ($1, $2, $3, $4)
ON CONFLICT (usuario_id, endpoint) DO UPDATE SET p256dh = excluded.p256dh, auth = excluded.auth
`

type SalvarInscricaoParams struct {
	UsuarioID uuid.UUID
	Endpoint  string
	P256dh    string
	Auth      string
}

func (q *Queries) SalvarInscricao(ctx context.Context, arg SalvarInscricaoParams) error {
	_, err := q.db.Exec(ctx, salvarInscricao,
		arg.UsuarioID,
		arg.Endpoint,
		arg.P256dh,
		arg.Auth,
	)
	return err
}

const salvarPreferencias = `-- name: SalvarPreferencias :one
INSERT INTO preferencias_notificacao (usuario_id, email)
VALUES ($1, $2)
ON CONFLICT (usuario_id) DO UPDATE SET email = excluded.email, atualizado_em = now()
RETURNING usuario_id, email, atualizado_em
`

type SalvarPreferenciasParams struct {
	UsuarioID uuid.UUID
	Email     bool
}

func (q *Queries) SalvarPreferencias(ctx context.Context, arg SalvarPreferenciasParams) (PreferenciaNotificacao, error) {
	row := q.db.QueryRow(ctx, salvarPreferencias, arg.UsuarioID, arg.Email)
	var i PreferenciaNotificacao
	err := row.Scan(&i.UsuarioID, &i.Email, &i.AtualizadoEm)
	return i, err
}
