// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: midia.sql

package midiadb

import (
	"context"

	"github.com/google/uuid"
)

const apagarVideo = `-- name: ApagarVideo :execrows
DELETE FROM videos WHERE id = $1 AND workspace_id = $2 AND dono_id = $3
`

type ApagarVideoParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	DonoID      uuid.UUID
}

func (q *Queries) ApagarVideo(ctx context.Context, arg ApagarVideoParams) (int64, error) {
	result, err := q.db.Exec(ctx, apagarVideo, arg.ID, arg.WorkspaceID, arg.DonoID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const compartilhar = `-- name: Compartilhar :execrows
UPDATE videos SET compartilhado = $1, atualizado_em = now()
WHERE id = $2 AND workspace_id = $3 AND dono_id = $4
`

type CompartilharParams struct {
	Compartilhado bool
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
	DonoID        uuid.UUID
}

func (q *Queries) Compartilhar(ctx context.Context, arg CompartilharParams) (int64, error) {
	result, err := q.db.Exec(ctx, compartilhar,
		arg.Compartilhado,
		arg.ID,
		arg.WorkspaceID,
		arg.DonoID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const concluirUpload = `-- name: ConcluirUpload :exec
UPDATE videos SET status = 'processando', upload_id = NULL, tamanho_bytes = $1, atualizado_em = now()
WHERE id = $2 AND workspace_id = $3 AND dono_id = $4
`

type ConcluirUploadParams struct {
	TamanhoBytes int64
	ID           uuid.UUID
	WorkspaceID  uuid.UUID
	DonoID       uuid.UUID
}

func (q *Queries) ConcluirUpload(ctx context.Context, arg ConcluirUploadParams) error {
	_, err := q.db.Exec(ctx, concluirUpload,
		arg.TamanhoBytes,
		arg.ID,
		arg.WorkspaceID,
		arg.DonoID,
	)
	return err
}

const criarEmbed = `-- name: CriarEmbed :one

INSERT INTO videos (workspace_id, dono_id, tipo, plataforma, status, titulo, autor, url, embed_id, thumb_url, verificado_em)
VALUES ($1, $2, 'embed', $3, 'pronto', $4, $5, $6, $7, $8, now())
ON CONFLICT (workspace_id, dono_id, plataforma, embed_id) WHERE tipo = 'embed'
DO UPDATE SET titulo = excluded.titulo, autor = excluded.autor, url = excluded.url,
    thumb_url = excluded.thumb_url, status = 'pronto', verificado_em = now(), atualizado_em = now()
RETURNING id, (xmax = 0)::boolean AS criado
`

type CriarEmbedParams struct {
	WorkspaceID uuid.UUID
	DonoID      uuid.UUID
	Plataforma  string
	Titulo      string
	Autor       string
	Url         *string
	EmbedID     *string
	ThumbUrl    *string
}

type CriarEmbedRow struct {
	ID     uuid.UUID
	Criado bool
}

// Queries do módulo midia. Toda query filtra por workspace_id, além da RLS
// (que mostra ao usuário os vídeos dele e os compartilhados no workspace).
// Colar de novo o mesmo vídeo devolve o que já existe (xmax <> 0 no upsert).
func (q *Queries) CriarEmbed(ctx context.Context, arg CriarEmbedParams) (CriarEmbedRow, error) {
	row := q.db.QueryRow(ctx, criarEmbed,
		arg.WorkspaceID,
		arg.DonoID,
		arg.Plataforma,
		arg.Titulo,
		arg.Autor,
		arg.Url,
		arg.EmbedID,
		arg.ThumbUrl,
	)
	var i CriarEmbedRow
	err := row.Scan(&i.ID, &i.Criado)
	return i, err
}

const criarUpload = `-- name: CriarUpload :one
INSERT INTO videos (id, workspace_id, dono_id, tipo, plataforma, status, titulo, storage_key, upload_id,
                    nome_arquivo, content_type, tamanho_bytes, direito_uso_em)
VALUES ($1, $2, $3, 'upload', 'upload', 'enviando', $4, $5, $6,
        $7, $8, $9, now())
RETURNING id, workspace_id, dono_id, tipo, plataforma, status, titulo, autor, compartilhado, url, embed_id, thumb_url, verificado_em, storage_key, upload_id, nome_arquivo, content_type, tamanho_bytes, duracao_s, largura, altura, direito_uso_em, criado_em, atualizado_em
`

type CriarUploadParams struct {
	ID           uuid.UUID
	WorkspaceID  uuid.UUID
	DonoID       uuid.UUID
	Titulo       string
	StorageKey   *string
	UploadID     *string
	NomeArquivo  *string
	ContentType  *string
	TamanhoBytes int64
}

func (q *Queries) CriarUpload(ctx context.Context, arg CriarUploadParams) (Video, error) {
	row := q.db.QueryRow(ctx, criarUpload,
		arg.ID,
		arg.WorkspaceID,
		arg.DonoID,
		arg.Titulo,
		arg.StorageKey,
		arg.UploadID,
		arg.NomeArquivo,
		arg.ContentType,
		arg.TamanhoBytes,
	)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DonoID,
		&i.Tipo,
		&i.Plataforma,
		&i.Status,
		&i.Titulo,
		&i.Autor,
		&i.Compartilhado,
		&i.Url,
		&i.EmbedID,
		&i.ThumbUrl,
		&i.VerificadoEm,
		&i.StorageKey,
		&i.UploadID,
		&i.NomeArquivo,
		&i.ContentType,
		&i.TamanhoBytes,
		&i.DuracaoS,
		&i.Largura,
		&i.Altura,
		&i.DireitoUsoEm,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const desvincular = `-- name: Desvincular :execrows
DELETE FROM video_vinculos
WHERE workspace_id = $1 AND video_id = $2 AND alvo_tipo = $3 AND alvo_id = $4
`

type DesvincularParams struct {
	WorkspaceID uuid.UUID
	VideoID     uuid.UUID
	AlvoTipo    VideoAlvo
	AlvoID      uuid.UUID
}

func (q *Queries) Desvincular(ctx context.Context, arg DesvincularParams) (int64, error) {
	result, err := q.db.Exec(ctx, desvincular,
		arg.WorkspaceID,
		arg.VideoID,
		arg.AlvoTipo,
		arg.AlvoID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const desvincularAlvo = `-- name: DesvincularAlvo :exec
DELETE FROM video_vinculos WHERE workspace_id = $1 AND alvo_tipo = $2 AND alvo_id = $3
`

type DesvincularAlvoParams struct {
	WorkspaceID uuid.UUID
	AlvoTipo    VideoAlvo
	AlvoID      uuid.UUID
}

func (q *Queries) DesvincularAlvo(ctx context.Context, arg DesvincularAlvoParams) error {
	_, err := q.db.Exec(ctx, desvincularAlvo, arg.WorkspaceID, arg.AlvoTipo, arg.AlvoID)
	return err
}

const marcarStatus = `-- name: MarcarStatus :exec
UPDATE videos SET status = $1, atualizado_em = now()
WHERE id = $2 AND workspace_id = $3 AND dono_id = $4
`

type MarcarStatusParams struct {
	Status      VideoStatus
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	DonoID      uuid.UUID
}

func (q *Queries) MarcarStatus(ctx context.Context, arg MarcarStatusParams) error {
	_, err := q.db.Exec(ctx, marcarStatus,
		arg.Status,
		arg.ID,
		arg.WorkspaceID,
		arg.DonoID,
	)
	return err
}

const processado = `-- name: Processado :exec
UPDATE videos SET status = 'pronto', duracao_s = $1, largura = $2, altura = $3, atualizado_em = now()
WHERE id = $4 AND workspace_id = $5 AND dono_id = $6
`

type ProcessadoParams struct {
	DuracaoS    *int32
	Largura     *int32
	Altura      *int32
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	DonoID      uuid.UUID
}

func (q *Queries) Processado(ctx context.Context, arg ProcessadoParams) error {
	_, err := q.db.Exec(ctx, processado,
		arg.DuracaoS,
		arg.Largura,
		arg.Altura,
		arg.ID,
		arg.WorkspaceID,
		arg.DonoID,
	)
	return err
}

const renomear = `-- name: Renomear :execrows
UPDATE videos SET titulo = $1, atualizado_em = now()
WHERE id = $2 AND workspace_id = $3 AND dono_id = $4
`

type RenomearParams struct {
	Titulo      string
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	DonoID      uuid.UUID
}

func (q *Queries) Renomear(ctx context.Context, arg RenomearParams) (int64, error) {
	result, err := q.db.Exec(ctx, renomear,
		arg.Titulo,
		arg.ID,
		arg.WorkspaceID,
		arg.DonoID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revalidado = `-- name: Revalidado :exec
UPDATE videos SET status = $1, titulo = coalesce($2, titulo),
    autor = coalesce($3, autor), thumb_url = coalesce($4, thumb_url),
    verificado_em = now(), atualizado_em = now()
WHERE id = $5 AND workspace_id = $6 AND dono_id = $7
`

type RevalidadoParams struct {
	Status      VideoStatus
	Titulo      *string
	Autor       *string
	ThumbUrl    *string
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	DonoID      uuid.UUID
}

func (q *Queries) Revalidado(ctx context.Context, arg RevalidadoParams) error {
	_, err := q.db.Exec(ctx, revalidado,
		arg.Status,
		arg.Titulo,
		arg.Autor,
		arg.ThumbUrl,
		arg.ID,
		arg.WorkspaceID,
		arg.DonoID,
	)
	return err
}

const somarUso = `-- name: SomarUso :one
INSERT INTO uso_videos (workspace_id, bytes) VALUES ($1, greatest($2::bigint, 0))
ON CONFLICT (workspace_id) DO UPDATE SET bytes = greatest(uso_videos.bytes + $2::bigint, 0)
RETURNING bytes
`

type SomarUsoParams struct {
	WorkspaceID uuid.UUID
	Delta       int64
}

// Soma (ou subtrai) bytes do uso do workspace e devolve o novo total.
func (q *Queries) SomarUso(ctx context.Context, arg SomarUsoParams) (int64, error) {
	row := q.db.QueryRow(ctx, somarUso, arg.WorkspaceID, arg.Delta)
	var bytes int64
	err := row.Scan(&bytes)
	return bytes, err
}

const travarVideo = `-- name: TravarVideo :one
SELECT id, workspace_id, dono_id, tipo, plataforma, status, titulo, autor, compartilhado, url, embed_id, thumb_url, verificado_em, storage_key, upload_id, nome_arquivo, content_type, tamanho_bytes, duracao_s, largura, altura, direito_uso_em, criado_em, atualizado_em FROM videos WHERE id = $1 AND workspace_id = $2 AND dono_id = $3 FOR UPDATE
`

type TravarVideoParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	DonoID      uuid.UUID
}

func (q *Queries) TravarVideo(ctx context.Context, arg TravarVideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, travarVideo, arg.ID, arg.WorkspaceID, arg.DonoID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DonoID,
		&i.Tipo,
		&i.Plataforma,
		&i.Status,
		&i.Titulo,
		&i.Autor,
		&i.Compartilhado,
		&i.Url,
		&i.EmbedID,
		&i.ThumbUrl,
		&i.VerificadoEm,
		&i.StorageKey,
		&i.UploadID,
		&i.NomeArquivo,
		&i.ContentType,
		&i.TamanhoBytes,
		&i.DuracaoS,
		&i.Largura,
		&i.Altura,
		&i.DireitoUsoEm,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const uso = `-- name: Uso :one
SELECT coalesce((SELECT bytes FROM uso_videos WHERE workspace_id = $1), 0)::bigint
`

func (q *Queries) Uso(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, uso, workspaceID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const video = `-- name: Video :one
SELECT id, workspace_id, dono_id, tipo, plataforma, status, titulo, autor, compartilhado, url, embed_id, thumb_url, verificado_em, storage_key, upload_id, nome_arquivo, content_type, tamanho_bytes, duracao_s, largura, altura, direito_uso_em, criado_em, atualizado_em FROM videos WHERE id = $1 AND workspace_id = $2
`

type VideoParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) Video(ctx context.Context, arg VideoParams) (Video, error) {
	row := q.db.QueryRow(ctx, video, arg.ID, arg.WorkspaceID)
	var i Video
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DonoID,
		&i.Tipo,
		&i.Plataforma,
		&i.Status,
		&i.Titulo,
		&i.Autor,
		&i.Compartilhado,
		&i.Url,
		&i.EmbedID,
		&i.ThumbUrl,
		&i.VerificadoEm,
		&i.StorageKey,
		&i.UploadID,
		&i.NomeArquivo,
		&i.ContentType,
		&i.TamanhoBytes,
		&i.DuracaoS,
		&i.Largura,
		&i.Altura,
		&i.DireitoUsoEm,
		&i.CriadoEm,
		&i.AtualizadoEm,
	)
	return i, err
}

const videos = `-- name: Videos :many
SELECT id, workspace_id, dono_id, tipo, plataforma, status, titulo, autor, compartilhado, url, embed_id, thumb_url, verificado_em, storage_key, upload_id, nome_arquivo, content_type, tamanho_bytes, duracao_s, largura, altura, direito_uso_em, criado_em, atualizado_em FROM videos
WHERE workspace_id = $1
  AND (NOT $2::boolean OR dono_id = $3)
ORDER BY criado_em DESC, id
LIMIT 500
`

type VideosParams struct {
	WorkspaceID uuid.UUID
	SoMeus      bool
	DonoID      uuid.UUID
}

// Os vídeos que o usuário vê no workspace: os dele e os compartilhados.
func (q *Queries) Videos(ctx context.Context, arg VideosParams) ([]Video, error) {
	rows, err := q.db.Query(ctx, videos, arg.WorkspaceID, arg.SoMeus, arg.DonoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Video
	for rows.Next() {
		var i Video
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DonoID,
			&i.Tipo,
			&i.Plataforma,
			&i.Status,
			&i.Titulo,
			&i.Autor,
			&i.Compartilhado,
			&i.Url,
			&i.EmbedID,
			&i.ThumbUrl,
			&i.VerificadoEm,
			&i.StorageKey,
			&i.UploadID,
			&i.NomeArquivo,
			&i.ContentType,
			&i.TamanhoBytes,
			&i.DuracaoS,
			&i.Largura,
			&i.Altura,
			&i.DireitoUsoEm,
			&i.CriadoEm,
			&i.AtualizadoEm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const videosDosAlvos = `-- name: VideosDosAlvos :many
SELECT v.id, v.workspace_id, v.dono_id, v.tipo, v.plataforma, v.status, v.titulo, v.autor, v.compartilhado, v.url, v.embed_id, v.thumb_url, v.verificado_em, v.storage_key, v.upload_id, v.nome_arquivo, v.content_type, v.tamanho_bytes, v.duracao_s, v.largura, v.altura, v.direito_uso_em, v.criado_em, v.atualizado_em, vv.alvo_tipo, vv.alvo_id FROM video_vinculos vv
JOIN videos v ON v.id = vv.video_id AND v.workspace_id = vv.workspace_id
WHERE vv.workspace_id = $1
  AND vv.alvo_tipo = $2
  AND vv.alvo_id = ANY($3::uuid[])
ORDER BY vv.criado_em, v.id
`

type VideosDosAlvosParams struct {
	WorkspaceID uuid.UUID
	AlvoTipo    VideoAlvo
	AlvoIds     []uuid.UUID
}

type VideosDosAlvosRow struct {
	Video    Video
	AlvoTipo VideoAlvo
	AlvoID   uuid.UUID
}

// Os vídeos ligados a algum destes alvos, com o alvo de cada ligação.
func (q *Queries) VideosDosAlvos(ctx context.Context, arg VideosDosAlvosParams) ([]VideosDosAlvosRow, error) {
	rows, err := q.db.Query(ctx, videosDosAlvos, arg.WorkspaceID, arg.AlvoTipo, arg.AlvoIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VideosDosAlvosRow
	for rows.Next() {
		var i VideosDosAlvosRow
		if err := rows.Scan(
			&i.Video.ID,
			&i.Video.WorkspaceID,
			&i.Video.DonoID,
			&i.Video.Tipo,
			&i.Video.Plataforma,
			&i.Video.Status,
			&i.Video.Titulo,
			&i.Video.Autor,
			&i.Video.Compartilhado,
			&i.Video.Url,
			&i.Video.EmbedID,
			&i.Video.ThumbUrl,
			&i.Video.VerificadoEm,
			&i.Video.StorageKey,
			&i.Video.UploadID,
			&i.Video.NomeArquivo,
			&i.Video.ContentType,
			&i.Video.TamanhoBytes,
			&i.Video.DuracaoS,
			&i.Video.Largura,
			&i.Video.Altura,
			&i.Video.DireitoUsoEm,
			&i.Video.CriadoEm,
			&i.Video.AtualizadoEm,
			&i.AlvoTipo,
			&i.AlvoID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const vincular = `-- name: Vincular :execrows
INSERT INTO video_vinculos (video_id, workspace_id, dono_id, alvo_tipo, alvo_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
`

type VincularParams struct {
	VideoID     uuid.UUID
	WorkspaceID uuid.UUID
	DonoID      uuid.UUID
	AlvoTipo    VideoAlvo
	AlvoID      uuid.UUID
}

func (q *Queries) Vincular(ctx context.Context, arg VincularParams) (int64, error) {
	result, err := q.db.Exec(ctx, vincular,
		arg.VideoID,
		arg.WorkspaceID,
		arg.DonoID,
		arg.AlvoTipo,
		arg.AlvoID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const vinculosDosVideos = `-- name: VinculosDosVideos :many
SELECT video_id, alvo_tipo, alvo_id FROM video_vinculos
WHERE workspace_id = $1 AND video_id = ANY($2::uuid[])
ORDER BY criado_em
`

type VinculosDosVideosParams struct {
	WorkspaceID uuid.UUID
	VideoIds    []uuid.UUID
}

type VinculosDosVideosRow struct {
	VideoID  uuid.UUID
	AlvoTipo VideoAlvo
	AlvoID   uuid.UUID
}

func (q *Queries) VinculosDosVideos(ctx context.Context, arg VinculosDosVideosParams) ([]VinculosDosVideosRow, error) {
	rows, err := q.db.Query(ctx, vinculosDosVideos, arg.WorkspaceID, arg.VideoIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VinculosDosVideosRow
	for rows.Next() {
		var i VinculosDosVideosRow
		if err := rows.Scan(&i.VideoID, &i.AlvoTipo, &i.AlvoID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
