// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assinaturas.sql

package assinaturasdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assinatura = `-- name: Assinatura :one

SELECT workspace_id, provedor, cliente_externo_id, externo_id, status, assentos, valor_centavos, proximo_ciclo, url_pagamento, criado_por, criada_em, atualizada_em, cancelada_em FROM assinaturas WHERE workspace_id = $1
`

// Queries do módulo assinaturas. Gere o código com `make sqlc`.
func (q *Queries) Assinatura(ctx context.Context, workspaceID uuid.UUID) (Assinatura, error) {
	row := q.db.QueryRow(ctx, assinatura, workspaceID)
	var i Assinatura
	err := row.Scan(
		&i.WorkspaceID,
		&i.Provedor,
		&i.ClienteExternoID,
		&i.ExternoID,
		&i.Status,
		&i.Assentos,
		&i.ValorCentavos,
		&i.ProximoCiclo,
		&i.UrlPagamento,
		&i.CriadoPor,
		&i.CriadaEm,
		&i.AtualizadaEm,
		&i.CanceladaEm,
	)
	return i, err
}

const assinaturaPorExterno = `-- name: AssinaturaPorExterno :one
SELECT workspace_id, provedor, cliente_externo_id, externo_id, status, assentos, valor_centavos, proximo_ciclo, url_pagamento, criado_por, criada_em, atualizada_em, cancelada_em FROM assinaturas WHERE provedor = $1 AND externo_id = $2
`

type AssinaturaPorExternoParams struct {
	Provedor  string
	ExternoID string
}

func (q *Queries) AssinaturaPorExterno(ctx context.Context, arg AssinaturaPorExternoParams) (Assinatura, error) {
	row := q.db.QueryRow(ctx, assinaturaPorExterno, arg.Provedor, arg.ExternoID)
	var i Assinatura
	err := row.Scan(
		&i.WorkspaceID,
		&i.Provedor,
		&i.ClienteExternoID,
		&i.ExternoID,
		&i.Status,
		&i.Assentos,
		&i.ValorCentavos,
		&i.ProximoCiclo,
		&i.UrlPagamento,
		&i.CriadoPor,
		&i.CriadaEm,
		&i.AtualizadaEm,
		&i.CanceladaEm,
	)
	return i, err
}

const atualizarCobranca = `-- name: AtualizarCobranca :one
UPDATE assinaturas
SET status = $1,
    proximo_ciclo = coalesce($2, proximo_ciclo),
    url_pagamento = coalesce($3, url_pagamento),
    atualizada_em = now()
WHERE workspace_id = $4
RETURNING workspace_id, provedor, cliente_externo_id, externo_id, status, assentos, valor_centavos, proximo_ciclo, url_pagamento, criado_por, criada_em, atualizada_em, cancelada_em
`

type AtualizarCobrancaParams struct {
	Status       AssinaturaStatus
	ProximoCiclo pgtype.Date
	UrlPagamento *string
	WorkspaceID  uuid.UUID
}

// Situação vinda do gateway. url_pagamento nula mantém a atual (um aviso de
// pagamento confirmado não traz fatura em aberto).
func (q *Queries) AtualizarCobranca(ctx context.Context, arg AtualizarCobrancaParams) (Assinatura, error) {
	row := q.db.QueryRow(ctx, atualizarCobranca,
		arg.Status,
		arg.ProximoCiclo,
		arg.UrlPagamento,
		arg.WorkspaceID,
	)
	var i Assinatura
	err := row.Scan(
		&i.WorkspaceID,
		&i.Provedor,
		&i.ClienteExternoID,
		&i.ExternoID,
		&i.Status,
		&i.Assentos,
		&i.ValorCentavos,
		&i.ProximoCiclo,
		&i.UrlPagamento,
		&i.CriadoPor,
		&i.CriadaEm,
		&i.AtualizadaEm,
		&i.CanceladaEm,
	)
	return i, err
}

const atualizarPlano = `-- name: AtualizarPlano :one
UPDATE assinaturas
SET assentos = $1,
    valor_centavos = $2,
    atualizada_em = now()
WHERE workspace_id = $3 AND cancelada_em IS NULL
RETURNING workspace_id, provedor, cliente_externo_id, externo_id, status, assentos, valor_centavos, proximo_ciclo, url_pagamento, criado_por, criada_em, atualizada_em, cancelada_em
`

type AtualizarPlanoParams struct {
	Assentos      int32
	ValorCentavos int64
	WorkspaceID   uuid.UUID
}

// Muda assentos e valor de uma assinatura em andamento (mais ou menos
// afiliados na turma).
func (q *Queries) AtualizarPlano(ctx context.Context, arg AtualizarPlanoParams) (Assinatura, error) {
	row := q.db.QueryRow(ctx, atualizarPlano, arg.Assentos, arg.ValorCentavos, arg.WorkspaceID)
	var i Assinatura
	err := row.Scan(
		&i.WorkspaceID,
		&i.Provedor,
		&i.ClienteExternoID,
		&i.ExternoID,
		&i.Status,
		&i.Assentos,
		&i.ValorCentavos,
		&i.ProximoCiclo,
		&i.UrlPagamento,
		&i.CriadoPor,
		&i.CriadaEm,
		&i.AtualizadaEm,
		&i.CanceladaEm,
	)
	return i, err
}

const cancelarAssinatura = `-- name: CancelarAssinatura :one
UPDATE assinaturas
SET status = 'cancelada',
    url_pagamento = NULL,
    cancelada_em = now(),
    atualizada_em = now()
WHERE workspace_id = $1 AND cancelada_em IS NULL
RETURNING workspace_id, provedor, cliente_externo_id, externo_id, status, assentos, valor_centavos, proximo_ciclo, url_pagamento, criado_por, criada_em, atualizada_em, cancelada_em
`

func (q *Queries) CancelarAssinatura(ctx context.Context, workspaceID uuid.UUID) (Assinatura, error) {
	row := q.db.QueryRow(ctx, cancelarAssinatura, workspaceID)
	var i Assinatura
	err := row.Scan(
		&i.WorkspaceID,
		&i.Provedor,
		&i.ClienteExternoID,
		&i.ExternoID,
		&i.Status,
		&i.Assentos,
		&i.ValorCentavos,
		&i.ProximoCiclo,
		&i.UrlPagamento,
		&i.CriadoPor,
		&i.CriadaEm,
		&i.AtualizadaEm,
		&i.CanceladaEm,
	)
	return i, err
}

const registrarEvento = `-- name: RegistrarEvento :execrows
INSERT INTO eventos_cobranca (provedor, evento_id, workspace_id, tipo)
VALUES ($1, $2, $3, $4)
ON CONFLICT (provedor, evento_id) DO NOTHING
`

type RegistrarEventoParams struct {
	Provedor    string
	EventoID    string
	WorkspaceID uuid.UUID
	Tipo        string
}

// Devolve 0 quando o evento já tinha sido processado (reenvio do gateway).
func (q *Queries) RegistrarEvento(ctx context.Context, arg RegistrarEventoParams) (int64, error) {
	result, err := q.db.Exec(ctx, registrarEvento,
		arg.Provedor,
		arg.EventoID,
		arg.WorkspaceID,
		arg.Tipo,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const salvarAssinatura = `-- name: SalvarAssinatura :one
INSERT INTO assinaturas (
    workspace_id, provedor, cliente_externo_id, externo_id, status,
    assentos, valor_centavos, proximo_ciclo, url_pagamento, criado_por
) VALUES ($1, $2, $3, $4, 'aguardando', $5, $6, $7, $8, $9)
ON CONFLICT (workspace_id) DO UPDATE
    SET provedor = EXCLUDED.provedor,
        cliente_externo_id = EXCLUDED.cliente_externo_id,
        externo_id = EXCLUDED.externo_id,
        status = 'aguardando',
        assentos = EXCLUDED.assentos,
        valor_centavos = EXCLUDED.valor_centavos,
        proximo_ciclo = EXCLUDED.proximo_ciclo,
        url_pagamento = EXCLUDED.url_pagamento,
        criado_por = EXCLUDED.criado_por,
        atualizada_em = now(),
        cancelada_em = NULL
    WHERE assinaturas.cancelada_em IS NOT NULL
RETURNING workspace_id, provedor, cliente_externo_id, externo_id, status, assentos, valor_centavos, proximo_ciclo, url_pagamento, criado_por, criada_em, atualizada_em, cancelada_em
`

type SalvarAssinaturaParams struct {
	WorkspaceID      uuid.UUID
	Provedor         string
	ClienteExternoID string
	ExternoID        string
	Assentos         int32
	ValorCentavos    int64
	ProximoCiclo     pgtype.Date
	UrlPagamento     *string
	CriadoPor        uuid.UUID
}

// Grava a assinatura do workspace. Uma nova só substitui uma cancelada: sem
// linha devolvida, já existe uma em andamento.
func (q *Queries) SalvarAssinatura(ctx context.Context, arg SalvarAssinaturaParams) (Assinatura, error) {
	row := q.db.QueryRow(ctx, salvarAssinatura,
		arg.WorkspaceID,
		arg.Provedor,
		arg.ClienteExternoID,
		arg.ExternoID,
		arg.Assentos,
		arg.ValorCentavos,
		arg.ProximoCiclo,
		arg.UrlPagamento,
		arg.CriadoPor,
	)
	var i Assinatura
	err := row.Scan(
		&i.WorkspaceID,
		&i.Provedor,
		&i.ClienteExternoID,
		&i.ExternoID,
		&i.Status,
		&i.Assentos,
		&i.ValorCentavos,
		&i.ProximoCiclo,
		&i.UrlPagamento,
		&i.CriadoPor,
		&i.CriadaEm,
		&i.AtualizadaEm,
		&i.CanceladaEm,
	)
	return i, err
}
