// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: batch.go

package tendenciasdb

import (
	"context"
	"errors"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const upsertTendencia = `-- name: UpsertTendencia :batchexec
INSERT INTO tendencias (
    produto_id, calculado_em, score, ganho_por_venda_centavos, variacao_vendas_7d,
    nome, loja_nome, imagem_url, categoria_id, categorias, url,
    preco_min_centavos, preco_max_centavos, comissao_bp, vendas, nota, atualizado_em
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16, $17
)
ON CONFLICT (produto_id) DO UPDATE SET
    calculado_em = excluded.calculado_em,
    score = excluded.score,
    ganho_por_venda_centavos = excluded.ganho_por_venda_centavos,
    variacao_vendas_7d = excluded.variacao_vendas_7d,
    nome = excluded.nome,
    loja_nome = excluded.loja_nome,
    imagem_url = excluded.imagem_url,
    categoria_id = excluded.categoria_id,
    categorias = excluded.categorias,
    url = excluded.url,
    preco_min_centavos = excluded.preco_min_centavos,
    preco_max_centavos = excluded.preco_max_centavos,
    comissao_bp = excluded.comissao_bp,
    vendas = excluded.vendas,
    nota = excluded.nota,
    atualizado_em = excluded.atualizado_em
`

type UpsertTendenciaBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertTendenciaParams struct {
	ProdutoID             uuid.UUID
	CalculadoEm           time.Time
	Score                 float64
	GanhoPorVendaCentavos int64
	VariacaoVendas7d      *int64
	Nome                  string
	LojaNome              string
	ImagemUrl             *string
	CategoriaID           *int64
	Categorias            []int64
	Url                   string
	PrecoMinCentavos      int64
	PrecoMaxCentavos      int64
	ComissaoBp            int32
	Vendas                int64
	Nota                  *float64
	AtualizadoEm          time.Time
}

func (q *Queries) UpsertTendencia(ctx context.Context, arg []UpsertTendenciaParams) *UpsertTendenciaBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.ProdutoID,
			a.CalculadoEm,
			a.Score,
			a.GanhoPorVendaCentavos,
			a.VariacaoVendas7d,
			a.Nome,
			a.LojaNome,
			a.ImagemUrl,
			a.CategoriaID,
			a.Categorias,
			a.Url,
			a.PrecoMinCentavos,
			a.PrecoMaxCentavos,
			a.ComissaoBp,
			a.Vendas,
			a.Nota,
			a.AtualizadoEm,
		}
		batch.Queue(upsertTendencia, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertTendenciaBatchResults{br, len(arg), false}
}

func (b *UpsertTendenciaBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertTendenciaBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
