// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tendencias.sql

package tendenciasdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const categoriasDoRadar = `-- name: CategoriasDoRadar :many
SELECT categoria_id::bigint AS id, count(*) AS produtos
FROM tendencias
WHERE categoria_id IS NOT NULL
GROUP BY categoria_id
ORDER BY produtos DESC, categoria_id
`

type CategoriasDoRadarRow struct {
	ID       int64
	Produtos int64
}

func (q *Queries) CategoriasDoRadar(ctx context.Context) ([]CategoriasDoRadarRow, error) {
	rows, err := q.db.Query(ctx, categoriasDoRadar)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CategoriasDoRadarRow
	for rows.Next() {
		var i CategoriasDoRadarRow
		if err := rows.Scan(&i.ID, &i.Produtos); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const radar = `-- name: Radar :many
SELECT
    produto_id, nome, imagem_url, loja_nome, url, categorias,
    preco_min_centavos, preco_max_centavos, comissao_bp, ganho_por_venda_centavos,
    vendas, nota, score, variacao_vendas_7d, atualizado_em,
    count(*) OVER () AS total
FROM tendencias
WHERE ($1::bigint IS NULL OR $1::bigint = ANY (categorias))
  AND ($2::bigint IS NULL OR preco_min_centavos >= $2::bigint)
  AND ($3::bigint IS NULL OR preco_min_centavos <= $3::bigint)
  AND ($4::integer IS NULL OR comissao_bp >= $4::integer)
  AND ($5::numeric IS NULL OR nota >= $5::numeric)
  AND (
    $6::text IS NULL
    OR busca @@ websearch_to_tsquery('portuguese', $6::text)
    OR nome ILIKE $7::text ESCAPE '\'
    OR loja_nome ILIKE $7::text ESCAPE '\'
  )
ORDER BY
    CASE WHEN $8::text = 'comissao' THEN comissao_bp END DESC,
    CASE WHEN $8::text = 'ganho' THEN ganho_por_venda_centavos END DESC,
    CASE WHEN $8::text = 'vendas' THEN vendas END DESC,
    score DESC, vendas DESC, produto_id
LIMIT $10 OFFSET $9
`

type RadarParams struct {
	Categoria    *int64
	PrecoMin     *int64
	PrecoMax     *int64
	ComissaoMin  *int32
	NotaMin      *float64
	Busca        *string
	Padrao       *string
	Ordem        string
	Deslocamento int32
	Limite       int32
}

type RadarRow struct {
	ProdutoID             uuid.UUID
	Nome                  string
	ImagemUrl             *string
	LojaNome              string
	Url                   string
	Categorias            []int64
	PrecoMinCentavos      int64
	PrecoMaxCentavos      int64
	ComissaoBp            int32
	GanhoPorVendaCentavos int64
	Vendas                int64
	Nota                  *float64
	Score                 float64
	VariacaoVendas7d      *int64
	AtualizadoEm          time.Time
	Total                 int64
}

func (q *Queries) Radar(ctx context.Context, arg RadarParams) ([]RadarRow, error) {
	rows, err := q.db.Query(ctx, radar,
		arg.Categoria,
		arg.PrecoMin,
		arg.PrecoMax,
		arg.ComissaoMin,
		arg.NotaMin,
		arg.Busca,
		arg.Padrao,
		arg.Ordem,
		arg.Deslocamento,
		arg.Limite,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RadarRow
	for rows.Next() {
		var i RadarRow
		if err := rows.Scan(
			&i.ProdutoID,
			&i.Nome,
			&i.ImagemUrl,
			&i.LojaNome,
			&i.Url,
			&i.Categorias,
			&i.PrecoMinCentavos,
			&i.PrecoMaxCentavos,
			&i.ComissaoBp,
			&i.GanhoPorVendaCentavos,
			&i.Vendas,
			&i.Nota,
			&i.Score,
			&i.VariacaoVendas7d,
			&i.AtualizadoEm,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const radarAtualizadoEm = `-- name: RadarAtualizadoEm :one
SELECT atualizado_em FROM tendencias ORDER BY atualizado_em DESC LIMIT 1
`

func (q *Queries) RadarAtualizadoEm(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, radarAtualizadoEm)
	var atualizado_em time.Time
	err := row.Scan(&atualizado_em)
	return atualizado_em, err
}

const radarItem = `-- name: RadarItem :one
SELECT
    produto_id, nome, imagem_url, loja_nome, url, categorias,
    preco_min_centavos, preco_max_centavos, comissao_bp, ganho_por_venda_centavos,
    vendas, nota, score, variacao_vendas_7d, atualizado_em
FROM tendencias WHERE produto_id = $1
`

type RadarItemRow struct {
	ProdutoID             uuid.UUID
	Nome                  string
	ImagemUrl             *string
	LojaNome              string
	Url                   string
	Categorias            []int64
	PrecoMinCentavos      int64
	PrecoMaxCentavos      int64
	ComissaoBp            int32
	GanhoPorVendaCentavos int64
	Vendas                int64
	Nota                  *float64
	Score                 float64
	VariacaoVendas7d      *int64
	AtualizadoEm          time.Time
}

func (q *Queries) RadarItem(ctx context.Context, produtoID uuid.UUID) (RadarItemRow, error) {
	row := q.db.QueryRow(ctx, radarItem, produtoID)
	var i RadarItemRow
	err := row.Scan(
		&i.ProdutoID,
		&i.Nome,
		&i.ImagemUrl,
		&i.LojaNome,
		&i.Url,
		&i.Categorias,
		&i.PrecoMinCentavos,
		&i.PrecoMaxCentavos,
		&i.ComissaoBp,
		&i.GanhoPorVendaCentavos,
		&i.Vendas,
		&i.Nota,
		&i.Score,
		&i.VariacaoVendas7d,
		&i.AtualizadoEm,
	)
	return i, err
}

const removerTendenciasAntigas = `-- name: RemoverTendenciasAntigas :execrows
DELETE FROM tendencias WHERE calculado_em < $1
`

func (q *Queries) RemoverTendenciasAntigas(ctx context.Context, calculadoEm time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, removerTendenciasAntigas, calculadoEm)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
