-- Collections: the products an affiliate saved to promote, with title,
-- description, notes, tags, status and affiliate link, and the folders
-- (collections) they organize them in.
--
-- Saved items belong to the user inside each workspace: the policies require
-- the workspace of the request AND the user. The mentor does not see the
-- affiliate's items or notes. Child tables repeat workspace_id and user_id and
-- tie them to the parent with a composite foreign key, so the policy applies
-- to each row without a subquery.

-- +goose Up
CREATE TYPE item_status AS ENUM ('testing', 'winner', 'discarded');
CREATE TYPE link_origin AS ENUM ('auto', 'manual');
-- pending: no Shopee credential; generating: generate_affiliate_link job
-- queued; ready: link available; failed: Shopee did not generate it after the
-- retries.
CREATE TYPE link_status AS ENUM ('pending', 'generating', 'ready', 'failed');
CREATE TYPE channel AS ENUM ('instagram', 'tiktok', 'whatsapp', 'other');

CREATE TABLE saved_items (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id   uuid NOT NULL REFERENCES workspaces (id) ON DELETE CASCADE,
    user_id        uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    product_id     uuid NOT NULL REFERENCES products (id),
    title          text NOT NULL DEFAULT '' CHECK (length(title) <= 200),
    description    text NOT NULL DEFAULT '' CHECK (length(description) <= 2000),
    notes          text NOT NULL DEFAULT '' CHECK (length(notes) <= 5000),
    tags           text[] NOT NULL DEFAULT '{}',
    status         item_status NOT NULL DEFAULT 'testing',
    affiliate_link text,
    link_origin    link_origin NOT NULL DEFAULT 'auto',
    link_status    link_status NOT NULL,
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    UNIQUE (workspace_id, user_id, product_id),
    UNIQUE (id, workspace_id, user_id)
);

CREATE INDEX saved_items_owner ON saved_items (workspace_id, user_id, created_at DESC);
CREATE INDEX saved_items_tags ON saved_items USING gin (tags);

CREATE TABLE collections (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    workspace_id uuid NOT NULL REFERENCES workspaces (id) ON DELETE CASCADE,
    user_id      uuid NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name         text NOT NULL CHECK (length(name) BETWEEN 1 AND 60),
    created_at   timestamptz NOT NULL DEFAULT now(),
    UNIQUE (id, workspace_id, user_id)
);

CREATE UNIQUE INDEX collections_unique_name ON collections (workspace_id, user_id, lower(name));

CREATE TABLE collection_items (
    collection_id uuid NOT NULL,
    item_id       uuid NOT NULL,
    workspace_id  uuid NOT NULL,
    user_id       uuid NOT NULL,
    added_at      timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (collection_id, item_id),
    FOREIGN KEY (collection_id, workspace_id, user_id)
        REFERENCES collections (id, workspace_id, user_id) ON DELETE CASCADE,
    FOREIGN KEY (item_id, workspace_id, user_id)
        REFERENCES saved_items (id, workspace_id, user_id) ON DELETE CASCADE
);

CREATE INDEX collection_items_item ON collection_items (item_id);

-- Automatic link per channel, generated by the generate_affiliate_link job with
-- the user's credential and one subId per channel.
CREATE TABLE channel_links (
    item_id      uuid NOT NULL,
    workspace_id uuid NOT NULL,
    user_id      uuid NOT NULL,
    channel      channel NOT NULL,
    sub_id       text NOT NULL,
    url          text NOT NULL,
    generated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (item_id, channel),
    FOREIGN KEY (item_id, workspace_id, user_id)
        REFERENCES saved_items (id, workspace_id, user_id) ON DELETE CASCADE
);

GRANT SELECT, INSERT, UPDATE, DELETE ON saved_items, collections, collection_items, channel_links TO parceiros_app;

ALTER TABLE saved_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE saved_items FORCE ROW LEVEL SECURITY;
ALTER TABLE collections ENABLE ROW LEVEL SECURITY;
ALTER TABLE collections FORCE ROW LEVEL SECURITY;
ALTER TABLE collection_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE collection_items FORCE ROW LEVEL SECURITY;
ALTER TABLE channel_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE channel_links FORCE ROW LEVEL SECURITY;

CREATE POLICY saved_items_owner ON saved_items
    USING (workspace_id = app_workspace_id() AND user_id = app_user_id())
    WITH CHECK (workspace_id = app_workspace_id() AND user_id = app_user_id());
CREATE POLICY collections_owner ON collections
    USING (workspace_id = app_workspace_id() AND user_id = app_user_id())
    WITH CHECK (workspace_id = app_workspace_id() AND user_id = app_user_id());
CREATE POLICY collection_items_owner ON collection_items
    USING (workspace_id = app_workspace_id() AND user_id = app_user_id())
    WITH CHECK (workspace_id = app_workspace_id() AND user_id = app_user_id());
CREATE POLICY channel_links_owner ON channel_links
    USING (workspace_id = app_workspace_id() AND user_id = app_user_id())
    WITH CHECK (workspace_id = app_workspace_id() AND user_id = app_user_id());

-- +goose Down
DROP TABLE channel_links;
DROP TABLE collection_items;
DROP TABLE collections;
DROP TABLE saved_items;
DROP TYPE channel;
DROP TYPE link_status;
DROP TYPE link_origin;
DROP TYPE item_status;
