// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resultados.sql

package resultadosdb

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const concluirSincronizacao = `-- name: ConcluirSincronizacao :exec
INSERT INTO sincronizacoes (usuario_id, status, concluida_em, conversoes, erro)
VALUES ($1, $2, CASE WHEN $2 = 'ok' THEN $3::timestamptz END, $4, $5)
ON CONFLICT (usuario_id) DO UPDATE SET
    status = excluded.status,
    concluida_em = coalesce(excluded.concluida_em, sincronizacoes.concluida_em),
    conversoes = CASE WHEN excluded.status = 'ok' THEN excluded.conversoes ELSE sincronizacoes.conversoes END,
    erro = excluded.erro
`

type ConcluirSincronizacaoParams struct {
	UsuarioID  uuid.UUID
	Status     string
	Agora      time.Time
	Conversoes int32
	Erro       *string
}

// concluida_em e conversoes são da última sincronização que deu certo.
func (q *Queries) ConcluirSincronizacao(ctx context.Context, arg ConcluirSincronizacaoParams) error {
	_, err := q.db.Exec(ctx, concluirSincronizacao,
		arg.UsuarioID,
		arg.Status,
		arg.Agora,
		arg.Conversoes,
		arg.Erro,
	)
	return err
}

const iniciarSincronizacao = `-- name: IniciarSincronizacao :one
INSERT INTO sincronizacoes (usuario_id, status, pedida_em)
VALUES ($1, 'sincronizando', $2)
ON CONFLICT (usuario_id) DO UPDATE SET status = 'sincronizando', pedida_em = excluded.pedida_em, erro = NULL
RETURNING usuario_id, status, pedida_em, concluida_em, conversoes, erro
`

type IniciarSincronizacaoParams struct {
	UsuarioID uuid.UUID
	Agora     time.Time
}

func (q *Queries) IniciarSincronizacao(ctx context.Context, arg IniciarSincronizacaoParams) (Sincronizacao, error) {
	row := q.db.QueryRow(ctx, iniciarSincronizacao, arg.UsuarioID, arg.Agora)
	var i Sincronizacao
	err := row.Scan(
		&i.UsuarioID,
		&i.Status,
		&i.PedidaEm,
		&i.ConcluidaEm,
		&i.Conversoes,
		&i.Erro,
	)
	return i, err
}

const porCanal = `-- name: PorCanal :many
SELECT
    coalesce(canal::text, '')::text AS canal,
    count(DISTINCT pedido_id) FILTER (WHERE status <> 'cancelado')::bigint AS pedidos,
    coalesce(sum(comissao_centavos) FILTER (WHERE status <> 'cancelado'), 0)::bigint AS comissao_estimada_centavos,
    coalesce(sum(comissao_centavos) FILTER (WHERE status = 'concluido'), 0)::bigint AS comissao_validada_centavos
FROM conversoes
WHERE workspace_id = $1
  AND usuario_id = ANY($2::uuid[])
  AND ocorrido_em >= $3 AND ocorrido_em < $4
GROUP BY 1
HAVING count(*) FILTER (WHERE status <> 'cancelado') > 0
ORDER BY comissao_estimada_centavos DESC, 1
`

type PorCanalParams struct {
	WorkspaceID uuid.UUID
	Usuarios    []uuid.UUID
	De          time.Time
	Ate         time.Time
}

type PorCanalRow struct {
	Canal                    string
	Pedidos                  int64
	ComissaoEstimadaCentavos int64
	ComissaoValidadaCentavos int64
}

func (q *Queries) PorCanal(ctx context.Context, arg PorCanalParams) ([]PorCanalRow, error) {
	rows, err := q.db.Query(ctx, porCanal,
		arg.WorkspaceID,
		arg.Usuarios,
		arg.De,
		arg.Ate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PorCanalRow
	for rows.Next() {
		var i PorCanalRow
		if err := rows.Scan(
			&i.Canal,
			&i.Pedidos,
			&i.ComissaoEstimadaCentavos,
			&i.ComissaoValidadaCentavos,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const porDia = `-- name: PorDia :many
SELECT
    (ocorrido_em AT TIME ZONE 'America/Sao_Paulo')::date AS dia,
    count(DISTINCT pedido_id) FILTER (WHERE status <> 'cancelado')::bigint AS pedidos,
    coalesce(sum(comissao_centavos) FILTER (WHERE status <> 'cancelado'), 0)::bigint AS comissao_estimada_centavos,
    coalesce(sum(comissao_centavos) FILTER (WHERE status = 'concluido'), 0)::bigint AS comissao_validada_centavos
FROM conversoes
WHERE workspace_id = $1
  AND usuario_id = ANY($2::uuid[])
  AND ocorrido_em >= $3 AND ocorrido_em < $4
GROUP BY dia
ORDER BY dia
`

type PorDiaParams struct {
	WorkspaceID uuid.UUID
	Usuarios    []uuid.UUID
	De          time.Time
	Ate         time.Time
}

type PorDiaRow struct {
	Dia                      pgtype.Date
	Pedidos                  int64
	ComissaoEstimadaCentavos int64
	ComissaoValidadaCentavos int64
}

func (q *Queries) PorDia(ctx context.Context, arg PorDiaParams) ([]PorDiaRow, error) {
	rows, err := q.db.Query(ctx, porDia,
		arg.WorkspaceID,
		arg.Usuarios,
		arg.De,
		arg.Ate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PorDiaRow
	for rows.Next() {
		var i PorDiaRow
		if err := rows.Scan(
			&i.Dia,
			&i.Pedidos,
			&i.ComissaoEstimadaCentavos,
			&i.ComissaoValidadaCentavos,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const porGrupo = `-- name: PorGrupo :many
WITH imp AS (
    -- Os unnest no SELECT andam juntos, posição a posição.
    SELECT unnest($4::int[]) AS grupo,
           unnest($5::uuid[]) AS usuario_id,
           unnest($6::uuid[]) AS produto_id,
           unnest($7::timestamptz[]) AS desde
)
SELECT
    imp.grupo::int AS grupo,
    count(DISTINCT c.pedido_id) FILTER (WHERE c.status <> 'cancelado')::bigint AS pedidos,
    coalesce(sum(c.valor_centavos) FILTER (WHERE c.status <> 'cancelado'), 0)::bigint AS vendas_centavos,
    coalesce(sum(c.comissao_centavos) FILTER (WHERE c.status <> 'cancelado'), 0)::bigint AS comissao_estimada_centavos,
    coalesce(sum(c.comissao_centavos) FILTER (WHERE c.status = 'concluido'), 0)::bigint AS comissao_validada_centavos
FROM imp
JOIN conversoes c
  ON c.usuario_id = imp.usuario_id
 AND c.produto_id = imp.produto_id
 AND c.ocorrido_em >= imp.desde
WHERE c.workspace_id = $1
  AND c.ocorrido_em >= $2 AND c.ocorrido_em < $3
GROUP BY imp.grupo
`

type PorGrupoParams struct {
	WorkspaceID uuid.UUID
	De          time.Time
	Ate         time.Time
	Grupos      []int32
	Usuarios    []uuid.UUID
	Produtos    []uuid.UUID
	Desde       []time.Time
}

type PorGrupoRow struct {
	Grupo                    int32
	Pedidos                  int64
	VendasCentavos           int64
	ComissaoEstimadaCentavos int64
	ComissaoValidadaCentavos int64
}

// Resultados por grupo de importações (as de uma lista da curadoria): cada
// posição dos arrays é um produto importado por um afiliado, a partir de
// quando. Conta só as vendas desse produto, desse afiliado, depois da
// importação.
func (q *Queries) PorGrupo(ctx context.Context, arg PorGrupoParams) ([]PorGrupoRow, error) {
	rows, err := q.db.Query(ctx, porGrupo,
		arg.WorkspaceID,
		arg.De,
		arg.Ate,
		arg.Grupos,
		arg.Usuarios,
		arg.Produtos,
		arg.Desde,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PorGrupoRow
	for rows.Next() {
		var i PorGrupoRow
		if err := rows.Scan(
			&i.Grupo,
			&i.Pedidos,
			&i.VendasCentavos,
			&i.ComissaoEstimadaCentavos,
			&i.ComissaoValidadaCentavos,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const porProduto = `-- name: PorProduto :many
SELECT
    item_id,
    max(produto_id::text) AS produto_id,
    max(item_nome)::text AS item_nome,
    max(loja_nome)::text AS loja_nome,
    count(DISTINCT pedido_id) FILTER (WHERE status <> 'cancelado')::bigint AS pedidos,
    coalesce(sum(quantidade) FILTER (WHERE status <> 'cancelado'), 0)::bigint AS itens,
    coalesce(sum(valor_centavos) FILTER (WHERE status <> 'cancelado'), 0)::bigint AS vendas_centavos,
    coalesce(sum(comissao_centavos) FILTER (WHERE status <> 'cancelado'), 0)::bigint AS comissao_estimada_centavos,
    coalesce(sum(comissao_centavos) FILTER (WHERE status = 'concluido'), 0)::bigint AS comissao_validada_centavos
FROM conversoes
WHERE workspace_id = $1
  AND usuario_id = ANY($2::uuid[])
  AND ocorrido_em >= $3 AND ocorrido_em < $4
GROUP BY item_id
HAVING count(*) FILTER (WHERE status <> 'cancelado') > 0
ORDER BY comissao_estimada_centavos DESC, pedidos DESC, item_id
LIMIT $5
`

type PorProdutoParams struct {
	WorkspaceID uuid.UUID
	Usuarios    []uuid.UUID
	De          time.Time
	Ate         time.Time
	Limite      int32
}

type PorProdutoRow struct {
	ItemID                   int64
	ProdutoID                interface{}
	ItemNome                 string
	LojaNome                 string
	Pedidos                  int64
	Itens                    int64
	VendasCentavos           int64
	ComissaoEstimadaCentavos int64
	ComissaoValidadaCentavos int64
}

func (q *Queries) PorProduto(ctx context.Context, arg PorProdutoParams) ([]PorProdutoRow, error) {
	rows, err := q.db.Query(ctx, porProduto,
		arg.WorkspaceID,
		arg.Usuarios,
		arg.De,
		arg.Ate,
		arg.Limite,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PorProdutoRow
	for rows.Next() {
		var i PorProdutoRow
		if err := rows.Scan(
			&i.ItemID,
			&i.ProdutoID,
			&i.ItemNome,
			&i.LojaNome,
			&i.Pedidos,
			&i.Itens,
			&i.VendasCentavos,
			&i.ComissaoEstimadaCentavos,
			&i.ComissaoValidadaCentavos,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salvarConversao = `-- name: SalvarConversao :exec

INSERT INTO conversoes (
    usuario_id, workspace_id, fonte, conversao_id, pedido_id, item_id, modelo_id, produto_id,
    item_nome, loja_nome, sub_id, canal, status, quantidade, valor_centavos, comissao_centavos,
    ocorrido_em, clicado_em
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12, $13, $14, $15, $16,
    $17, $18
)
ON CONFLICT (usuario_id, fonte, pedido_id, item_id, modelo_id) DO UPDATE SET
    workspace_id = excluded.workspace_id,
    conversao_id = excluded.conversao_id,
    produto_id = coalesce(excluded.produto_id, conversoes.produto_id),
    item_nome = excluded.item_nome,
    loja_nome = excluded.loja_nome,
    sub_id = excluded.sub_id,
    canal = excluded.canal,
    status = excluded.status,
    quantidade = excluded.quantidade,
    valor_centavos = excluded.valor_centavos,
    comissao_centavos = excluded.comissao_centavos,
    ocorrido_em = excluded.ocorrido_em,
    clicado_em = excluded.clicado_em,
    sincronizado_em = now()
`

type SalvarConversaoParams struct {
	UsuarioID        uuid.UUID
	WorkspaceID      uuid.UUID
	Fonte            string
	ConversaoID      int64
	PedidoID         string
	ItemID           int64
	ModeloID         int64
	ProdutoID        *uuid.UUID
	ItemNome         string
	LojaNome         string
	SubID            string
	Canal            *Canal
	Status           PedidoStatus
	Quantidade       int32
	ValorCentavos    int64
	ComissaoCentavos int64
	OcorridoEm       time.Time
	ClicadoEm        *time.Time
}

// Queries do módulo resultados. As leituras filtram por workspace e pelos
// usuários pedidos (o próprio afiliado, ou a turma que consentiu), além da RLS.
// Os dias contam no fuso de Brasília.
func (q *Queries) SalvarConversao(ctx context.Context, arg SalvarConversaoParams) error {
	_, err := q.db.Exec(ctx, salvarConversao,
		arg.UsuarioID,
		arg.WorkspaceID,
		arg.Fonte,
		arg.ConversaoID,
		arg.PedidoID,
		arg.ItemID,
		arg.ModeloID,
		arg.ProdutoID,
		arg.ItemNome,
		arg.LojaNome,
		arg.SubID,
		arg.Canal,
		arg.Status,
		arg.Quantidade,
		arg.ValorCentavos,
		arg.ComissaoCentavos,
		arg.OcorridoEm,
		arg.ClicadoEm,
	)
	return err
}

const sincronizacao = `-- name: Sincronizacao :one
SELECT usuario_id, status, pedida_em, concluida_em, conversoes, erro FROM sincronizacoes WHERE usuario_id = $1
`

func (q *Queries) Sincronizacao(ctx context.Context, usuarioID uuid.UUID) (Sincronizacao, error) {
	row := q.db.QueryRow(ctx, sincronizacao, usuarioID)
	var i Sincronizacao
	err := row.Scan(
		&i.UsuarioID,
		&i.Status,
		&i.PedidaEm,
		&i.ConcluidaEm,
		&i.Conversoes,
		&i.Erro,
	)
	return i, err
}

const totais = `-- name: Totais :one
SELECT
    count(DISTINCT pedido_id) FILTER (WHERE status <> 'cancelado')::bigint AS pedidos,
    count(DISTINCT pedido_id) FILTER (WHERE status = 'cancelado')::bigint AS cancelados,
    coalesce(sum(quantidade) FILTER (WHERE status <> 'cancelado'), 0)::bigint AS itens,
    coalesce(sum(valor_centavos) FILTER (WHERE status <> 'cancelado'), 0)::bigint AS vendas_centavos,
    coalesce(sum(comissao_centavos) FILTER (WHERE status <> 'cancelado'), 0)::bigint AS comissao_estimada_centavos,
    coalesce(sum(comissao_centavos) FILTER (WHERE status = 'concluido'), 0)::bigint AS comissao_validada_centavos,
    count(DISTINCT usuario_id) FILTER (WHERE status <> 'cancelado')::bigint AS afiliados
FROM conversoes
WHERE workspace_id = $1
  AND usuario_id = ANY($2::uuid[])
  AND ocorrido_em >= $3 AND ocorrido_em < $4
`

type TotaisParams struct {
	WorkspaceID uuid.UUID
	Usuarios    []uuid.UUID
	De          time.Time
	Ate         time.Time
}

type TotaisRow struct {
	Pedidos                  int64
	Cancelados               int64
	Itens                    int64
	VendasCentavos           int64
	ComissaoEstimadaCentavos int64
	ComissaoValidadaCentavos int64
	Afiliados                int64
}

func (q *Queries) Totais(ctx context.Context, arg TotaisParams) (TotaisRow, error) {
	row := q.db.QueryRow(ctx, totais,
		arg.WorkspaceID,
		arg.Usuarios,
		arg.De,
		arg.Ate,
	)
	var i TotaisRow
	err := row.Scan(
		&i.Pedidos,
		&i.Cancelados,
		&i.Itens,
		&i.VendasCentavos,
		&i.ComissaoEstimadaCentavos,
		&i.ComissaoValidadaCentavos,
		&i.Afiliados,
	)
	return i, err
}
